### ISSUE TITLE
Abstractions in IPLD discussion

### ISSUE THREAD

**Issue by nicola** [ipfs/pm#103]
# discussion on https://github.com/ipfs/specs/issues/91

I'm also calling a meeting together to discuss the two levels of abstractions in IPLD described in the issue https://github.com/ipfs/specs/issues/91

## Agenda

- sync on current ipld
- understanding motivations for the higher level (ipld objects)
- concrete decisions on low level (ipld blocks)
- finding a name for ipld objects/ipld blocks
- agree on syntax (different or merged)

Ping @Stebalien @diasdavid @jbenet @mildred @dignifiedquire 

Everyone is welcome to join, I will make sure there will be a write up out of this

## Candidate coordinates

- Sometime monday 4/18. subject to availability of people above (except 2-3:30 EST)

**Comment by dignifiedquire** [comment]
I'll try to be around :)

**Comment by Stebalien** [comment]
I'm free all day (after 10am EDT).

On April 17, 2016 5:56:04 PM EDT, Nicola Greco <notifications@github.com> wrote:
># discussion on https://github.com/ipfs/specs/issues/91
>
>I'm also calling a meeting together to discuss the two levels of
>abstractions in IPLD described in the issue
>https://github.com/ipfs/specs/issues/91
>
>## Agenda
>
>- sync on current ipld
>- understanding motivations for the higher level (ipld objects)
>- concrete decisions on low level (ipld blocks)
>- finding a name for ipld objects/ipld blocks
>- agree on syntax (different or merged)
>
>Ping @Stebalien @diasdavid @jbenet @mildred @dignifiedquire 
>
>Everyone is welcome to join, I will make sure there will be a write up
>out of this
>
>## Candidate coordinates
>
>- Sometime monday 4/18. subject to availability of people above
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ipfs/pm/issues/103

-- 
Steven Allen

**Comment by jbenet** [comment]
I'd like to participate, but im unlikely to be able to make it to this on monday. Perhaps we could have it on {Tue, Wed, Thu} while I'm in Boston ?

**Comment by jbenet** [comment]
(though feel free to have a call without me on monday)

**Comment by nicola** [comment]
I am happy to move it on Wed (or having it both today and on Wed)

**Comment by nicola** [comment]
I would suggest 2pm EDT on Wed

**Comment by Stebalien** [comment]
Works for me.

**Comment by diasdavid** [comment]
I can make it one hour earlier. But if it is hard to adjust, I'm happy to get the notes after. This week is a super intensely busy week for me and I know it is hard to find a time that is convenient for everyone.

**Comment by RichardLitt** [comment]
Let me know what to add to the calendar.

**Comment by nicola** [comment]
@Stebalien can you do 1h earlier?

**Comment by Stebalien** [comment]
1pm? I can do that.

**Comment by nicola** [comment]
@RichardLitt let's go ahead if @jbenet confirms

**Comment by jbenet** [comment]
I can do 1pm. i have a hard stop at 2pm.

**Comment by dignifiedquire** [comment]
Notes:

---

# IPLD Discussion 

[x] sync on current ipld
[x] understanding motivations for the higher level (ipld objects)
[ ] concrete decisions on low level (ipld blocks)
pathing (create an issue on the `//` or `/@link` or new path delimeter🚀)
@transform (create an issue getting all the possible ways of doing this)
sharing file (merge)
sharing folders (merge)
indexing 
aggregation (split)
functional datastructures
@transforms
[ ] finding a name for ipld objects/ipld blocks (of any)

## Abstractions / Layers Discussion
- https://github.com/ipfs/specs/issues/91

Deliverables
- spec that has these properties (@transform)
- {
    foo: {
        perm: 0777,
        @link: {  }
        @embedded: { other data },
        secret: {
            @link: '/ipfs/<hash>'
        }
    }
}
- {
    "foo":  link("/ipfs/hash/..."),
    "foo/": {
        perm: 0777,
    },
    "foo":  "test"),
    "foo/": {
        perm: 0777,
    },
    "bar":  link("/ipfs/hash/..."),
    "bar/": {
        perm: 0777,
    },
}
- {
    "foo":  {
        @link: "Junk",
    },
}


Using "." and "/"

{
    foo: {
        jpg: {
        @link: "Qmaaa"
mode: 777 
        }
    } 
    foo.jpg: {
        @link: Qmbbb
mode: 755
        }
}

Qmaaa = {
mode: 111
}

Qmbbb = {
mode: 222
}

> $root/foo/jpg/mode
777

> 


> foo/jpg
2
> foo.jpg
2

{
    foo: {
        jpg: 2
    } 
    foo/jpg: 1
}

-> Same issue as above?
> foo/jpg
> 2

Goals
- Small set rule

TODO
- aggregate a list of work doing this
-

**Comment by RichardLitt** [comment]
Can this be closed? What are the actionable items, and who is assigned them?

**Comment by RichardLitt** [comment]
Let us reopen as needed.
