### ISSUE TITLE
Tool Request: Issue Status Badges

### ISSUE THREAD

**Issue by jbenet** [ipfs/pm#111]
Github issue statuses are really useful to know. We are using issues to list other issues in task lists (checkboxes), which creates nice roadmaps and dependency listings. This works very well with Github's issue progress indicators.

It would be very, very useful to be able to embed readme badges that show an issue's status, in particular the "progress bar".

For example, being able to turn this:

![](http://gateway.ipfs.io/ipfs/QmYpKT3ySpqiEpDzXqQccbSKpZ2YB4XK4RWZBSSQ3qgBUo/cap.png)

Into this:

![](http://gateway.ipfs.io/ipfs/QmUqR4pZK4EmTQd23vumnRhPrJa9HcmSs8xNsddJc7tat9/cap.png)

Where the progress bar is calculated live from an issue's task completion.

Similar to https://github.com/fehmicansaglam/progressed.io -- but the server image renderer would check a particular github issue.

@RichardLitt think you'd like to tackle this? would be very useful for Roadmaps, Milestones, and PMing in general.

cc @em-ly

**Comment by RichardLitt** [comment]
I can tackle this, sure. Will be nice to have a refresher on how to run server-side scripts.

**Comment by RichardLitt** [comment]
Relevant issue for Waffle: https://github.com/waffleio/waffle.io/issues/1623

**Comment by RichardLitt** [comment]
I'm curious, @jbenet: how would this be better than milestones? Because it is embedded in a README? Would it be cheaper to change our process?

**Comment by RichardLitt** [comment]
Milestones don't reach across repos. So, they're out! On to using GitHub's api to scrape issues, then.

**Comment by RichardLitt** [comment]
I am working on this, but being mindful of other priorities at the moment.

**Comment by em-ly** [comment]
status update?

**Comment by RichardLitt** [comment]
Still here: 

> I am working on this, but being mindful of other priorities at the moment.

I haven't had solid hacking time in a while. Perhaps next week?

Tracking this here: https://github.com/RichardLitt/github-task-status/issues/1

**Comment by diasdavid** [comment]
@jbenet seems that github lost your screenshots (wat?) 

![image](https://cloud.githubusercontent.com/assets/1211152/20098377/643333b0-a5ab-11e6-9568-a8b0c177cf70.png)

![image](https://cloud.githubusercontent.com/assets/1211152/20098387/6b647fc2-a5ab-11e6-8b62-2089e9db563b.png)

**Comment by RichardLitt** [comment]
That is super weird! 

Update: I have not prioritized this, because I am not sure how much it would be used at the moment. I have higher priorities right now, but if anyone thinks I should highlight it sooner, please let me know.

**Comment by diasdavid** [comment]
Do we still want this or have we shifted our interest to `depviz`? (Close if not necessary anymore)
