### ISSUE TITLE
Switch back to One Week sprints

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#115]
I'm not sure that the two week sprint is helping us do more than keeping track with one weeks sprints would. We switched over when we went to short video hangouts, but I don't see why that can't be alternate weeks, but still be maintained with a weekly sprint issue for tracking to dos. 

Shall we switch back to one-week sprints? Would that help anyone? I know it would, me.

**Comment by Kubuxu** [comment]
I think it is good idea, today short sprint went well.

**Comment by whyrusleeping** [comment]
Agreed on the short sprints being very helpful. :+1:

**Comment by RichardLitt** [comment]
Going with this going forward. Will open a new issue as more patterns make sense.
