### ISSUE TITLE
Automating Times

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#121]
I am having issues repeatedly making figuring out the right time for events, and making that match the calendar. I would like to automate this. 

@haadcode: 

>  the timezone issue sounds like an ideal problem to automate. from what I read, it’s a human error atm. let’s be lazy and get computers to do what we don’t want to/should do :slightly_smiling_face: richard: there’s probably a js library to a) display user’s local timezone time for the sprint b) display user’s timezone c) display UTC/other timezone times. not sure how it can be integrated to a GH .md file due to security restrictions, but there’s probably a way to display it. it’d be ideal if, when I go to check the sprint time, it would display me:
> `Sprint on Xth of N: 17:00 (Your local timezone, Berlin GMT+2) - 16:00 (UTC)`
> <— that’s all the info I need to make sure I catch the right time. what do you think?

No, I think we need more than that. That would have issues with people using VPNs and so on. I think we should simply automate the conversion between times, and have a module that syncs to the google calendar, if possible. Building a time converter sounds like a very easy task to do, actually. When I make the issue, I can simply plug in a time to the CLI tool, and get out the output I need. Sound good?

**Comment by Kubuxu** [comment]
You could use Greasemonkey (for FF or corresponding tool for Chrome) and write userscript that would convert Zulu time into user's timezone and display it on page.

It should be quite easy.

**Comment by RichardLitt** [comment]
Smart idea, but I'm not sure adding a dep for the user is the way to go. Too many moving pieces.

**Comment by RichardLitt** [comment]
@dignifiedquire in IRC:

> 15:56:22 <dignifiedquire> we should have an irc bot that we can ask, when will the sprint be 
15:56:31 <dignifiedquire> and it will give you a countdown rather than the time

**Comment by diasdavid** [comment]
@RichardLitt was this achieve with your new sprint helper?

**Comment by RichardLitt** [comment]
No, but it easily could. Currently, it just prints out the template for the sprint call notification. Having it calculate the time until the next call would be a good thing to do. Opened an issue about it.

**Comment by RichardLitt** [comment]
I believe this is currently being solved in https://github.com/ipfs/sprint-helper. It will be fixed by using the Google Calendar as a source of truth.

**Comment by diasdavid** [comment]
Let's continue on #433
