### ISSUE TITLE
Sprint: July 11 → July 25th and the IPFS Workshop

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#123]
# Sprint July 11 → July 25th

This sprint, instead of having the long 30-minute discussions, we are having another short video sprint. This is because of travel issues and vacation for many endeavors, and because of a tight schedule at the moment for a few people working on IPFS.

**For this sprint** please do the following:
- Put your **completed tasks** in the [old sprint issue](https://github.com/ipfs/pm/issues/113).
- Put your To Do items for the upcoming sprint in the Etherpad for the video sprint **before** the sprint. (I'll ping you about this, if you're in the [active contributor list](https://github.com/ipfs/pm#active-contributors)).
- Finalize your To Do items during the hangout and put them in this issue by Tuesday, July 5th, the Solstice. ☀️ 

## Sprint Discussions

[Schedule](https://github.com/ipfs/pm#sprint-discussion-schedule)

Endeavour         | Lead            | Time | Pad
:---------------: | :-------------: | :--------------------------: | :----:
Video sync              | @RichardLitt    | 9:00PDT 12:00EDT 16:00Z 17:00BST 18:00CEST  | https://public.etherpad-mozilla.org/p/sdfklasjflsd-ipfs-july-11-video-sync

@RichardLitt will post the Hangout link on the IRC channel, as normal.

## Sprint Deliverables

- Add your tasks below in a comment, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.
- Add your To Dos in Markdown format. That means using `- [ ]`, which GitHub automatically converts to a checkbox.
- As the sprint progresses, refer back to this issue and check of any tasks you have done, and subdivide, delete, or add tasks accordingly. That way, the list at the end gives an accurate depiction of what was done this sprint.
- If anyone seems to be doing something you could do, approach them and see if you can take any of their tasks. Likewise, if you have too much.

**Comment by lgierth** [comment]
Yeeaah definitely not gonna make it :) flight still hasn't taken off

**Comment by RichardLitt** [comment]
@lgierth Can you post your updates and todos?

**Comment by jbenet** [comment]
- W3C / IETF standardizaton
  - IPLD
  - libp2p interfaces
  - multiformats
- cli args -- go-ipfs
- mapping -- https://github.com/ipfs/notes/issues/142
- xtp - https://github.com/ipfs/xtp
- ipld importers - https://github.com/ipfs/notes/issues/144
- ipfs-cluster - https://github.com/ipfs/ipfs-cluster
- machine learning bitswap
- project management

**Comment by RichardLitt** [comment]
This week is not the most code intensive, for many of us. If anyone has any questions, feel free to ping me on any social media.

**Comment by RichardLitt** [comment]
Hey all: the Protocol Labs and IPFS team have been meeting this week to figure out our quarterly goals for the next quarter, and don't have a significant amount of work to talk about or surface right now. So, we've decided that it may be best not to have the sprint syncs today. 

However! We would like to draw attention to the [IPFS Workshop](https://github.com/ipfs/community/issues/142) we'll be having next week. Please check it out; this is there for you, and we'll be able to have remote participation as well. This will be a good time to jump in technically and see what we're up to going forward. 

Feel free (as always!) to ping me personally on IRC as `richardlitt` or anywhere else if you've got questions about this. See you next week.

**Comment by RichardLitt** [comment]
Closing this as largely inactive. Will open a new sprint issue shortly.

**Comment by lgierth** [comment]
### @lgierth sprint 11-jul-2016 -> 25-jul-2016

- go-ipfs
  - [x] handled security vulnerability
  - [x] changelog for v0.4.3-rc1
  - [x] release v0.4.3-rc1
  - [x] report v0.4.3-rc1 bugs ipfs/go-ipfs#2987 ipfs/go-ipfs#2988
  - [x] musl libc support for fs-repo auto-migrations
  - [ ] switch /ipns/example.com from static TLD list to regexp
- multiformats
  - [x] multiformats.io domain
  - [x] multigram spec work
  - [ ] multihash spec review
  - [ ] gnunet contact re: xtp / exo-transports
- infrastructure
  - [x] shut down v03x network
  - [x] remove v03x provisioning code
  - [x] provsn secrets handling
  - [x] fix provsn parallelism
  - [x] vacation handover to @whyrusleeping and @Kubuxu
  - [ ] cjdns rekeying
  - [ ] rebuild nihal
- misc
  - [x] team week
  - [x] ipfs workshop
  - [x] fly back to berlin
  - [x] security@ipfs.io gpg key
