### ISSUE TITLE
IPLD spec refining call - round 1

### ISSUE THREAD

**Issue by nicola** [ipfs/pm#124]
IPLD stakeholders should get together to agree on [some pending refinement in IPLD](https://github.com/ipld/specs/issues?q=is%3Aissue+is%3Aopen+label%3Aneeds-agreement). These issues are not necessarily new features but restrictions that we may have to specify in the spec to make it less ambiguous.

Partecipants are expected to be informed about the different issues, they should:
- Read the different issues beforehand
- Raise concerns and give opinion offline (so that everyone is ready to agree/further discuss)

Agenda so far:
- Canonical representation (https://github.com/ipld/specs/issues/6)
- Multiple hash pointers in link object (https://github.com/ipld/specs/issues/5)
- Use of IPLD pointers in link object (https://github.com/ipld/specs/issues/3)
- Allow properties in link object (or reserve that space) (https://github.com/ipld/specs/issues/2)
- Relative Paths in IPLD (https://github.com/ipld/specs/issues/1)
- IPLD links must be IPLD pointers (https://github.com/ipld/specs/issues/8)
- Requiring prefixing of paths (https://github.com/ipld/specs/issues/7)
- Mutable pointers (https://github.com/ipld/specs/issues/9)

We can do this in 2 weeks time (who should I ping? @RichardLitt )
---

Ping @stebalien, @mildred, @jbenet, @dignifiedquire

**Comment by dignifiedquire** [comment]
> who should I ping?

For setting up a call or for what?

**Comment by nicola** [comment]
@dignifiedquire Yes, setting up the call, adding it to the calendar and finding the right timing

**Comment by RichardLitt** [comment]
@nicola Best thing to do is to open an issue in github.com/ipfs/pm about a planned call. Should probably happen on Monday near the sprint. Ping anyone who is interested, and they can follow along there. 

LMK if you want me to go through the legwork of this for you! :D

**Comment by nicola** [comment]
(Is this issue that I opened what I need to open?)

**Comment by RichardLitt** [comment]
Ah! Wow. I thought this issue was somewhere else. What a doofus I am! 

Perfect! This is great. I'll add this to the sprint on Monday the 8th. Ping anyone you think should be there and point them here. :D!

**Comment by nicola** [comment]
Sorry everyone, I missed @RichardLitt post, this will happen the coming Monday the 8th (@RichardLitt)

**Comment by nicola** [comment]
@dignifiedquire, @diasdavid, @mildred, @stebalien can we have this conversation on Monday after the sprint?

**Comment by diasdavid** [comment]
Sounds good to me!

**Comment by jbenet** [comment]
Most important thing to agree on (IMO) is CID, unless that's already agreed
on.

**Comment by nicola** [comment]
cc @edsilv

**Comment by nicola** [comment]
@RichardLitt thi is happening after the "all hands" meeting, 12pm EDT

**Comment by RichardLitt** [comment]
@nicola Sounds good. There are a few other ones happening after the all hands, so let's discuss in that call when to schedule this.

**Comment by Stebalien** [comment]
IRC? (iirc://rc.freenode.net#ipfs)?

**Comment by Stebalien** [comment]
@nicola I assume this can be closed. Etherpad: https://public.etherpad-mozilla.org/p/r.4e9ac4b53b0d5dab99a8a6995909a8e1

**Comment by nicola** [comment]
Copying the notes over here

--

# IPLD 08 August 2016

Welcome! Note: please add your name to etherpad on the right --------------->

**Moderator:** David Dias (@diasdavid)

**Notetaker:**  (Nicola Greco @nicola) (with em-ly helping!)(\o/)

**Attendees** 
@em-ly
@jbenet
@nicola
@dignifiedquire
@diasdavid
@EdwardSilverton
@flyzumwalt
@stebalien


## Agenda
agenda is here: https://github.com/ipfs/pm/issues/124

 0.0. CIDv1 https://github.com/ipfs/specs/issues/130
Canonical representation ( https://github.com/ipld/specs/issues/6
Multiple hash pointers in link object ( https://github.com/ipld/specs/issues/5
Use of IPLD pointers in link object ( https://github.com/ipld/specs/issues/3
Allow properties in link object (or reserve that space) ( https://github.com/ipld/specs/issues/2
Relative Paths in IPLD ( https://github.com/ipld/specs/issues/1
IPLD links must be IPLD pointers ( https://github.com/ipld/specs/issues/8
Requiring prefixing of paths ( https://github.com/ipld/specs/issues/7
Mutable pointers ( https://github.com/ipld/specs/issues/9

## Notes
 - Calls biweekly, issue will be created with agenda topics that need to be covered
 - CID (content ID)
 
##  Action items
- CID
  - [ ] more time
  - [ ] implementation
  - [ ] write its own spec
 - [ ] discuss where CIDs belong to (multiformats, IPLD, ?)




----
Ref prefixing of paths

1. For the notion of linking between protobuf to protobuf there is an implicit CID of v0, protobuf, base58. To allow for the 
  integration of other raw objects, like git objects we need this implicit thing as well. Given that then all links inside networks
  are using implicit CIDs, except for IPLD do we want to do the same thing for IPLD inside links?
2. Do we need to use /ipld/<cid>  or <cid> for linking to IPLD objects inside IPLD objects?

**Comment by nicola** [comment]
Will close this once I create all the necessary issues and document what I have done here

**Comment by nicola** [comment]
I updated all the issues we have discussed and documented the work done in the [captain.log](https://github.com/ipld/specs/issues/13#issuecomment-238017395)

**Comment by nicola** [comment]
(should have been closed then!)
