### ISSUE TITLE
Identify which Projects Need Roadmaps and Who Maintains those Roadmaps

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#135]
Which projects go on the Organizational Roadmap (see description in https://github.com/ipfs/pm/pull/131)? 

A quick list of projects I've seen mentioned:
- IPFS (general)
- go-ipfs
- js-ipfs
- orbit + orbit-db (aka "dynamic content"?)
- IPLD
- PubSub
- libp2p
- XTP
- IPFS Cluster
- Packet Management
- Multiformats
- Infrastructure
  etc..

**Comment by flyingzumwalt** [comment]
We can write this list into the config file for @haadcode's roadmap-generator. That way we have a file in a git repo explicitly listing the repositories that we are watching. See PR #176

**Comment by RichardLitt** [comment]
Has this issue changed? 

> Which projects go on the Organizational Roadmap (see description in #131)? Who is responsible for maintaining the roadmap of each project?

Is this you, now?

**Comment by haadcode** [comment]
> Which projects go on the Organizational Roadmap (see description in #131)? Who is responsible for maintaining the roadmap of each project?
> Is this you, now?

I believe @flyingzumwalt is responsible for the *organization's roadmap*. Project leads are still responsible for individual project roadmaps.

**Comment by flyingzumwalt** [comment]
Yep. What @haadcode said. I'll update the text so the ticket remains focused on the actual task at hand - identifying which projects need to be included on the org roadmap.
