### ISSUE TITLE
Decide whether Roadmap Updates are Quarterly or Third-ly

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#142]
Spinning this off from comments on the [PM Process Document](https://github.com/ipfs/pm/pull/131/files#r74581761)

@diasdavid comments:

> at last team gathering, there was a proposal to move it to 4 months, shall we consider that before getting the pm doc in stone?

**Comment by flyingzumwalt** [comment]
A standard Quarterly calendar would have Quarterly Updates (and meetings) in
 1. January
 2. April
 3. July
 4. October

If we broke the year into thirds, we might do updates in
 1. January
 2. May
 3. September  

or, alternatively, April, August, December

**Comment by diasdavid** [comment]
I would prefer it to be 'Third-ly' mainly due to:

- We typically have ideas and plans that could fill an entire year of work, just from one roadmap update. By giving ourselves an extra month, we can finish more stuff, having to port less to the next following 4 months.
- It reduces the time spent in travel. The logistics required to organize a gathering are time consuming and it will only get more difficult with the core growing. Right now we spend close to 2 weeks (at least), plus the time to prepare for it and the time of recovering and getting up to regular pace (making the total roughly 1 month, one third of a quarter).

**Comment by jbenet** [comment]
- We don't have to travel for all quarterly reviews. we could do that 2x or 3x.
- Nothing prevents us from breaking large things up and having their milestones span multiple quarters. we do this already.
- The problem with longer stretches is that the cadence becomes long and easier to get derrailed into less useful stuff. we need to be able to -- as a team -- react very quickly to changes in the space. already doing this review quarterly has me concerned: our focus cycle is quite long.
- i actually think that as we get really good at PMing (roadmaps, milestones, goals, etc). we will have to do a lot less work in these regular reviews.
- We need to get into a strong cadence around it.
- we don't have to travel. we don't have to meet physically. we don't have to turn this into a massive time investment every time. 
- i think everyone is reacting negatively to spending so much time travelling this last week, and that was much more a mistake in planning than in time spent PMing: we did not set an end date and we tacked on more things like hacking and workshops.
- We should be able to do a PMing review distributed and without the massive investment. I propose we try this for Q4.

**Comment by jbenet** [comment]
- I would add that, right now, i do not feel confident that our team can react to a serious product race. It would take us until a quarter boundary to review and refocus our efforts.
- Once we demonstrate the ability to be nimble and agile in this respect, to get PMing so well that we're on top of all our roadmap, milestones, and goals, and we're able to steer towards drastically different focus "mid quarter" by adjusting our milestones without a large sync review THEN we can see about lengthening this parameter of the cycle.
- Until then, i am already uncomfortable with the length here, and broadening it would make me quite alarmed about the combination of that length and our present ability to respond to changing product needs as a team.

**Comment by jbenet** [comment]
- Realistically, with proper async prep work, we should be able to do a "Roadmap Review" across ALL projects in 1-2 sync days.

**Comment by jbenet** [comment]
- Another good take away: Do Less. Commit to less per cycle. 
- if stressed about about not finishing milestones in a cycle, the appropriate response should not be "make the cycle bigger" (that's killer for development teams), but rather "push milestones to the next cycle".
-  I'm very happy with how @haadcode was very deliberate in keeping the amount of work down to something he could reasonably manage.
- If we need to push milestones out to other quarters, so be it. if we need to get more help, so be it.

**Comment by dignifiedquire** [comment]
- I very much agree with the things mentioned from @jbenet. Review & Planning should happen quarterly, but that doesn't mean we have to always meet up in person for a long period of time. 
- We really need to get better at not exhausting ourselves at these meetings as a group. Some of us manage better than others. The fact is though that a lot of us got sick shortly after these meetings and most of us are pretty exhausted when they come home. If we manage to take better care of ourselves and not pushing our limits that much we should have a much better time getting back into a regular schedule when we come home.

**Comment by flyingzumwalt** [comment]
I also agree with @jbenet's concerns about cadence and losing the ability to respond to change. Even at big institutions and giant behemoth corporations they keep a quarterly pulse. If that pulse is too fast for us, that's cause for concern.

**Comment by flyingzumwalt** [comment]
@jbenet's proposed 
> We should be able to do a PMing review distributed and without the massive investment. I propose we try this for Q4.

I opened #143 so we can discuss what that would look like, which is a separate conversation from this ticket's goal: Deciding whether Roadmap Updates are Quarterly or Third-ly

**Comment by diasdavid** [comment]
Note that you will always have my full support to anything that can increase our productivity and ability to do more great and greater quality things. I fully adhere to the quarterly meetings when it comes to, as you said, being able to react, readjust and reroute if needed.

It is important that for successful quarterly meetings and plans that are reactive and enable the team to do their best work, reality takes precedence over an hypothetical plan, things like: the RTT delay for feedback on the preparation; dev time that is spent in preparation of sessions; time required to recover from the backlog; the need to ramp up new people and so on, are taken into account during those plans (i.e: Don't save till last week to prepare things), therefore ensuring that we don't fall into the same time sink traps again.

**Comment by diasdavid** [comment]
This issue is out of date. We do now quarterly OKRs and long term project Roadmaps. Closing
