### ISSUE TITLE
Mediachain collaboration call

### ISSUE THREAD

**Issue by parkan** [ipfs/pm#145]
(feel free to reassign/close/move this as necessary, I'm not entirely sure where I should be opening this)

as per conversation with @jbenet, let's try to set up a regular call w/mediachain team -- we're moving into active development on top of libp2p/IPFS and would love to stay in sync + contribute to upstream

areas we'd like to cover on an ongoing basis (I have a more detailed agenda, as well):

* IPLD (roadmap, gotchas, how can we help)
* performance at large scale (20TB+ trees, billions of objects)
* pubsub
* CRDTs
* libp2p internals/modularization (DHT, discovery, overlay, protocol hiding)

could be attached to the monday call or separate

**Comment by jbenet** [comment]
awesome, this sounds great. would mondays work for you? may keep you in sync with other things going on. we can do another time if better though. 

cc @whyrusleeping @diasdavid @flyingzumwalt @RichardLitt

**Comment by diasdavid** [comment]
Let's keep as much as possible during the Monday syncs and reserve a slot in another day of the week for extra questions if needed.

@parkan you can do it by going to the sprint issue (opens at least 3 days before every sprint) and propose the topics for discussion, the more detailed the better. Next sprint - https://github.com/ipfs/pm/issues/146

**Comment by parkan** [comment]
Added some agenda items of immediate concern to the issue

**Comment by jbenet** [comment]
@parkan this is great! Let's make sure this call gets scheduled, and we could even schedule a regular time weekly to check in. Does today at 3:30p work for you? Else another day?

This is a longer discussion, and the roadmapping sprint calls are for upkeep on project management, not for in depth discussion (sorry for the confusion-- we're improving our sprint day which may cause some confusion).

**Comment by diasdavid** [comment]
This happened, notes on https://public.etherpad-mozilla.org/p/ipfs-2016-08-22-mediachain

Thank you :)
