### ISSUE TITLE
Test out YouTube Live

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#151]
This is an issue to remind me to check out YouTube Live. Google Hangouts On Air is going away on September 12th :'(. So, we'll need to replace this with something else. I need to test this before the next Monday call. 

[Goodbye Hangouts On Air](https://support.google.com/youtube/answer/7083786?p=live_hoa&rd=1)

**Comment by diasdavid** [comment]
Do we need to do something special for today's call?

**Comment by diasdavid** [comment]
Let's test it this week, we probably are able (since they separeted the services) to attach a Google Hangouts from a Google Apps (@ipfs.io) account to a Youtube LiveStream of a Google Page (IPFS)

**Comment by flyingzumwalt** [comment]
One thing to keep in mind: We want to retain the option of having participants share their screens for demos, etc.  Whichever approach we take (ie. zoom + youtube live stream) let's make sure it lets us do that smoothly.

**Comment by dignifiedquire** [comment]
@RichardLitt any update on this?

**Comment by RichardLitt** [comment]
@dignifiedquire Not yet. On my list of things to do today.

**Comment by RichardLitt** [comment]
This works. This issue can be closed when we update the Process doc.

**Comment by dignifiedquire** [comment]
I don't think this can be marked as successful. We are still hitting the 10 participants limit which at the current size of our team is not acceptable anymore, as we know before hand that not everyone who wants to join can join.

**Comment by RichardLitt** [comment]
Looks like it might be possible to live stream from Zoom to YouTube. [Article](http://ptzoptics.com/live-streaming-video-conference-youtube-live/). This might be costly, though. I think it would be worth trying; @dignifiedquire can you read this and double check with this seems smart?

**Comment by dignifiedquire** [comment]
I was able to stream a zoom call directly to youtube live using 

- https://obsproject.com/ and following this guide to capture desktop audio
- https://socapex.wordpress.com/2015/11/29/capturing-desktop-audio-on-el-capitan/ 

It worked pretty well so we can test this out on Monday :)

**Comment by Kubuxu** [comment]
In future it would be best to have a server doing that automagically but it will be a bit harder.
