### ISSUE TITLE
Test out the PM Process on go-ipfs Project

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#153]
Other than a bit of rewording (I've got a PR incoming on that front), the main things we need to do to the PM document are to 
- add good, concrete examples
- tweak it to work as a clear, straightforward guide that people can rely on and refer to
- define roles clearly

Rather than cooking those up in the abstract, I propose that @em-ly, @whyrusleeping and I try applying this model, as it's expressed in the document right now, to go-ipfs. That will let us 
- figure out what's confusing or unclear in the document
- sort out an iplementation of the mechanics -- translating this model into real, working GH issues, milestones, roadmap, waffle board, etc (inspired by existing examples in js-ipfs and orbit)
- identify good examples to explain the model

I'm suggesting go-ipfs as the starting point because 
1. Its waffle board as-is seems to be the closest reflection of a "middle of the road" implementation of mechanics (though some tweaks still necessary)
2. Getting the PM process and roles right for go-ipfs will free up @jbenet's time
3. It lets us experiment with the distinction between responsibilities of a Project Lead (@whyrusleeping), Project Manager (@em-ly) and Product Owner (@jbenet) so that we can represent it accurately in the PM document.
4. It lets us revisit the go-ipfs roadmap & milestones for Q3 while we figure out the mechanics for expressing the Project Roadmap

Whaddaya think?

cc @haadcode @diasdavid @RichardLitt

**Comment by diasdavid** [comment]
Sounds good :) Thank you @flyingzumwalt

**Comment by RichardLitt** [comment]
SGTM2.

**Comment by flyingzumwalt** [comment]
@whyrusleeping @em-ly how do you want to start this? Phone call? @whyrusleeping when will you be traveling?

**Comment by whyrusleeping** [comment]
i'll be in a plane on monday, shortly after the sprint.

**Comment by diasdavid** [comment]
Is `go-ipfs` fully onboarded in the PM process? What is missing exactly?

**Comment by flyingzumwalt** [comment]
Yes it's basically onboarded. I want to do a final pass, mainly watching how we use the waffle board and the roadmap. I also will be updating the PM document to _remove_ minor stuff that we're not doing and seem to be fine without.

It's fine to close this issue though. We've done what it proposes -- testing the PM process with the go-ipfs project.
