### ISSUE TITLE
Better scheduling

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/pm#157]
At the moment we are moving and adjusting the schedule on Monday, which is far from ideal. 
To fix this I propose the following structure:

- For all regular calls (all hands, go-ipfs, js-ipfs, libp2p) always have the same times, unless there is a very good reason.
- Any adjustments to the schedule should be made latest the Friday before.
- The only adjustment that is okay to do on Monday is adding calls, but not moving around already announced ones.

**Comment by jbenet** [comment]
Agree with this. thank you

**Comment by flyingzumwalt** [comment]
If we make the scheduling more stable, will that let us publish links to the hangouts/zoom calls in advance and put them in the sprint issue? @RichardLitt is there another reason why we create those links last-minute?

**Comment by RichardLitt** [comment]
Yes; I actually start them in the hangout, and IIRC there was some issue with longstanding hangouts. It's easier for me to create them on the fly; however, bunching them may also be possible, as I haven't tested this in a while.

**Comment by dignifiedquire** [comment]
@RichardLitt have you put some of this into the notes somewhere already?

**Comment by RichardLitt** [comment]
In the notes? Not yet; I've created the issue and am asking people if it is OK. See https://github.com/ipfs/pm/issues/162. Would it be better if I included this in a protocol somewhere?

**Comment by dignifiedquire** [comment]
@RichardLitt I think it would make sense to add it here
- https://github.com/ipfs/pm#sprint-planning and in 
- https://github.com/ipfs/pm/blob/master/admin-guides/sprint-calls-prep.md

**Comment by RichardLitt** [comment]
Assigning to me. Will get to it.
