### ISSUE TITLE
Clearly define Product Owner, Project Lead, and Project Manager 

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#164]
Currently roles like Product Owner and Project Manager don't have definitions and it's not clear how they relate to each other.

Roles defined in the Document
- Product Owners
- Project Leads _(same as Project Captains?)_
- Project Managers
- Program Manager
- Sprint Administrator
- Sprint Master
- Discussion Leads
## Why Define these Roles

By providing these definitions we
- Allow the people in these roles to know what is expected of them
- Let everyone know what to expect of the persons in each of these roles
- Gives everyone cues about where to direct their questions and requests

Its also worth taking the time to define these roles because it allows us to make sure that we're setting realistic expectations.
### Product Owners

Examples:
- IPFS: @jbenet 
- filecoin: @jbenet 
- js-ipfs: @diasdavid 
- go-ipfs: @whyrusleeping 
- IPLD: @nicola

_This is @flyingzumwalt's condensed sense of what the role Product Owner means in the software industry (when it's used well)._

Each project has only one Product Owner. This person is responsible for crafting and maintaining the narrative that defines the product, its users, and the user experience. While this narrative is created by everyone -- users, contributors, maintainers, etc. -- the Product Owner is responsible for ensuring that the narrative remains cohesive and consistent. The Product Owner is also responsible for ensuring that the narrative evolves in response to changes in users needs, technical possibilities, etc.

Some Product Owners must work closely with each other in order to achieve consistent user experience across a broad base of adopters. For example, the Product Owners for js-ipfs and go-ipfs must work closely with each other and with the Product Owner of IPFS.

**A note about Product Owners and Project Managers:** One healthy dynamic is to set up the Product Owner as the advocate for users who drives the user experience forward while the Project Manager is the advocate for the engineers who keeps an eye on capacity and roadmap.  _The Product Owner forges ahead while the Project Manager ensures that we're committing to work that's actually achievable within the given timelines._  This requires the Product Owner to spend a lot of time interacting with users and stakeholders and requires the Project Manager to have intimate knowledge of the team's capacities and commitments.  It's a dynamic that works very well, but might not fit with our organizational structure.
### Project Lead

Examples:
- js-ipfs: @diasdavid 
- go-ipfs: @whyrusleeping 

_Question: is this the same thing as a Project Captain?_

Given @flyingzumwalt's definition of Project Owner, is there a distinction between Project Lead and Product Owner?
### Project Managers

Example: @em-ly 

Project Managers serve the Project Lead and the team of contributors by 
- Gathering information from stakeholders and ensuring that it is captured well
- Grooming the Pipeline
- Keeping Milestones up to date
- Ensuring that the team stays focused on its commitments, estimated dates of delivery and deadlines.
### Program Manager

Example: @flyingzumwalt

The Program Manager maintains the Organization Roadmap by
- Ensuring that the overall set of Projects, Roadmaps, Milestones and Goals is appropriately surfaced
- Assisting Product Owners, Project Managers and Committers in creating and maintaining their Roadmaps
- Convening Quarterly Roadmap Updates and Facilitating those Conversations
### Sprint Administrator

Example: ???

@RichardLitt do you have any ideas about how to define this role? The draft PM Document currently just says: 

> The sprint administrator (normally @RichardLitt) is responsible for the sprint process every week.
> Maybe we can just link to the guide that describes the work of a sprint administrator?
### Discussion Leads

Example: _(this responsibility rotates)_
The PM Document defines Discussion Leads as:

> Each discussion has a lead, and each lead is responsible for preparing for that talk before hand. There is a sprint-issue-template available for discussion leads to add into an Etherpad for their sprint; the admin should have already filled out the Etherpad with the template, and linked to your Etherpad in the sprint issue. After the discussions, the lead should add the notes directly into the current sprint issue.

Is this accurate? 
### Sprint Master

Example: ???

The PM Document defines Sprint Master as:

> Ideally, there should be a sprint master who knows every participant's tasks and projects intimately, helps moderate work loads, checks in when a task has been taking long than expected, sets the sprint goals, and adds any urgent or incoming business to the sprint. Realistically, this is done by the discussion leads and the team as a whole. The sprint administrator was created to minimize the sprint master's admin, and to help the discussion leads.

It seems like this role could potentially be covered by the Project Lead.   Should we just re-word that a bit and add it to the responsibilities of a Project Lead?  Should we keep these responsibilities separate from Project Leads so that you can rotate the responsibilities of Sprint Master?

**Comment by flyingzumwalt** [comment]
Some comments on this in the PR:
* https://github.com/ipfs/pm/pull/131/files/0fbf77efecf51695f4c9370c540e4d6727cda80d#r74582317

**Comment by flyingzumwalt** [comment]
Any thoughts? @haadcode @jbenet @whyrusleeping @em-ly @RichardLitt @diasdavid @dignifiedquire

**Comment by jbenet** [comment]
lots of thoughts here-- will respond when i get a chace.

**Comment by RichardLitt** [comment]
I think writing these down is smart. 

### Sprint Administrator

This was removed when we overhauled the README. This is how I had it, before:

#### Sprint Administrator

The sprint administrator (normally [@RichardLitt](//github.com/RichardLitt)) is responsible for the sprint process every week.

** GitHub tasks**

- Opens a new issue for the sprint on GitHub, and posts a link to it on IRC ahead of time. To open an Etherpad, go to https://etherpad-mozilla.org.
- Opens an etherpad for each discussion and copies in the [sprint-issue-template](sprint-issue-template.md) to each etherpad, making sure that the etherpad URL matches the discussion link in the new sprint issue.
- Pings each of the discussion leads to remind them to prepare for their talks the next day, preferably by writing an agenda
- Asks people to drop their updates in the old sprint issue before the sync
- Reminds people to drop their TODOs in the new sprint issue after the discussions.

** Sync tasks**

- Begins each sprint sync with a roll-call by pinging active contributors (listed below) on IRC.
- Prompts everyone who participated in the previous sprint to update on their work. The best way to choose who goes first is to go off of a first-post-first-sync method, where all participants add their updates to the old PM issue, and the first to do so generally syncs first in the IRC channel.
- Closes up by making sure everyone who needs to has gone.

** Discussion tasks**

- Sets up the videos and moderates them, using the process outlined in [hangouts.md](hangouts.md).

---

I can clean this up, if you like. 

### Discussion Leads

> Each discussion has a lead, and each lead is responsible for preparing for that talk before hand. There is a sprint-issue-template available for discussion leads to add into an Etherpad for their sprint; the admin should have already filled out the Etherpad with the template, and linked to your Etherpad in the sprint issue. After the discussions, the lead should add the notes directly into the current sprint issue.

Yes, this is mostly accurate; however, the lead is no longer responsible for posting the notes; instead, the notetaker is, by making a PR to this repo. 

### Sprint Master

This is an artefact of what we wanted, months ago. I don't think this role has ever existed, but it would be ideal to have.

**Comment by flyingzumwalt** [comment]
We weren't able to settle on clear definitions of these. We seem to be getting by ok without them defined -- for now. We can reopen the topic if/when the definition becomes clear, or we start to feel pain from not having definitions for all of these roles.

**Comment by RichardLitt** [comment]
Sounds good to to me. Thank you.
