### ISSUE TITLE
Frame Milestones as crossover point between the timeline view (Roadmap) and the pipeline view (Status Board) of your Goals

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#166]
I propose thinking of Roadmaps and Status Boards as two views onto the same set of Goals.
- Every project has a Roadmap and a Status Board
- The Roadmap is primarily concerned with projected timeline. It arranges Goals by their Milestones, which have deadlines or estimated dates of delivery.
- The Status Board is primarily concerned with the current state of work. It arranges Goals based on their status within the pipeline.
- Milestones are the main point of navigation/connection between these two contexts.
### How this lets us Frame the Concepts

Roadmaps and Status Boards provide different views on the same set of Goals in order to answer different questions and to support distinct types of decisions:
- If you want to know the current state of work, go to the Status Board and look at the Goals there.
- If you want to know about timelines involved in the project and estimated dates of delivery, go to the Roadmap and look at the Milestones there.

Milestones are the bridge between these two contexts:
- If you want to know the current state of work for a particular Milestone in the Roadmap, go to the board and look at that Milestone's Goals on the Board.
- If you're looking at a Goal and you want to know how it fits into the overall Roadmap and timeline, find the Milestone that the Goal belongs to and see where that Milestone lies within the Roadmap.
## Definition for "Status Board"

I gave this its own ticket. See #167

Currently the document doesn't mention status boards but all of our discussions about pipelines assume that you have a place to view the project's Goals within a pipeline (ie. a Waffle Board). We should define the concept so we can use it explicitly in the model.

**Definition**: _Status Board_: A view of the project's Goals that shows their statuses within the project's pipeline.  This allows you to see the current state of work and to identify what work is ready to be picked up. 

Ie. You should be able to ask a PM "Where is this project's status board? What's the state of your project's board?" or a Project Lead can say "To see the current state of our Goals, look at the status board."

**Comment by flyingzumwalt** [comment]
Also see discussion in [these comments](https://github.com/ipfs/pm/pull/131/files/0fbf77efecf51695f4c9370c540e4d6727cda80d#r74653782)

> I think that is the purpose of Milestones -- to show that certain work is on the roadmap, and where it is on that roadmap.  By contrast, the backlog and the Icebox/Unstaged will both contain lots of stuff that's listed in Milestones.  The milestones show you the Roadmap view so you can answer questions like
* What is our trajectory? 
* What are our priorities?
* When are things likely to be done?

> Meanwhile the pipeline with Icebox, Ready, In Progress, etc. gives you the working view so you can answer questions like
* What's being worked on _now_? 
* What's ready to be worked on _now_? 
* What's been completed recently?

**Comment by flyingzumwalt** [comment]
@haadcode @dignifiedquire @whyrusleeping @diasdavid @jbenet @RichardLitt How does this sound to you? It feels to me like a helpful frame. If you agree, I'll rearrange the PM doc a bit to use it.

**Comment by RichardLitt** [comment]
> We should define [Status Board] so we can use it explicitly in the model.

This sounds good to me. 

I don't fully understand the difference between Goals and Milestones, or between Roadmap (a document?) and Status Boards. Status Boards like Waffle makes sense to me; how we were viewing Roadmaps? Above, in the comment, @diasdavid mentions "things likely to be done", "what's being worked on", "lots of stuff listed in Milestones". Are those goals? 

It might be good to have a glossary in the PM document.
