### ISSUE TITLE
Clarify the headings "Units of Work" and "Structures"

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#168]
The PM Model document defines "Units of Work" and "Structures".
### Are these the right headings? Should we just define terms without headings?

What's the purpose of this section and these headings? Do the headings convey useful meaning that helps people use this model?
### Which of these are Artifacts? Which are just concepts or organizing principles?

The Units of work (Project, Milestone, Goal) are all artifacts -- they are things that exist in the project. It's a bit fuzzier with the "Structures" (Roadmap, Backlog and Pipeline). Based on discussions and examples, it seems like we expect the Roadmap to exist as an artifact, but Backlog and Pipeline are not explicit artifacts.  They're concepts or organizing principles.  This led to confusion [in these comments](https://github.com/ipfs/pm/pull/131/files/0fbf77efecf51695f4c9370c540e4d6727cda80d#r74582220)

I'm partially asking this question because I think we should add a term -- Status Board -- which is not an artifact. It's a dynamic view of the Goals & the Pipeline.  (see #167)

It does seem like a good idea for the Roadmap to be an explicit artifact -- ie. generated Roadmap.md generated by @haadcode's [roadmap generator](https://github.com/haadcode/roadmap-generator) because we can commit the Roadmap.md in into version control with the code, which lets us get the history of diffs applied to the Roadmap over time.

**Comment by flyingzumwalt** [comment]
@haadcode do you have any advice on this? Did you have a particular intention in using the terms "Units of Work" and "Structures" when you wrote the definitions for these terms?

**Comment by haadcode** [comment]
Very quick thoughts and will get back to this with more detail. 

Board == artifact of a pipeline. the board can be displayed in many ways, but it should always be "a place" to look at, a url perhaps, so to me it sounds like an artifact.
Backlog == artifact (list of all goals). it could be presented as the Github Issues section, or it could be an .md file that lists all the goals.

Originally "Units of Work" was "TL;DR" and "Structures" was to define the concept and terminology of how we *structure* our projects in regards to project management. Not sure what would be better, so go ahead and find good ones :)
