### ISSUE TITLE
Async Retrospectives (using 2016-09-05 Calls as example)

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#170]
I've been wondering whether we can find a graceful way to have async Retrospectives on our calls & meetings.  I like that idea because retrospectives are valuable, but they tend to eat up too much time when you do them for every single meeting and force everyone to stay in synchronous mode during that retrospective.

I propose trying out this format, using this ticket as the Retrospective for this week's calls.
## Format

I like [the format described in this article](http://agileforall.com/the-real-baseline-agile-retrospective-format/) because it uses the word Fabulous and because it gives us a structure that can be done async. A sketch of how we can apply it asynchronously:
### 1: Post your individual Retrospectives & Comment

During and after the calls, anyone can post a comment to the retrospective with:
1. 🎉 What was Fabulous?
2. 🤔 What could be more Fabulous?
3. 🆕 Possible Actions or Experiments (especially ones to address 1 and 2)

Anyone can discuss those in further comments.  We should probably put a time limit on when you post your Retrospective (same day?).  Not sure if this should go _in_ the sprint issue ticket or in its own retrospective.
### 2: Identify Actions & Experiments we want to Act On

As suggestions of possible actions & experiments arise, identify which ones  **we** want to **act** on by calling them out and voting.

... maybe create a comment per-experiment/action and let people vote with 👍 and 👎. This voting doesn't have to wait for everyone to finish posting their own retrospectives.
### 3: Track the Actions & Experiments we decided to Act On

Once discussion & voting are done, we might need to gather an explicit list of the things we decided to do or try.  Alternatively, the comments with votes attached might work as a list.
## Template for your Retrospective

You can use this snippet as a template for your retrospective

```
<your-handle> retrospective:
### 🎉 What was Fabulous?

### 🤔 What could be more Fabulous?

### 🆕 Possible Actions or Experiments
```

**Comment by flyingzumwalt** [comment]
@flyingzumwalt's retrospective

## 🎉 What was Fabulous?

**:+1: Using Youtube Live **
- it works
- it saved @RichardLitt time
- it lets us post links for hangout & video on the sprint ticket  🎉 

**Short, focused, concise calls**
The calls have gotten a lot shorter without losing any of the signal! 

## 🤔 What could be more Fabulous?

**START ON TIME**
Start meetings promptly at the publicized start time. That means all the participants need to be on the call at that time, not 3, 5, or 10 minutes later.

- Starting late wastes everyone's time
- Starting late means that the youtube feed is just blank/dead
- A late-start meeting is a missed deadline. It's a small deadline, but we still missed a deadline.

## 🆕 Possible Actions or Experiments

**Try: Start Demos by stating the use case**

When you give a demo, start by saying:
- Who will use this feature or functionality we're demonstrating?
- Why are they using it - what problems does it solve?
- What is the User Experience? When & How will they use it?

**Try: Frame Sprint Discussions the Waffle Board and Milestones List** 
Pass around a link to the Milestones List and the Waffle Board and then read through the pertinent tickets from `Done`, `In Progress`, `Ready`, `Backlog`, `Inbox`, etc.  Discuss topics by their issue numbers, GH labels, milestone titles, or location within the Waffle Board rather than simply calling out a topic.

**Try: Async Retrospectives in Github Tickets**
Try out the format in the ticket you're reading right now!

**Comment by RichardLitt** [comment]
I like this idea!

> I propose trying out this format, using this ticket as the Retrospective for this week's calls.

Why don't we just record retrospective notes in each sprint issue? 

I don't think we'll need a time limit; whenever will work. People will naturally not post retrospectives for long-gone events. 

> ... maybe create a comment per-experiment/action and let people vote with 👍 and 👎. This voting doesn't have to wait for everyone to finish posting their own retrospectives.

SGTM. 

### Demos

I think that the Demos should be added to the agenda, not just "can anyone demo anything?", and that that template you suggest should be added when adding it to the agenda. Just saying "Who, why, what, how" also works. 

### Waffle Boards

We'll get there. I don't think this is happening yet, right? 

### Being on Time

+100.

**Comment by RichardLitt** [comment]
### 🎉 What was Fabulous?

We are getting really good at having people jump in and note-take!

### 🤔 What could be more Fabulous?

If the notetakers automatically were aware that part of their job is saving the Etherpad to GitHub, by making a PR in this repo with the notes in the `meeting-notes` folder. Currently, I have to remind people to do this.

### 🆕 Possible Actions or Experiments

I could vocally remind notetakers to do this during the call, or we could add a note to the template about it, or we could add it to the process document. Or all three!

**Comment by dignifiedquire** [comment]
### 🎉 What was Fabulous?

Short and sweet.

### 🤔 What could be more Fabulous?

- Paying more attention during the sync calls, yes I'm pointing the finger at myself here.
- Use a video chat that supports more than 10 participants
- Bring back a better role call

### 🆕 Possible Actions or Experiments

- Research and find a solution so we can stop using the limited Google Hangouts/Youtube stream. This is not acceptable any more give that we know we are more than 10 people who want to join the main call.
