### ISSUE TITLE
Define User, Contributor and Maintainer in PM Document

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#182]
The draft version of the PM document has two gaping holes: I doesn't define a decision making process (aka governance model) and it doesn't define a notion of Users, Contributors or Maintainers.  It's important to address these things.  Defining a governance model is going to take more time, but we should define the notions of Users, Contributors and Maintainers now, since they are the most important people in the project.

How should we define these roles?
## In general

A **Contributor** is anyone who contributes Code, Designs, Documentation, Marketing Materials or other improvements to a Project.

A **Maintainer** is someone who plays a more active role in governance, has additional decision making power, and has taken on responsibility for maintaining the health of the software. 
## Questions
- What's missing from these general definitions?
- How do Maintainers get selected or identified as Maintainers?
- What are the responsibilities associated with these roles?
- Are we using a definition of Contributor that aligns legally with our handling of Licensing? (see https://github.com/ipfs/community/issues/139)
## Reference: Apache Software Foundation (ASF) Governance

The Apache Software Foundation's model aspires to operate using a [meritocratic governance model](http://oss-watch.ac.uk/resources/meritocraticgovernancemodel). It defines roles for _User_, _Committer_ and _Project Management Committee (PMC) Member_ here: https://www.apache.org/foundation/how-it-works.html

Note: there are some criticisms of the ASF model and whether it is truly optimized to actually achieve a meritocracy.

**Comment by RichardLitt** [comment]
I would add that a contributor can be someone who contributes to a discussion, as well. A lot of great contributions never make it into the code directly with someone's name, as they may just be commenting on the GitHub issue.

We also need to define User.
