### ISSUE TITLE
(guidelines) Use "Ready" Status or "Sprint Backlog" to Show What's Ready for _this sprint_

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#188]
This came up on the js-ipfs call 09-12-2016, where we went through the issues in Milestone 2 and needed to flag some issues as "Work on it this week" or "This isn't urgent for this week. Give other things priority." 

Our PM model leans towards using the "Ready" status to signify "Work on it this week" and "Backlog" status to signify "This isn't urgent for this week. Give other things priority." 

Some orgs make a distinction between "Product Backlog" vs. "Sprint Backlog" in order to address this. Even within a Milestone, the issues that are important for the current sprint should be in the "Sprint Backlog" stage of the Pipeline. The issues that are not prioritized for the current sprint remain in the "Product Backlog".

With this second approach, you would not have a "Ready" status -- everything in the Product Backlog and the Sprint Backlog would be "Ready".

What do people think?

cc @diasdavid @whyrusleeping @haadcode @jbenet

**Comment by dignifiedquire** [comment]
I don't think "ready" is the right label. It is strongly associated with read for realease/merge for me. Alternative suggestions would be "current" or "do it"

**Comment by flyingzumwalt** [comment]
My memory was fuzzy. Looks like people don't use the term "ready" here. Instead they distinguish between "Product Backlog" and "Sprint Backlog".  In order for an issue to be in _either_ of those backlogs it must fit the team's [Definition of Ready](https://www.scruminc.com/definition-of-ready/)

**Comment by flyingzumwalt** [comment]
I updated the title and original comment. Now it proposes making a distinction between "Product Backlog" vs. "Sprint Backlog" which would mean getting rid of the "Ready" status.

**Comment by haadcode** [comment]
I think the separation was what we tried to achieve with "Backlog" vs. "Ready". Calling them "Product Backlog" and "Sprint Backlog" is a fairly common way.

I always found it easiest to call the to "Backlog" and "TODO" where "TODO" is the currently-planned-to-be-worked-on-goals.

However, I would again encourage to *NOT* use the term Sprint. We don't really do sprints (and imo shouldn't).

**Comment by dignifiedquire** [comment]
Sorry but "Product Backlog" and "Sprint Backlog" is even more confusing to me :/ I also want to point out that idea was that these are not in a new column, simply a way of highlighting tasks that are worked on in this week, without moving them away from their contextual milestone.

**Comment by haadcode** [comment]
Sigh... I've tried to say this multiple times, but I'll try again.

>  I also want to point out that idea was that these are not in a new column, simply a way of highlighting tasks that are worked on in this week, without moving them away from their contextual milestone.

If we didn't use the stages in Waffle as backlog sections, this wouldn't be a problem. Instead, you would have a view that is able to tell you the status of each goal.

> ...needed to flag some issues as "Work on it this week" or "This isn't urgent for this week. Give other things priority."

This is exactly what the status board would tell you if you'd set it up like go-ipfs and Orbit do. You lose nothing and you can still view goals per-milestone (filters).

**Comment by dignifiedquire** [comment]
@haadcode but again you are mentioning different views, i.e. two different set of filters activated. But I want something where I can see both things at the same time.

**Comment by diasdavid** [comment]
We are doing this now, can the issue be closed?

**Comment by flyingzumwalt** [comment]
Yep. Closing.

**Comment by RichardLitt** [comment]
@flyingzumwalt Should this be in the docs somewhere? Is this part of the big PM doc?

**Comment by flyingzumwalt** [comment]
Yes. It's part of the PM discussion.
