### ISSUE TITLE
Check Out OSS Trackers for the IPFS Organization

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#194]
This list is from an [article on OSS management tools](http://todogroup.org/blog/open-source-program-management-tools/) by Todo group that talks about the importance of tracking the health & traction of your OSS projects.

Some (or all) of these are aimed at letting big orgs track the health and community engagement of dozens or hundreds of OSS projects. They might not be useful for us, but they're worth looking at.
- [OSS Tracker](https://github.com/Netflix/osstracker) by Netflix
- [Gander](https://github.com/paypal/Gander) by PayPal
- [Azure on Github](http://www.jeff.wilcox.name/2015/11/azure-on-github/) by Microsoft
- [OSS Dashboard](https://github.com/amznlabs/oss-dashboard) by Amazon
- [CatWatch](https://github.com/zalando/catwatch) by Zalando
- [GrimoireLab](http://grimoirelab.github.io/) and [biterg.io](http://biterg.io/) by Bitergia

**Comment by dignifiedquire** [comment]
I just ran and tested Gander, which was a pretty big let down :( 

See attached screenshot for all it seems to do

![screen shot 2016-09-14 at 12 05 40](https://cloud.githubusercontent.com/assets/790842/18508231/a6122d62-7a73-11e6-8bd3-f84dd1fde3b3.png)

**Comment by diasdavid** [comment]
Let's continue on https://github.com/ipfs/community/issues/269
