### ISSUE TITLE
Sprint N

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/pm#20]
## Sprint Discussions

See https://github.com/ipfs/pm#sprint-discussion-schedule

## Sprint Deliverables

- Add yourself below, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

### @whyrusleeping
- [ ] merge GC https://github.com/ipfs/go-ipfs/pull/1420
- [ ] merge batching
- [x] implement go-multiplex
- [x] implement go-multiplex into go-peerstream
- [x] go through outstanding PRs
- [x] merge msgio buffering into dev0.4.0
- [ ] merge multistream select into dev0.4.0

### @krl
- [ ] ipfs-app
- [ ] webui -> ipfs-app(s):
  - [ ] connections -> ipfs app
  - [ ] DAG explorer -> ipfs app
  - [ ] node info -> ipfs app
  - [ ] logs -> ipfs app
  - [ ] config -> ipfs app

### @jbenet
- [x] review + merge a ton of outstanding PRs
- [ ] IPRS records package
- [x] finish multistream select on go-ipfs
- [x] check out cjdns code and think about embedding in app
- [ ] finish diagrams + modules.go
- [ ] neocities blog post things
- [x] propose dag DSL
- [x] propose versioning datastructs
- [x] find multiplex datarace
- [x] https://github.com/jbenet/node-screencap-stream#ipfs-cap-binary - paste screenshot to ipfs (node + osx for now)
- [x] https://github.com/jbenet/ipfs-screencap
- [x] https://github.com/jbenet/ipfs-paste - paste to ipfs

### @lgierth

- https://github.com/protocol/infrastructure/issues/58 Monitoring for gateway.ipfs.io
  - [x] https://github.com/ipfs/go-ipfs/pull/1422 ipfs daemon generates metrics
  - [x] https://github.com/protocol/infrastructure/pull/68 expose metrics to whitelisted cjdns nodes
  - [x] https://github.com/ipfs/infrastructure/pull/28 prometheus instance collects metrics and serves them
  - [ ] very simple graphana dashboard
- [x] https://github.com/ipfs/infrastructure/pull/26 publish gateway ansible scripts at ipfs/infrastructure
- [x] https://github.com/ipfs/infrastructure/pull/27 make authorized_keys an ansible step
- [ ] https://github.com/ipfs/go-ipfs/pull/1316 discover peers from cjdns

### @wking
- [ ] land https://github.com/ipfs/go-ipfs/pull/1351
- [ ] land https://github.com/ipfs/go-ipfs/pull/1407
- [ ] land https://github.com/ipfs/go-ipfs/pull/1413

### @kbala
- [ ] add prometheus to bssim and start graphing useful things
- [ ] merge bandwidth and latency additions to mocknet

### @diasdavid
- [ ] DHT Spec - https://github.com/ipfs/specs/pull/14
- [X] go & node interop (it is all about that spdy)
  - https://github.com/indutny/spdy-transport/issues/2
  - https://github.com/indutny/spdy-transport/issues/1
- [X] spdy-transport documentation https://github.com/indutny/spdy-transport/pull/5
- [x] spdy-transport spdy parser.js tests  https://github.com/indutny/spdy-transport/pull/3
- [x] get discovery with mDNS working in Mac OS X 
  - https://github.com/hashicorp/mdns/issues/41

### @chriscool
- [x] https://github.com/jbenet/ipfs-screencap/pull/5

**Comment by diasdavid** [comment]
- spdystream (go) and spdy-transport (node) now interop (mux all the streams!! :))
- wrote a bunch of tests and docs for spdy-transport
- contributed to multicast-dns(node) to get it working with the go impl (mdns)
- started working in a more complete DHT spec which eventually led me to start writing things for both the Routing Layer and Network layer entirely 
- In the node-ipfs land
  - We have mDNS Discovery working, peers are found and added to the DHT
  - DHT does DHT things, meaning k-bucketing peers added, splits, and math to find 'closest peers'
  - PR https://github.com/diasdavid/node-ipfs/pull/1
  - Working now on getting swarm implemented with multistream-select and spdy, swarm branch - https://github.com/diasdavid/node-ipfs/tree/swarm

**Comment by krl** [comment]
Ipfs apps first attempt here, will move towards using unixfs directories instead of implicit asset linking:

http://gateway.ipfs.io/ipfs/QmSoK4xKpUjR7RdtUtzHyHuy7mtimdjidrEz859QXahGyL
