### ISSUE TITLE
Sprint: Sept 26 → Oct 2

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#201]
# Sprint Sept 26

_For information about these calls and how they work, read [the ipfs/pm README](https://github.com/ipfs/pm)._

[Calendar](https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com)

Endeavour      | Lead            | Time (PDT - **UTC/Z** - CEST) | Zoom     | Stream     | Pad
:------------: | :-------------: | :---------------------------: | :------: | :--------: | :----:
All Hands Call | @lgierth        | 9:00PDT **16:00Z** 18:00CEST  | [Zoom](https://zoom.us/j/3339991818) | [Stream](https://www.youtube.com/watch?v=bJXFzJkRpBc) | [all-hands notes](https://public.etherpad-mozilla.org/p/ipfs-sept-26-all-hands)
go-ipfs        | @Kubuxu   | 10:00PDT **17:00Z** 19:00CEST | [Zoom](https://zoom.us/j/3339991818) | [Stream](https://www.youtube.com/watch?v=bJXFzJkRpBc) | [go-ipfs notes](https://public.etherpad-mozilla.org/p/ipfs-sept-26-go-ipfs)
js-ipfs        | @dignifiedquire       | 10:30PDT **17:30Z** 19:30CEST | [Zoom](https://zoom.us/j/3339991818) | [Stream](https://www.youtube.com/watch?v=bJXFzJkRpBc) | [js-ipfs notes](https://public.etherpad-mozilla.org/p/ipfs-sept-26-js-ipfs)
libp2p         | @dignifiedquire      | 11:00PDT **18:00Z** 20:00CEST | [Zoom](https://zoom.us/j/3339991818) | [Stream](https://www.youtube.com/watch?v=bJXFzJkRpBc) | [libp2p notes](https://public.etherpad-mozilla.org/p/ipfs-sept-26-libp2p)
ipld           | @nicola         | 12:00PDT **19:00Z** 21:00CEST | [Zoom](https://zoom.us/j/3339991818) | [Stream](https://www.youtube.com/watch?v=bJXFzJkRpBc) | [ipld notes](https://public.etherpad-mozilla.org/p/ipfs-sept-26-ipld)

Please add any agenda items you have to the pad before the project-specific sprint call starts.

**Comment by RichardLitt** [comment]
@nicola Added IPLD at the same time as last week; is that ok? Let me know by Saturday, if you could!

**Comment by nicola** [comment]
works!

**Comment by flyingzumwalt** [comment]
Added an agenda item: T-shirts for Hydra Connect and for future conferences

**Comment by flyingzumwalt** [comment]
Added agenda item: Proposal: Dedicate 10/3 and 10/10 community calls to Roadmap Discussions https://github.com/ipfs/pm/issues/202
