### ISSUE TITLE
Finish applying 'backlog' label to go-ipfs 'help wanted' issues 

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#204]
On today's call, we decided to add the `backlog` label to all of the tickets that are marked `help wanted` so that we can make waffle display them all in the backlog column.  -- once we're done with this move, we will move some of those items from the `backlog` to `ready`, but in the meantime, it lets us clean up the `ready` and `in progress` columns.

I did this label-juggling for all the go-ipfs repos that I have write access to, but  I don't have write access on some of the repos, so couldn't apply the label to the issues in those repos.

For each of these links below,
1. Follow the link, which gives you the list of issues in the repo that have a `help wanted` label.
2. Click the checkbox to `select all` of the issues in that list of search results
3. Add the `backlog` label

go-libp2p
https://github.com/libp2p/go-libp2p/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20label%3A%22help%20wanted%22%20

go-libp2p-peer
https://github.com/libp2p/go-libp2p-peer/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20label%3A%22help%20wanted%22%20

go-libp2p-transport
https://github.com/libp2p/go-libp2p-transport/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20label%3A%22help%20wanted%22%20

**Comment by lgierth** [comment]
Sorry, I totally failed to fulfill this simple task. Should I still apply the "backlog" label or is that covered by the "libp2p-backlog" label now?
