### ISSUE TITLE
Background Reading on Open Governance Models

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#209]
Over the coming weeks I want to talk about laying the groundwork for gradually and smoothly transition to an even more open, democratic governance model. This is something that deserves careful consideration and there's real benefit to starting the conversation early so that we have a lot of time to do the personal and organizational footwork that builds healthy patterns of communication, roles, responsibilities, accountability, etc. before they're needed.

This is related to the conversation about the Project Management Model but Governance is a distinct topic from Project Management that needs special attention.

To establish some common vocabulary and reference points, I recommend reading the sections on [Benevolent Dictators](http://producingoss.com/en/social-infrastructure.html#benevolent-dictator) and [Consensus-based Democracy](http://producingoss.com/en/consensus-democracy.html) in [Producing Open Source Software](http://producingoss.com/) (_BTW, The whole book is packed with useful advice_)

This conversation impacts everyone. It's especially important for the Project Leads to read about, consider and discuss.

cc @jbenet @haadcode @diasdavid @whyrusleeping @dignifiedquire

**Comment by flyingzumwalt** [comment]
Project Leads, please read these materials before team week. They're very short.
- [ ] @jbenet 
- [ ] @haadcode 
- [ ] @diasdavid 
- [ ] @whyrusleeping 
- [ ] @dignifiedquire

**Comment by dignifiedquire** [comment]
Got the text on my kindle, will read on the plane

**Comment by diasdavid** [comment]
I was just listening to the RFC podcast with Karl Fogel, the author of POSS, I recommend you also to listen to it:

- https://changelog.com/rfc-1/
- https://changelog.com/rfc-2/

**Comment by diasdavid** [comment]
Added these resources to - https://github.com/ipfs/pm/pull/269

**Comment by zmackie-nbc** [comment]
This issue sounds like it may be closing, but [C4](https://rfc.zeromq.org/spec:42/C4/) may have something to add to the discussion.  It's the "Collective Code Construction Contract" that ZeroMQ uses to great success.

**Comment by Zanadar** [comment]
This issue sounds like it may be closing, but [C4](https://rfc.zeromq.org/spec:42/C4/) may have something to add to the discussion.  It's the "Collective Code Construction Contract" that ZeroMQ uses to great success.

**Comment by flyingzumwalt** [comment]
We should consider this particular issue done, but it brings up the need for a knowledge base (ie Wiki) where information like this can accumulate.  It should be independent of Issues, which need to be closed at some point. We've often put "knowledge base" type info into documents within GH repositories, but that info quickly gets lost because GH wasn't designed for tracking knowledge bases in the git repositories -- search isn't optimized for it, editing flow is wrong, etc. 

At some point I'll open a separate issue for discussing that. Right now it's not a high priority -- we can make our existing habits work for a bit longer.
