### ISSUE TITLE
Call: Project Management Process

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#225]
This call will cover a handful of topics around establishing a common Project Management process.  We will also touch on the much bigger topic of choosing a Governance Model for our projects.

| Goal/Objective | Activity | Duration |
| --- | --- | --- |
| Review the [Second Draft of project management process doc](https://github.com/ipfs/pm/pull/183) | Review Document & Discuss | 15 minutes |
| Discuss Needs & Concerns for Choosing a Governance Model | Open Discussion | 20 minutes |
| Decide on Guidelines for Representing Milestones in Github, including a clear definition of "Milestone" that distinguishes Milestones from Goals | Discussion of Pros & Cons to the different approaches | 15 minutes |
| Decide how to continue applying PM Process in Waffle Boards & Sprint Calls | Retrospective on experiments with applying this | 30 minutes |
| Figure out what needs to be done to use Roadmap Generator for all Projects | Demo of Sample Roadmaps, Open Discussion | 10 minutes |

**Comment by flyingzumwalt** [comment]
Doodle poll for picking a time to conduct this call: http://doodle.com/poll/gmv8k4ukxei2xewr

Anyone is welcome to join this call. If you want to participate, please share your availability on the doodle poll and we will try to find a time that works for everyone. We definitely need to have @diasdavid @whyrusleeping, @flyingzumwalt and @haadcode on the call, so their availability will get higher priority.

**Comment by haadcode** [comment]
I can't make it next week, but don't let that hold you from having it. Can you record it so I can watch it afterwards and catch up?

**Comment by diasdavid** [comment]
@flyingzumwalt do we have the notes for this call available? Can we link them here and add them to the notes folder?

Also, I believe we can close this issue now, right?

**Comment by flyingzumwalt** [comment]
Looks like we ended up with 2 issues for this. All the notes, links, etc are in #251. We didn't use the agenda listed in this issue, but touched on most of the topics. I plan to cover the rest in small-group PM coaching calls.
