### ISSUE TITLE
Align HTTP APIs and the documentation

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/pm#227]
We are going to take js-ipfs current HTTP API definition as source of truth.

I will go through all endpoints and check that they are aligned in go-ipfs, otherwise submit issues for inconsistencies.

The apiary docs need to reflect js-ipfs http API as well, to the point that it is possible to autogenerate tests from them.

Actionable items:
- [ ] Submit issues to go-ipfs about missaligned endpoints
- [ ] Fix HTTP API related issues in go-ipfs
- [x] Fix apiary http-api docs https://github.com/ipfs/http-api-spec/issues/122
- [ ] Create automated tests from apiary docs

Planned deadline: Week 5, November 15th, 2016

**Comment by diasdavid** [comment]
Let's take this to the thread on [http-api-spec.ng - Roadmap, Priorities and Discussions of where to take the HTTP API](https://github.com/ipfs/http-api-spec/issues/116)

**Comment by Mr0grog** [comment]
@diasdavid that repo is archived, so nobody can comment there. Maybe https://github.com/ipfs/http-api-docs/issues/3 ?
