### ISSUE TITLE
IPFS Cluster Specs

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/pm#228]
Several cards grouped here for simplicity:
- [ ] IPFS Cluster rollback spec (Wk 9, Dec 12th)
- [x] IPFS Cluster API (internode) (Wk. 10, Dec 19th)
- [x] IPFS Cluster Behaviour spec (Wk. 10, Dec 19th)

Mostly concerning @whyrusleeping @hsanjuan @jbenet

**Comment by hsanjuan** [comment]
Related content:

- IPFSCluster illustrations (readme): https://github.com/ipfs/ipfs-cluster/blob/master/README.md
- Repo breakdown and some tasks: https://github.com/ipfs/ipfs-cluster/issues/2
- Meeting notes with overall descriptions https://github.com/ipfs/ipfs-cluster/issues/1
- Meeting notes where some tasks were allocated https://github.com/ipfs/ipfs-cluster/issues/4

**Comment by diasdavid** [comment]
@hsanjuan could you make this part of a ROADMAP.md on [ipfs-cluster repo](https://github.com/ipfs/ipfs-cluster)? Also, we should have at least 5 minutes on go-ipfs Monday call reserved for this.

**Comment by hsanjuan** [comment]
ok

**Comment by diasdavid** [comment]
@hsanjuan update?

**Comment by hsanjuan** [comment]
@diasdavid nope. I know this issue has to go from here and it will eventually, it's just not my main worry at the moment.

**Comment by hsanjuan** [comment]
I'm adding a roadmap file now and this is outdated from previous quarter so I'm closing.
