### ISSUE TITLE
Host our own Etherpad instance

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#230]
Each week, I create the sprint issue, and manually create Etherpads by opening links in the issue, and then copying in and editing the template for these notes manually. This takes time, and it could all hypothetically be automated. 

To automate this process so that we can do it in one click each week, removing the onus on me to do it, we should run our own Etherpad instance and allow API usage. The repo for this is here: https://github.com/ether/etherpad-lite

Ideally, of course, we would run Etherpad on IPFS. But, for now, running our own etherpad gateway might be smart. This also reduces our dependance on Mozilla's.

**Comment by flyingzumwalt** [comment]
👍

**Comment by diasdavid** [comment]
Now that we moved to hackpad, can we close this?

Having an hackpad/etherpad on IPFS sounds like a great idea and should be added to ipfs/notes

**Comment by diasdavid** [comment]
Actually it is mentioned here: https://github.com/ipfs/notes/issues/40#issuecomment-147285873 in the CRDT discussion, but it could use its own issue.

**Comment by RichardLitt** [comment]
No longer needed as we use HackMD. Closing this; I opened https://github.com/ipfs/notes/issues/190 to log potential work here in the future.
