### ISSUE TITLE
Switch of Daylight Saving Time

### ISSUE THREAD

**Issue by lgierth** [ipfs/pm#231]
CEST (Central European Summer Time) will end in 9 days (last day of October), and other DSTs will end in the next few weeks too. We'll have to adjust times of sprint all hands and hangouts again, and this time we'll finally do it planned, smoothly, and in a way that we can just replicate in ~6 months. The last times we didn't pay attention and had to adjust adhoc.

Options:
- Stick with starting at 4pm UTC.
  - Probably the easiest coordination-wise.
  - But participants will have to pay attention to their respective local end-of-DST.
- Or adjust to 5pm UTC.
  - When exactly to adjust? Different local DSTs change at different dates (I think).

**Comment by RichardLitt** [comment]
👍 to this entire issue.

I think we should stick with 4pm UTC until after all of the other DSTs have changed. We can check in in November to make sure that this time still works for everyone. Being very clear and reminding everyone that the time zone will still be UTC should be fine, I think. DSTs do change at different times - PST changes to PDT (and EST to EDT) on November 6th, while Britain will be on October 29th (I believe, looking at [this wikipedia entry](https://en.wikipedia.org/wiki/Daylight_saving_time_by_country).

We could remove entries for anything other than UTC in the template, and note that users will have to check their regional settings to make sure they are on time?

**Comment by hsanjuan** [comment]
Related: if time for meetings remains  UTC-based, we probably need to update some calendars (community etc), as I think the events there are defined in some US timezone and they will shift to the wrong time for everyone. Protip: When UTC cannot be set directly, it is good to know that Iceland/Reykjavik timezone matches UTC all year long.

**Comment by RichardLitt** [comment]
I updated the sprint events in the IPFS to be on Reykjavík time. Good thinking, @hsanjuan. I'll add a note that we use Reykjavík time in the README, I don't see it being there at the moment.

**Comment by diasdavid** [comment]
related: https://github.com/ipfs/pm/issues/121

**Comment by RichardLitt** [comment]
This can be closed now; we've all gone through the time change.
