### ISSUE TITLE
Set up labels-and-milestones for ipfs projects

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#237]
Set up [labels-and-milestones](https://github.com/haadcode/labels-and-milestones) for ipfs projects.  

Start with js-ipfs so @diasdavid can see if it addresses his needs.

@haadcode is already using this tool to sync milestones and labels across all orbit-related repositories.

**Comment by flyingzumwalt** [comment]
The documented way to use this tool is to fork the whole repo, write a yml file in the repo with your repository and milestone info in it, and then run the tool from within the repo.

You run it with commands like this:

`$ npm run lint js-ipfs.yml`
`$ npm run sync js-ipfs.yml`

I've forked the tool [here](https://github.com/flyingzumwalt/labels-and-milestones) and added a [js-ipfs.yml](https://github.com/flyingzumwalt/labels-and-milestones/blob/master/js-ipfs.yml) and a [ipfs-pm-and-community.yml](https://github.com/flyingzumwalt/labels-and-milestones/blob/master/ipfs-pm-and-community.yml)

Currently I get this error when I try to run the tool locally: 
```

> gslm-starter-project@1.0.0 sync /Users/matt/Develop/haadcode/labels-and-milestones
> npm run build && [ -f config.json ] && npm run gslm "ipfs-pm-and-community.yml"


> gslm-starter-project@1.0.0 build /Users/matt/Develop/haadcode/labels-and-milestones
> npm run clean && npm run build-json


> gslm-starter-project@1.0.0 clean /Users/matt/Develop/haadcode/labels-and-milestones
> rm -f config.json


> gslm-starter-project@1.0.0 build-json /Users/matt/Develop/haadcode/labels-and-milestones
> ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))' < config.yml > config.json


> gslm-starter-project@1.0.0 gslm /Users/matt/Develop/haadcode/labels-and-milestones
> github-sync-labels-milestones -v -c config.json -t $GITHUB_TOKEN "ipfs-pm-and-community.yml"

{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
undefined

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/5.7.0/bin/node" "/usr/local/bin/npm" "run" "gslm" "ipfs-pm-and-community.yml"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! gslm-starter-project@1.0.0 gslm: `github-sync-labels-milestones -v -c config.json -t $GITHUB_TOKEN "ipfs-pm-and-community.yml"`
npm ERR! Exit status 1
```

**Comment by flyingzumwalt** [comment]
If we decide to adopt the tool, we should pull the code into a repo within the ipfs org so everyone can add/edit YAML files for their projects and run them. We should even be able to make the tool run automatically on CI whenever someone pushes changes to their YAML file.

I might have to set this aside until next week. Priority is to get all the roadmaps into Github. @diasdavid has already done the hard work of manually creating his roadmaps. Getting them set up to auto-generate with the roadmap-generator and getting them to display nicely in waffle boards is a high priority, but doesn't need to be done by tomorrow.

**Comment by flyingzumwalt** [comment]
@diasdavid we finally have labels-and-milestones working! Please review the list of repos, milestones and labels in this config file to confirm that they are right before I sync them across all your repositories: https://github.com/flyingzumwalt/labels-and-milestones/blob/master/js-ipfs.json

Eventually these files will probably live in ipfs/pm somewhere, but for today just submit a PR against my fork if you want to make changes.

**Comment by diasdavid** [comment]
@flyingzumwalt the complete list can be found here: https://waffle.io/ipfs/js-ipfs/settings/sources
@RichardLitt has also updated his script that will enable the labels to be applied in all the repos https://github.com/ipfs/community/commit/238477df3c63567451cd95d2ef21a0e750adf959

excited that this is coming together :) 

For easy easing, can we have like 2 or 3 random chars per Milestone, such that:

```
a3c- Async Crypto
hd8- Bitswap Complete
```

So that it is easier to parse through (rather than making our brains read through the whole thing)

Even better would be to use the quarter and a letter, such as:

```
q4a- Async Crypto
q4b- Bitswap Complete
```

**Comment by diasdavid** [comment]
@flyingzumwalt saw that you added the milestones https://github.com/ipfs/js-ipfs/milestones \o/ thank you!

Do note though, that they were not all tagged correctly:

![image](https://cloud.githubusercontent.com/assets/1211152/20235662/f5d52756-a88f-11e6-8051-a6d51e091683.png)

![image](https://cloud.githubusercontent.com/assets/1211152/20235664/f91c5c36-a88f-11e6-94d4-b927b0f14c33.png)


^^ These were Q3: https://github.com/ipfs/js-ipfs/blob/master/ROADMAP.md#2016-q3

**Comment by flyingzumwalt** [comment]
Fixing it would take about an hour. Can we live with it?

**Comment by diasdavid** [comment]
just closing these 2 would be enough :)

**Comment by flyingzumwalt** [comment]
I think I know how to do that! Let me try.

**Comment by flyingzumwalt** [comment]
Ok. I synced the milestones across these repos:
```
"ipfs/js-ipfs",
"ipfs/js-ipfs-api",
"ipfs/js-ipfs-block-service",
"ipfs/js-ipfs-repo",
"ipfs/js-ipfs-block",
"ipfs/js-ipfs-merkle-dag",
"ipfs/js-ipfs-unixfs",
"ipfs/js-ipfs-unixfs-engine",
"ipfs/js-ipfs-bitswap",
"ipfs/js-ipfsd-ctl"
```
and closed the two Q3 milestones.

I wasn't sure if you want these milestones added to all the multiformats and libp2p repositories. We can create separeate config files for those projects' milestones if you want.

Note: I still don't have write permissions on https://github.com/ipfs/js-ipfs-examples, so the milestones aren't syncing to that one.

**Comment by diasdavid** [comment]
> I wasn't sure if you want these milestones added to all the multiformats and libp2p repositories. We can create separeate config files for those projects' milestones if you want.

We do need the milestones to be across the repos that waffle is tracking for the `Project: js-ipfs`

**Comment by flyingzumwalt** [comment]
Added these to the config file:
```
      "dignifiedquire/aegir",
      "ipfs/js-libp2p-ipfs",
      "ipfs/js-libp2p-ipfs-browser",
      "ipld/js-ipld-dag-cbor",
      "ipld/js-ipld-resolver",
      "multiformats/js-multiaddr",
      "multiformats/js-multibase",
      "multiformats/js-multicodec",
      "multiformats/js-multihash",
      "multiformats/js-multihashing",
      "multiformats/js-multihashing-async",
      "multiformats/js-multistream-select",
      "multiformats/multistream-select"
```
bu I don't have write access to most of those repos. @dignifiedquire can you help with that?

**Comment by diasdavid** [comment]
@flyingzumwalt added you to all with exception of `aegir`, which @dignifiedquire owns

**Comment by flyingzumwalt** [comment]
I still don't have admin access to any of the multiformats repos.

**Comment by RichardLitt** [comment]
You should now.

**Comment by flyingzumwalt** [comment]
It’s still not letting me add milestones to any of the multiformats repos.

**Comment by dignifiedquire** [comment]
@flyingzumwalt invited you to aegir
