### ISSUE TITLE
Sprint R - July 27

### ISSUE THREAD

**Issue by jbenet** [ipfs/pm#24]
## Sprint Discussions

See https://github.com/ipfs/pm#sprint-discussion-schedule

## Sprint Deliverables

- Add yourself below, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

### @jbenet
- [ ] CR all the things
- [x] 0.3.6 release https://github.com/ipfs/go-ipfs/milestones/IPFS 0.3.6
  - [x] CR all the 0.3.6 things
  - [x] fix refs -u -r https://github.com/ipfs/go-ipfs/pull/1527
  - [x] fix gobuilder dist https://github.com/ipfs/go-ipfs/pull/1526
  - [x] fix CORS https://github.com/ipfs/go-ipfs/pull/1529
  - [x] remove "Publishing!" println https://github.com/ipfs/go-ipfs/pull/1535
  - [x] goprocess bugfix https://github.com/jbenet/goprocess/pull/12 + 13
  - [x] ipfs add -r -w and FUSE fixes https://github.com/ipfs/go-ipfs/pull/1536
- [x] fix pinbot things https://github.com/whyrusleeping/pinbot/pull/5
- Planning
  - [ ] plan for containers
  - [ ] plan for installing
  - [ ] plan for starlog
- Cube things
  - [ ] designer contact
  - [ ] feedback on docs/gist
- [ ] finish vinyl PR in node-ipfs-api https://github.com/ipfs/node-ipfs-api/pull/35
- [ ] SEA -> BER team travel things
- Discussions
  - [x] tokens / capabilities discussion https://github.com/ipfs/go-ipfs/issues/1532
  - [x] ipget spec https://github.com/ipfs/notes/issues/27

### @whyrusleeping
- [x] rabin fingerprinting chunker
- [x] ipfs mfs api v0.1 (at least to PR)
- [x] dropbox app (mfs frontend) functional
- [x] fix in browser node-ipfs-api add call
- [x] fix vinyl's file buffer check (https://github.com/wearefractal/vinyl/pull/58)
- [x] work on removing dependencies from ipfs-shell (shouldnt have to import all of ipfs)
 

### @diasdavid || @daviddias

- 

### @krl

- [ ] publish modularized webui
- [ ] append only finger tree demo

### @lgierth

- [x] repo config managed by ansible https://github.com/ipfs/infrastructure/pull/53
- [x] rebuild more gateway hosts https://github.com/ipfs/infrastructure/pull/54
- [x] move metrics.i.ipfs.io to dedicated droplet https://github.com/ipfs/infrastructure/pull/55
- [ ] blocklist
- [ ] discover peers from cjdns https://github.com/ipfs/go-ipfs/pull/1316
- [ ] write down test net thoughts

### @rht
- [ ] fix pending PR's
- [ ] throttle bandwidth https://github.com/ipfs/go-ipfs/issues/1482

**Comment by diasdavid** [comment]
## SPRINT UPDATE

- We've run successfully an interoperability test between go-ipfs and node-ipfs, using the PING protocol. It works™
- Friedel is now helping node-ipfs land (woot! \o/), starting by adding tests. 
- network-layer
  - [x] ton of discussions on defining how we are going to modularize (already following what was defined) the libp2p (see images below for future reference)
  - Peer routing
    - [x] standardise the interface for router components
    - [~] make kad-router. kbucket update/split works (with tests), dht registers on swarm, need to finish the peer `query loop`
￼  - swarm
    - [x] add ability to open just connection (without a stream) (today!)
    - [x] add lastSeen https://github.com/diasdavid/node-ipfs-swarm/pull/6
    - [x] merged https://github.com/diasdavid/node-spdy-stream-muxer/pull/3
    - [x] merged https://github.com/diasdavid/node-ipfs-swarm/pull/5
- node-ipfs-api 
  - [x] fix browserify transform problem https://github.com/ipfs/node-ipfs-api/pull/38


Discussion boards for `libp2p` components:

![image](https://cloud.githubusercontent.com/assets/1211152/9043373/4e0f1d40-3a15-11e5-8de1-8c3555aef4c4.png)
![image](https://cloud.githubusercontent.com/assets/1211152/9043381/51728a44-3a15-11e5-8e86-a69d71d2d20a.png)

**Comment by lgierth** [comment]
- ipfs repo config on the gateways is now managed by ansible. in the past we lost the private key of pluto, which won't happen again.
- neptune has been rebuilt
- the nginx-related ansible code got a good refactoring (CR needed)
- pinbot and metrics have been moved to a new host called scruffy (CR needed). that means we now have infrastructure stuff separate from gateway/bootstrap nodes
- did a bit more work on cjdns-discovery, but that's still WIP
- checked out other cjdns integration points with daviddias
- got the dmca blocklist daemon to work today
- battlemesh preparations and travels
- didn't get to writing down testnet stuff

**Comment by whyrusleeping** [comment]
This last week I worked on getting the ipfs http commands lib refactored and fixed up. We now have better reliability provided by the commands as they are now able to return errors after beginning a stream of data via http trailers.
I implemented a --create option for ipfs patch, along with a moderate refactor of the involved code.
Windows builds work again, although NAT traversal is iffy on the platform.
we shipped 0.3.6! and it was awesome, but the webui was broken, so we fixed that and shipped 0.3.7.
Since then, I implemented rabin fingerprinting chunking which I still need to address CR on.
I also started working on implementing the mfs API to allow for a whole bunch of cool new apps to be built, including a dropbox-like app i'm writing in javascript.
I learned a lot about javascript and I'm kinda getting the hang of how things work.

**Comment by jbenet** [comment]
This week was very productive in terms of 0.3.6. Other thing so so.
- [x] 0.3.6 release https://github.com/ipfs/go-ipfs/milestones/IPFS 0.3.6
  - [x] CR all the 0.3.6 things
  - [x] fix refs -u -r https://github.com/ipfs/go-ipfs/pull/1527
  - [x] fix gobuilder dist https://github.com/ipfs/go-ipfs/pull/1526
  - [x] fix CORS https://github.com/ipfs/go-ipfs/pull/1529
  - [x] remove "Publishing!" println https://github.com/ipfs/go-ipfs/pull/1535
  - [x] goprocess bugfix https://github.com/jbenet/goprocess/pull/12 + 13
  - [x] ipfs add -r -w and FUSE fixes https://github.com/ipfs/go-ipfs/pull/1536
- [x] fix pinbot things + redeploy https://github.com/whyrusleeping/pinbot/pull/5
- [x] 0.3.7 release 
  - [x] release: https://github.com/ipfs/go-ipfs/commit/ec51450d071e50464c03a84ef1c3fe3ca902d0e1
  - [x] fix referer + origin bug with webui https://github.com/ipfs/go-ipfs/pull/1544
- Planning
  - [-] plan for containers (starship, got somewhere, but not far enough)
  - [ ] plan for starlog --- (didnt get to this)
  - [-] plan for installing (with @diasdavid)
  - [x] plans for electron app improvements (with @diasdavid)
- [ ] finish vinyl PR in node-ipfs-api https://github.com/ipfs/node-ipfs-api/pull/35 --- (didnt get to this)
- Discussions
  - [x] tokens / capabilities discussion https://github.com/ipfs/go-ipfs/issues/1532
  - [x] ipget spec https://github.com/ipfs/notes/issues/27
- [x] SEA -> BER -> MDX team travel (lots of) things
 oh and i got a next iteration of ipfsld done. need to figure out what the node api will be exactly, and need to
figure out marshaling details (reflect stuff, validation, link types)

**Comment by jbenet** [comment]
@krl @heems @rht want to post sprint update here? thanks

**Comment by chriscool** [comment]
@jbenet I have been working on https://github.com/chriscool/sharnessify during my vacation. Please take a look and tell me what you think about it. Thanks!

**Comment by jbenet** [comment]
@chriscool nice! will take a look and run through adding it to a repo
