### ISSUE TITLE
Calls to review PM Model and Ratify PM Model

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#244]
The PM Roadmap aims to 
1. **Ratify** a PM model by 11 November [Milestone 1](https://github.com/ipfs/pm/milestone/1)
2. **Implement** that model across all projects by 16 December - [Milestone 4](https://github.com/ipfs/pm/milestone/4)

Let's schedule a call to discuss/refine the model and then a call to ratify the final draft.

Proposed Call Times: 

_Make sure to read the [Second Draft of project management process doc](https://github.com/ipfs/pm/pull/183) and add comments before these calls._

Date | Time | Topic
-----|------|-------
Tuesday 8 Nov | 16:00 UTC | **Discuss the PM Process** (see [agenda item from team week](https://github.com/protocol/team-week-2016-Q4/issues/37)) and identify what needs to be changed/updated in the PM Document
Tuesday 15 Nov | 16:00 UTC | **Ratify the PM Process Document**

@haadcode @diasdavid @whyrusleeping @em-ly

**Comment by em-ly** [comment]
15:00 UTC on Tuesday and Thursday works for me!

**Comment by haadcode** [comment]
I can do Tuesday but not Thursday.

Do we need two calls? Is there something we can do async? I'm all for pushing forwards with this but I'm hesitant to schedule more calls.

**Comment by flyingzumwalt** [comment]
The first will is basically be the PM Process discussion that was supposed to happen at Team Week. That will certainly kick up edits that need to happen in the PM Document. Once I've applied those edits, we will almost certainly need to have another discussion to make sure we're all on the right page in order to actually ratify it.

Now that I think of it, I won't be able to turn around the edits that quickly. Let's shoot for 2 Tuesdays in a row, with the goal of ratifying the PM Process on the call on Tuesday 15 November.  Updating the original comment to reflect this...

**Comment by flyingzumwalt** [comment]
Apologies. I forgot about Daylight Savings. @whyrusleeping is not available until 8am PST, which is now 16:00Z, not 15:00Z. I'm going to send out an iCal invite for Tuesday 16:00Z. Is that time a no-go for any project leads? @whyrusleeping @diasdavid @haadcode @em-ly

**Comment by flyingzumwalt** [comment]
Falling back to relying on Doodle. Please vote: 
http://doodle.com/poll/659qpabx6vce3kfp

**Comment by diasdavid** [comment]
Call happened, now next step is: https://github.com/ipfs/pm/issues/251

**Comment by flyingzumwalt** [comment]
NOTE: We still haven't formally ratified the PM Process Document, but we might not need a call to do this. If we merge a PR with the document in it, that probably qualifies as "ratifying" the document.
