### ISSUE TITLE
Sprint: Nov 7 -> Nov 13

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#246]
# Sprint November 7th

_For information about these calls and how they work, read [the ipfs/pm README](https://github.com/ipfs/pm)._

[Calendar](https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com)

Zoom and Stream links will be updated directly before the calls. Links to them will also be dropped in IRC, at the start of each call. If the link below seems to link to this issue, the link has not been updated yet.

**[Zoom link](https://zoom.us/j/213894386)**
**[Stream link](https://www.youtube.com/watch?v=jnpmCXuQ1WA)**

Endeavour      | Lead            | Time (PST - **UTC/Z** - CET) | Pad
:------------: | :-------------: | :-------------------------: | :----: 
All Hands Call | @flyingzumwalt  | 9:00PST **17:00Z** 18:00CET  | [notes](https://public.etherpad-mozilla.org/p/ipfs-nov-7-all-hands)
go-ipfs        | @whyrusleeping  | 10:00PST **18:00Z** 19:00CET | [notes](https://public.etherpad-mozilla.org/p/ipfs-nov-7-go-ipfs)
apps on IPFS   | @haadcode       | 10:30PST **18:30Z** 19:30CET | [notes](https://public.etherpad-mozilla.org/p/ipfs-nov-7-apps-on-ipfs)
js-ipfs        | @diasdavid      | 11:00PST **19:00Z** 20:00CET | [notes](https://public.etherpad-mozilla.org/p/ipfs-nov-7-js-ipfs)
libp2p         | @diasdavid      | 11:30PST **19:30Z** 20:30CET | [notes](https://public.etherpad-mozilla.org/p/ipfs-nov-7-libp2p)
Please add any agenda items you have to the pad before the project-specific sprint call starts.

**Comment by RichardLitt** [comment]
Note! 
- The times have changed due to daylight savings. Be sure the times work for you. If they don't, post here!
- Apps on IPFS is now also a call. @nicola Should this replace IPLD? You don't need one of those right now, right? @haadcode that time work for you? It's as early as I could make it. 
- I won't be here this next Monday. But the calls should, of course, go on. :)

**Comment by nicola** [comment]
Are we making IPLD on Monday or on Friday?

**Comment by flyingzumwalt** [comment]
@nicola it's your call. Last week people seemed to strongly favor removing IPLD from the Monday lineup so we don't have a meeting that starts at 20:00Z

**Comment by nicola** [comment]
Same with me, let's try to set it up then for this coming Friday

**Comment by dignifiedquire** [comment]
@nicola removed it from the issue

**Comment by diasdavid** [comment]
@nicola sounds good to me :)

**Comment by diasdavid** [comment]
# dag API

This really needs some love -> https://github.com/ipfs/interface-ipfs-core/issues/81

**Comment by diasdavid** [comment]
# floodsub API

@gavinmcdermott is taking the lead of stubbing this API and integrating it in js-ipfs and js-ipfs-api

Relevant issues with notes:
- https://github.com/ipfs/js-ipfs/issues/530
- https://github.com/ipfs/js-ipfs/pull/531
- https://github.com/ipfs/js-ipfs-api/pull/377

**Comment by diasdavid** [comment]
# metamask libp2p testnet

- [ ] notify @kumavis when all Async Crypto is merged and ready for him to try out (hopefully no later then wednesday)

**Comment by diasdavid** [comment]
I've added the action items/notes (above ^^^ ) that are not captured directly by milestones our waffle so that we don't drop them :)

**Comment by diasdavid** [comment]
I won't be able to commit being available for next sprint call, as I'll be participating on TADSummit. 

@dignifiedquire @VictorBjelkholm can you take over me for js-ipfs? I'll give my review on the waffle board and leave notes on the etherpad

@whyrusleeping @lgierth @Kubuxu can you take over me for libp2p? I'll also give my review on the waffle board and leave notes on the etherpad

**Comment by RichardLitt** [comment]
@diasdavid Updated in #248 with that information, thanks. Have fun!

**Comment by nicola** [comment]
### IPLD fridays poll

@flyingzumwalt, @dignifiedquire, @jbenet, @diasdavid please fill this: http://doodle.com/poll/xipx3d7q56shufmc

**Comment by diasdavid** [comment]
@nicola why no 6pm UTC?

**Comment by nicola** [comment]
@diasdavid just added, but might not work for me :/

**Comment by diasdavid** [comment]
@nicola I believe you added 3pm UTC

**Comment by nicola** [comment]
hey @daviddias, @dignifiedquire, @victorbjelkholm I have failed to notify you with doodle.com about today’s IPLD meeting, according to the poll should be now. I thought I have done it through the app, but it did not show up on the calendar.

Let me know if you are in.

**Comment by RichardLitt** [comment]
@nicola closing this. Hope that that was resolved.
