### ISSUE TITLE
Sprint: Nov 14 > Nov 20

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#248]
# November 14 Sprint

_For information about these calls and how they work, read [the ipfs/pm README](https://github.com/ipfs/pm)._

[Calendar](https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com)

Zoom and Stream links will be updated directly before the calls. Links to them will also be dropped in IRC, at the start of each call. If the link below seems to link to this issue, the link has not been updated yet.

**[Zoom link](https://zoom.us/j/3339991818)**
Stream link: There will be **no stream** today, due to lack of manpower. Please join and turn off your camera and mike if you would like to see but not participate.

Endeavour      | Lead            | Time (PST - **UTC/Z** - CET) | Pad
:------------: | :-------------: | :-------------------------: | :----:
All Hands Call | @lgierth, notes @sidharder | 9:00PST **17:00Z** 18:00CET  | [notes](https://hackmd.io/MwVgDAjAnATAxgQwLRgGYKkgLFApgDiSgCMIIlhVcQ4xdipg8g==)
go-ipfs        | @whyrusleeping  | **CANCELLED** | [notes](https://hackmd.io/EwYwrAZgnFAmAsBaAbMgHE+9kFNEENkRhEIxgBGAdggQmAGYAGIA)
apps on IPFS   | @haadcode       | 10:30PST **18:30Z** 19:30CET | [notes](https://hackmd.io/OwNgjAxghgnMEFoIAYoBMEBZMDMBMCAHAEYQDMCwaOwMayOZhmyQA===)
js-ipfs        | @VictorBjelkholm | 11:00PST **19:00Z** 20:00CET | [notes](https://hackmd.io/AwJgJgRgHA7CwFoQwIYDYEBZwZcAjAKYL5QBmMmwKAnAKx001A==)
libp2p         | @whyrusleeping  | **CANCELLED** | [notes](https://hackmd.io/OwIwbALArAhgzCAtGADFFiIxDRBOEAUwBN8BGMAJjIgDMVgYsg==)

**Friday, the 18th**:

| **Endeavour**   | **Lead** | **Time UTC** | **Pad** |
|-----|---------|---|---------|
| IPLD |  @nicola  | 17:00  | [Notes](https://hackmd.io/IYFmBMFYE5QWmgIwMYHY4gMwDZN2AAwBMAHHASZtMiOMcjUA) |

Please add any agenda items you have to the pad before the project-specific sprint call starts.

Note that I have removed IPLD (@nicola), as that will happen on Friday from now on, I believe. Let me know if this isn't the case. Also, @diasdavid will be absent from this sprint, so I have given js-ipfs and libp2p over to @dignifiedquire and @whyrusleeping, if they can take those on.

**Comment by RichardLitt** [comment]
This week, it would be a good idea to try out HackMD and see how we like it. It allows us to see a live version of the Markdown. I've adjusted the links above. See https://github.com/ipfs/community/issues/196 for more information.

**Comment by nicola** [comment]
Hey @RichardLitt, from a previous Doodle we confirmed that IPLD should happen at 12pm EST (5pm UTC)

Can we add in this weekly calendar a new table like this:

| **Endeavour**   | **Lead** | **Time (PST - UTC/Z - CET)** | **Pad** |
|-----|---------|---|---------|
| IPLS |  @nicola  | 12pm EST  | x |

**Comment by RichardLitt** [comment]
Ok; that's on November 18th, correct?

**Comment by nicola** [comment]
@RichardLitt correct!

**Comment by RichardLitt** [comment]
Added. :)

**Comment by diasdavid** [comment]
@RichardLitt could you also update the weekly calendar?

**Comment by RichardLitt** [comment]
Done!

**Comment by diasdavid** [comment]
thank you @RichardLitt 

another thing, @dignifiedquire won't be able to join the calls tonight. @VictorBjelkholm would you be good to lead js-ipfs call?

**Comment by VictorBjelkholm** [comment]
Sure thing!

**Comment by RichardLitt** [comment]
Updated all links to notes to use HackMD following good vibes from the All Hands call.

**Comment by flyingzumwalt** [comment]
**CANCELLED go-ipfs** call due to Technical Difficulties and lack of agenda items. Apologies for the last minute change.

**CANCELLED libp2p** due to lack of quorum (no @diasdavid or @whyrusleeping) @diasdavid set up some items [on the agenda](https://hackmd.io/AwJgJgRgHA7CwFoQwIYDYEBZwZcAjAKYL5QBmMmwKAnAKx001A==) but only @kumavis was around to discuss. 

@diasdavid Remember to revive those agenda items next week.

**Comment by diasdavid** [comment]
@VictorBjelkholm thank you for hosting the call and @em-ly thank you for note taking! Are the notes all up? Can I get the video recording just to catch up on the items of the agenda?

@flyingzumwalt for reference: https://github.com/ipfs/pm/issues/246#issuecomment-259551164

**Comment by VictorBjelkholm** [comment]
@diasdavid you can find the notes here: https://github.com/ipfs/pm/blob/d0fa64bce0598d768f0b17b15092865537208789/meeting-notes/2016-11-14-js-ipfs.md

In short, just walked through the items on the list, announcing the async crypto stuff is merged but I haven't personally verified it's working in the browser yet. Also talking about the mission to add more examples and documentation in preparation of dappshack event.

**Comment by RichardLitt** [comment]
The video for the All Hands Call can be found here: https://www.youtube.com/watch?v=njwL_Xrmu5M

**Comment by diasdavid** [comment]
@RichardLitt do you have the one for js-ipfs?

**Comment by RichardLitt** [comment]
I do not, unfortunately. I have one for Apps on IPFS from @Kubuxu, however.

**Comment by RichardLitt** [comment]
Which is here: https://youtu.be/Q0ao_OANKu0

**Comment by flyingzumwalt** [comment]
I handed off the videos of all-hands and js-ipfs to @VictorBjelkholm for uploading to youtube (I don't have access to the IPFS youtube account). Let me know if you need me to hand them off again.

**Comment by VictorBjelkholm** [comment]
@flyingzumwalt Oh, did not realize that, I only pinned the hashes you sent me! I have no idea how the process for us to upload to Youtube (nor the access) works, probably better if someone else does it. Sorry for any miscommunication on my side.

**Comment by RichardLitt** [comment]
Can you find those hashes and give them to me? I can upload them.

**Comment by VictorBjelkholm** [comment]
@RichardLitt yes, should have put them directly...

all-hands: QmQ5W1Su6Hq4qfXsctRH8rp8c8qD61wU35j8WCizcmfHCs

js-ipfs: QmNskaAZUqweAnDc4nv8SAQQzzNsr11j62tQeohXj3dJk3

**Comment by RichardLitt** [comment]
Thanks, @VictorBjelkholm. After processing, the video for js-ipfs will be available here: https://youtu.be/kMw4Z3YpqPU

**Comment by RichardLitt** [comment]
This is to note that the IPLD call is happening today at 1700 UTC. Please add your agenda items accordingly.

**Comment by VictorBjelkholm** [comment]
@RichardLitt IPLD call recording is here: QmbBqxsNPEMJhXxVUBvXLWG1GgJt7ukKjH5AxQbTEpVMas

Could you please upload it to youtube as well?

**Comment by RichardLitt** [comment]
Sure. https://youtu.be/3zTip_GfN-Y. 

And I think that is it for this sprint! See you all next week.
