### ISSUE TITLE
Sprint S - August 3

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/pm#25]
## Sprint Discussions

See https://github.com/ipfs/pm#sprint-discussion-schedule

## Sprint Deliverables

- Add yourself below, that way we only have people listed who are really in the sprint
- Add links to issues down here. Only add things you can finish this sprint.

**Comment by whyrusleeping** [comment]
This week I worked on a rabin fingerprint chunker for add, got it merged in and made jbenet happy
I have the first revision of the mfs API up for PR, and i've built a neat little app on top of it.
In building that app i patched the vinyl packages buffer check, and our handling of that in node-ipfs-api.
ipfs-shell is also now completely independent of the go-ipfs codebase, you no longer have to import that monster as a dependency.
I have an open PR for improving the node builder and the node construction process in general, once i'm done it should make it easier to create more specialized nodes for various purposes

**Comment by diasdavid** [comment]
Added the starting date to the title, it helps looking at the sprint history and map it to the real calendar. Hope it is ok for everyone

**Comment by jbenet** [comment]
@diasdavid :+1: 

Let's do checkin + discussions tonight at the usual monday time(s).

**Comment by lgierth** [comment]
- such an unproductive week, battlemesh was still great and awesome, but sooo unproductive
- gateway-dmca-denylist is taking shape, sorry for keeping you in limbo @whyrusleeping
- discovery-cjdns not yet finished, but a little progress
- we didn't look into libp2p + cjdns during battlemesh
- landed nginx-related ansible refactorings
- landed ansible fixes for bootstrapping hosts

**Comment by diasdavid** [comment]
### SPRINT UPDATE

Battlemesh was really fun, but also very time consuming, traveling lack of reliable Internet connectivity made it really hard to stay productive. Here is the things I managed to get done/be focused on:
	- Planned with @jbenet all the things we need to have for CCC.
	- On libp2p, I finished the implementation of kad-router and make some tests to verify it’s functionality (it works™). I still feel the need to stress it a bit more (DHT Hell tests) and make sure it behaves as expected in all conditions.
	- Started working on electron-app, did a great restructured the codebase, fixed a bunch of bugs / misunderstandings of how electron operates and finally implemented drag-and-drop. drag-and-drop is there (it works™), but needs a UI polish. I’m not very good with CSS and the lack of internet connectivity for the last days didn’t help me find nice guides/examples. Nevertheless it does show a loading bar while its uploading and the name + hash when it is uploaded, also, the “gateway.ipfs.io/ipfs/“+hash gets automatically added to the clipboard.
		- https://github.com/ipfs/electron-app/pull/27/files
		- https://github.com/ipfs/electron-app/pull/30
 	- Wrote the script to download and build all of the electron-app releases for the ipfs/distributions repo for the soon /install.html page. 
		- https://github.com/ipfs/distributions/pull/5

**Comment by heems** [comment]
* added upload data and graphing to bssim
* fixed some performance issues in bssim
* started work on peers being choosey about who the download from and upload to, it works using ledger data and latency information at the moment

**Comment by jbenet** [comment]
battlemesh + travel without internet is frustrating.

- [x] fixed the go-ipfs npm package versioning https://github.com/ipfs/npm-go-ipfs
- [x] CCC planning (distributions, electron-app fixes)
- [x] made ipfs/distributions with @daviddias https://github.com/ipfs/distributions
  - [x] make scaffolding
  - [x] download all go-ipfs binaries from gobuilder
  - [ ] design nice html pages
  - [ ] generate html pages
- [x] node-subcomandante to fix ipfsd-ctl zombies. (still needs to be merged into node-ipfs-api)
- [~] node-vinyl-multipart stream -- still doesnt work
- [x] Battlemesh time consumingness.
  - [x] gave talk at battlemesh
- [x] go-simple-encrypt for simple secrets https://github.com/jbenet/go-simple-encrypt
- [x] improved go-ipld https://github.com/ipfs/go-ipfsld -- working on multicodec now.
  - [ ] go-multicodec began implementation but not done yet. basic multistream + encoders

**Comment by krl** [comment]
had a terrible week of hardware failure, that i still have not been able to get around (have to use my screenless old x61 with external monitor atm) have however made progress on webcomponents and starlog concept.

The webcomponent feed-view can now display an infinite-scroll list of a feed. ( here /ipfs/QmXUzXsqFgKfS5MBXzn2pfaAbxWQzirKSvFM45ywEMWeD8/app/ )

What's left is appending, publishing to ipns, and muxing multiple feeds together for a timeline view. and then we have a webcomponent-powered twitter-clone on ipfs.

I think i'll still have time to get something installable until camp, i've gotten over the most hurdles. and my new computer should arrive tomorrow.

**Comment by whyrusleeping** [comment]
dont know why this was closed, I just made this issue yesterday...
