### ISSUE TITLE
Find out if Community Wants a weekly "Apps on IPFS" Call

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#253]
We have added an "Apps on IPFS" slot to the weekly calls.  This is primarily for orbit. We want to figure out whether the community wants this call to cover more than just orbit (and people using orbit-db).

Action Items
- [x] Reach out on ipfs/community
- [ ] Ask on Discourse Trial
- [x] Ask on IRC
- [x] Reach out to people whose work is on awesome-ipfs ???
- [x] Reach out on ipfs/apps

**Comment by flyingzumwalt** [comment]
@RichardLitt can you help with this?

**Comment by VictorBjelkholm** [comment]
I would certainly want to see more than just Orbit in a general call for apps on IPFS. I think we do need to be better at reaching out to people we see using IPFS and make the case for them to appear in the call and talk about their projects though.

**Comment by haadcode** [comment]
I would also like to see more than just orbit :) Perhaps we can reach on on ipfs/apps too to encourage people to come and share what they're working on?

**Comment by flyingzumwalt** [comment]
I didn't even know ipfs/apps existed. 😊

**Comment by VictorBjelkholm** [comment]
We also have Twitter and Reddit where we can ask for people

**Comment by RichardLitt** [comment]
- [ ] Reached out on Reddit https://www.reddit.com/r/ipfs/comments/5doa3k/asking_for_participation_in_the_weekly_apps_on/
