### ISSUE TITLE
[Generating Roadmaps] Evaluating the labels-and-milestones approach  

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#257]
## The Need
We want a graceful way to 
* Construct Roadmaps that list Milestones with Estimated Dates of Delivery and associated Github Issues
* Commit Quarterly Roadmaps in a way that lets us evaluate at the end of the Quarter
* Track the progress of Milestones as time passes
* easily refer back-and-forth between waffle boards (or equivalent) and Roadmaps

If our projects only spanned one repository or if Github Milestones were multi-repo, we would use Github Milestones to represent our milestones and generate our roadmaps using haadcode/roadmap-generator.

## The Complicating Factors
1. Projects like js-ipfs and go-ipfs span many repositories. 
2. Github milestones are single-repository -- they can only contain issues from one repository
3. If we could make multi-repo Milestones we would use those to track our work and generate ROADMAP.md files from the Milestones

## The Solution we're Testing

1. Sync Milestones across a project's repositories using haadcode/labels-as-milestones
2. Use haadcode/roadmap-generator to generate Roadmap.md files from those milestones (matching by milestone title)
3. Commit those ROADMAP.md files 

(bonus) We can tweak the roadmap generator to include links into the waffle board that let you view the board filtered per-milestone. For example: [All Issues related to the go-ipfs 0.4.5 milestone](https://waffle.io/ipfs/go-ipfs?milestone=Dont%20Kill%20Routers,ipfs%200.4.5)

(bonus) We could use the same config files to generate Captain's Logs like https://github.com/ipld/specs/issues/13, which was the intention of https://github.com/nicola/captain-log

## Open Questions

1. Where should the project-specific config files for labels-and-milestones be stored?
2. Where should the project-specific config files for roadmap-generator be stored?
4. How and when should these scripts be run (presumably by CI, but what should trigger re-running?)

## Notes
Currently the best list of relevant repositories for each project is in the "sources" list of the project's waffle board. See [js-ipfs](https://waffle.io/ipfs/js-ipfs/settings/sources) and [go-ipfs](https://waffle.io/ipfs/go-ipfs/settings/sources)

**Comment by flyingzumwalt** [comment]
Here's what I had to do to set this up for go-ipfs:
* https://github.com/ipfs/go-ipfs/pull/3390
* https://github.com/ipfs/go-ipfs/pull/3389

Likewise for js-ipfs:
* https://github.com/ipfs/js-ipfs/pull/595
* https://github.com/ipfs/js-ipfs/pull/596

I'm not convinced that we want to store these config files within each project. I just set it up to imitate what @haadcode did in https://github.com/haadcode/orbit/tree/master/tools/roadmap-generator. 

Also it seems odd to make one-off package.json files and README.md files like these, but at this point I just wanted to make everything consistent with https://github.com/haadcode/orbit/tree/master/tools/roadmap-generator and wanted to make sure it's all documented so people can use it while I'm on vacation.

**Comment by diasdavid** [comment]
Feature request: When a milestone is "done" it would be awesome to be able to "close all of those milestones across repos. Right now it has to be manual

**Comment by flyingzumwalt** [comment]
@diasdavid to close a milestone across all the projects you just need to set the status to "closed" on that milestone and re-run the sync tool. Example here: https://github.com/ipfs/js-ipfs/pull/595/files#diff-bf8248917bae166dcc53714cf525dddcR31

**Comment by diasdavid** [comment]
@flyingzumwalt good to drop this one?
