### ISSUE TITLE
Sprint: Nov 21 -> 27

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#258]
# Sprint November 21

_For information about these calls and how they work, read [the ipfs/pm README](https://github.com/ipfs/pm)._

[Calendar](https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com)

Zoom and Stream links will be updated directly before the calls. Links to them will also be dropped in IRC, at the start of each call. If the link below seems to link to this issue, the link has not been updated yet.

**[Zoom link](https://zoom.us/j/3339991818)**
**[Stream link](https://www.youtube.com/watch?v=_ShPj-NhBTE)**

### Monday, November 21st

Endeavour      | Lead            | Time (PST - **UTC/Z** - CET) | Pad
:------------: | :-------------: | :-------------------------: | :----:
All Hands Call | @flyingzumwalt  | 9:00PST **17:00Z** 18:00CET  | [notes](https://hackmd.io/OwDgzATBICxgtAYxsAjPGBDAZgBniAKaLoyIBsYhAJhItpqrkA==)
js-ipfs        | @diasdavid      | 10:00PST **18:00Z** 19:00CET | [notes](https://hackmd.io/MwJgDAhmAsBmAcBaMA2MZHTAEwMaICNcB2FQ2ATgEYUBWCA22WYIA===)
apps on IPFS   | @haadcode       | 10:30PST **18:30Z** 19:30CET | [notes](https://hackmd.io/GYEw7ADBAcBGCGBaY0CcBTRAWE0yNWAGNZEA2AJhHTHgRCyiA===)

### Wednesday, November 23rd

Note: Neither of these two calls will be streamed, but they will be recorded and uploaded later. 

| **Endeavour**   | **Lead** | **Time UTC** | **Pad** |
:----------------: | :--------: | :-------------: | :--------:
go-ipfs        | @whyrusleeping  | 19:00 | [Notes](https://hackmd.io/GwEwLAZiCcIEYFpgGZoAYFgIYFNkLgHYBWLBARjRAGMxziQ05pig)
libp2p         | @diasdavid      | 19:30 | [notes](https://hackmd.io/EYJgDAZgjCAmEFoBsBmYSEBYQEMCmCwAxngcLJlAOzB5JUCsOUQA)

### Friday, November 25th

| **Endeavour**   | **Lead** | **Time UTC** | **Pad** |
|-----|---------|---|---------|
| IPLD |  @nicola  | 17:00  | [Notes](https://hackmd.io/IYFmBMFYE5QWmgIwMYHY4gMwDZN2AAwBMAHHASZtMiOMcjUA) |

Please add any agenda items you have to the pad before the project-specific sprint call starts.

**Comment by RichardLitt** [comment]
Note: I have added the HackMD notes and agendas to each of the sprints above. Going forward, we will use HackMD, following https://github.com/ipfs/community/issues/196. 🎉

**Comment by whyrusleeping** [comment]
I'm going to be either unavailable or in a noisy crowded airport monday morning. I would like to move go-ipfs and go-libp2p calls to tuesday the 22nd, and either keep the time the same, or move it forward (might be easier on the europeans). cc @lgierth and @Kubuxu on your schedule constaints.

**Comment by lgierth** [comment]
Either tuesday or wednesday work for me -- let's decide until tomorrow though

**Comment by kevina** [comment]
Tuesday's are bad for me.  If we move the call the Wed there is a much better change of me being able to attend the go-ipfs call.

**Comment by RichardLitt** [comment]
@whyrusleeping @kevina @lgierth Does Wednesday work for you? 1800Z?

**Comment by Kubuxu** [comment]
Wednesday doesn't work for me until 1845Z.

**Comment by kevina** [comment]
How about we make it 1900Z then?  (But either time works for me.)

**Comment by RichardLitt** [comment]
@whyrusleeping sound good?

**Comment by whyrusleeping** [comment]
Sounds good to me.

**Comment by hsanjuan** [comment]
ok too

**Comment by RichardLitt** [comment]
Updated the schedule.

**Comment by diasdavid** [comment]
@RichardLitt can we start sooner then?

**Comment by RichardLitt** [comment]
We could, yes. Do you think that two hours is enough advance time to let people know that the calls will be shifted? 

Might be best to move the libp2p call to before Apps on IPFS.

**Comment by diasdavid** [comment]
There is a bunch of items in libp2p agenda today that are with respect to go-libp2p, I would like to have @whyrusleeping around for it. Can we move libp2p to Wednesday as well? 
Then we can move js-ipfs to go-ipfs timeslot and we save everyone some extra time today :)

**Comment by RichardLitt** [comment]
1930 for libp2p on Wednesday, then?

**Comment by diasdavid** [comment]
yes, thank you :)

**Comment by dignifiedquire** [comment]
I won't be around on Wednesday or Friday :(
