### ISSUE TITLE
Sprint: November 28 > December 4

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#267]
# Sprint November 28

_For information about these calls and how they work, read [the ipfs/pm README](https://github.com/ipfs/pm)._

[Calendar](https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com)

Zoom and Stream links will be updated directly before the calls. Links to them will also be dropped in IRC, at the start of each call. If the link below seems to link to this issue, the link has not been updated yet.

**[Zoom link](https://zoom.us/j/3339991818)**
**[Stream link](https://www.youtube.com/watch?v=g3Rn1yQX84Q)**

Endeavour      | Lead            | Time **UTC/Z** | Pad
:------------: | :-------------: | :-------------------------: | :----:
All Hands Call | @jbenet  | **17:00Z** | [notes](https://hackmd.io/EYNgrCCGYMwIwFpgA4AsBTBqbyQdgGNF0AmdATmHIDMQ7VIg)
js-ipfs        | @diasdavid      | **18:00Z** | [notes](https://hackmd.io/IwZgnADArA7GAmBaGBDWiAswMkQDnjAFNEAjIqSIgNgCYoMYIg==)
libp2p         | @diasdavid      | **18:30Z** | [notes](https://hackmd.io/IwUw7AHAnFDMIFoDGAGArFBAWMWCGCUwATImACZLnQoRp4RJA===)
go-ipfs        | @whyrusleeping  | **19:00Z** | [notes](https://hackmd.io/KbCGFZgZgEwYwLQwGzgAwICzAIyYQEYCcBOCATOQBzlzVo5VXhA=)
apps on IPFS   | @RichardLitt       | **19:30Z** | [notes](https://hackmd.io/EwFgJgrAZgbAHAZgLRzgBgkkIBGBGJAQwHYEBTFCAYxASquoE5i4g===)

### Friday, December 2nd

| **Endeavour**   | **Lead** | **Time UTC** | **Pad** |
|-----|---------|---|---------|
| IPLD |  @nicola  | 17:00  | [Notes](https://hackmd.io/MwTmEYHYBMAYQLQA4CGBjaCAsIBmuERIAmANgVNlhRBC2gFY1JYg) |

Please add any agenda items you have to the pad before the project-specific sprint call starts.

**Comment by diasdavid** [comment]
Aye! Just realised that tomorrow I won't be available 7pm onwards. Can we switch js-ipfs and libp2p with go-ipfs and apps on IPFS?

@whyrusleeping @haadcode would you be ok with it?

My apologies for the late notice, it got off of my radar with visit to Berlin and all the flying mess.

//cc @RichardLitt @flyingzumwalt

**Comment by haadcode** [comment]
I can't do apps that late. We can switch if someone else can lead it?

**Comment by haadcode** [comment]
Alternatively, I'm also fine *not* doing an apps call this week and give the slot to @diasdavid. There hasn't been any notable progress with Orbit, but I'm not sure how others in the community feel about it.

**Comment by haadcode** [comment]
Due to unexpected turn of events, I can't participate in tonight's calls, sorry for the late notice. 

I've left an [update on Orbit](https://hackmd.io/EwFgJgrAZgbAHAZgLRzgBgkkIBGBGJAQwHYEBTFCAYxASquoE5i4g===#agenda) in the pad for "app on IPFS", and added a small demo for the [all hands](https://hackmd.io/EYNgrCCGYMwIwFpgA4AsBTBqbyQdgGNF0AmdATmHIDMQ7VIg#agenda). Someone will have to moderate the apps call.

**Comment by RichardLitt** [comment]
Thanks for letting us know. I'll moderate the apps call.

**Comment by RichardLitt** [comment]
I've shifted the calls to reflect @diasdavid not being there. We can raise any issues with this in the All Hands call; for now, this is the best way to ensure that @diasdavid is able to attend.

**Comment by diasdavid** [comment]
@haadcode hope everything is ok. Are you around this afternoon? Can you leave an update for us on the developments of `FloodSub` and `Improving Init`?

**Comment by haadcode** [comment]
@diasdavid thanks @diasdavid all is good, just have to do something tonight that I can't do on other nights :)

**Comment by haadcode** [comment]
@diasdavid and check the apps notes for some pubsub related updates.

**Comment by noffle** [comment]
Hiya o/

I'm not going to be able to make the apps time slot either, so I left my ipget 1.0.0 notes on the [pad](https://hackmd.io/EwFgJgrAZgbAHAZgLRzgBgkkIBGBGJAQwHYEBTFCAYxASquoE5i4g===) too. I'm idling in `#Ipfs` though, so ping me if there's any questions and I can answer + update notes asynchronously! :tada:

**Comment by RichardLitt** [comment]
@noffle I read your notes to the peoples. Thank you so much for your work!
