### ISSUE TITLE
Consistent label / state naming for libp2p

### ISSUE THREAD

**Issue by jbenet** [ipfs/pm#272]
It came up in the libp2p call of 11/28 ( #267 ) that:

- go-libp2p things are tracked as part of go-ipfs to reduce friction for the go team
- the libp2p board and effort is there to track all libp2p things (go-libp2p, js-libp2p, etc)
- if the labels were named the same, then we could have the go-libp2p issues show up in both go-ipfs and libp2p boards.

So, this may need:

- [x] verify that works
- [x] rename libp2p progress label names?

not sure, but let's please make sure go-libp2p stuff does get tracked in the libp2p board. cc @diasdavid @whyrusleeping

**Comment by Kubuxu** [comment]
Just renaming labels might not work, what has to happen is for example: for every `libp2p-backlog` label, apply `backlog` label, remove the `libp2p-backlog` label. It for sure can be automated with GH API.

**Comment by diasdavid** [comment]
It works 🎉 Just tested it and renamed the labels in the process :)
