### ISSUE TITLE
Sprint: December 5-11

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#279]
_For information about these calls and how they work, read [the ipfs/pm README](https://github.com/ipfs/pm)._

[Calendar](https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com)

Zoom and Stream links will be updated directly before the calls. Links to them will also be dropped in IRC, at the start of each call. If the link below seems to link to this issue, the link has not been updated yet.

**[Zoom link](https://zoom.us/j/407592909)**
**[Stream link](https://www.youtube.com/watch?v=xRLglRE8AEo)**

### Monday

Endeavour      | Lead            | Time (PST - UTC - CET) | Pad
:------------: | :-------------: | :--------------------: | :----:
All Hands Call | @RichardLitt  | 9:00 **17:00** 18:00  | [agenda and notes](https://hackmd.io/MYQ2FYAYQDgTgLQFMBGB2RAWOJILgGYgoICMAJmuCuQGyb0VA===)
go-ipfs        | @whyrusleeping  | 10:00 **18:00** 19:00 | [agenda and notes](https://hackmd.io/EYY2wdgVgZgDgLQFMAMAWYC0DM4BMFgYYUEBDNCNANjgCYkQyokg)
apps on IPFS   | @haadcode       | 10:30 **18:30** 19:30 | [agenda and notes](https://hackmd.io/BwRlGMBME5gWgEzQMzTgFnMkcBG6QE4BDYYANmXUgpHFyA==)
js-ipfs        | @diasdavid      | 11:00 **19:00** 20:00 | [agenda and notes](https://hackmd.io/GbCsA4CYEMDYFMC0AGAJtAzIgLAIwMaqICc0AjMIpMeBtsvNNKqskA==)
libp2p         | @diasdavid      | 11:30 **19:30** 20:30 | [agenda and notes](https://hackmd.io/GYZgxgbOAmAcC0BGWB2ALPNAGArGeAhgJwCmCOARmCGhAExrBilA)

### Friday

Endeavour      | Lead            | Time (PST - UTC - CET) | Pad
:------------: | :-------------: | :--------------------: | :----:
IPLD           | @nicola         | 9:00 **17:00** 18:00 | [agenda and notes](https://hackmd.io/MwNmHYA4BZgVgLSQIwGNIOgU1apBOAMwCMEAmNABjLP1TNEqA===)

Please add any agenda items you have to the pad before the project-specific sprint call starts.

_Note: This issue was automatically created by [RichardLitt/ipfs-hubot](//github.com/RichardLitt/ipfs-hubot). Cronjobs imminent._

**Comment by VictorBjelkholm** [comment]
Today I won't be able to participate in the calls.

**Comment by dignifiedquire** [comment]
> Today I won't be able to participate in the calls.

we will miss you

**Comment by whyrusleeping** [comment]
re: @haadcode's 'everyone tell us what theyre doing this week'. Thats pretty much all i want the weekly sprint meetings to be all the time.

**Comment by RichardLitt** [comment]
@haadcode I loved the check ins. That is why this is called a sync, too. :)

**Comment by haadcode** [comment]
I liked the sync sync, too. Would love to do it again next week.
