### ISSUE TITLE
Sprint: December 12-18

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#285]
_For information about these calls and how they work, read [the ipfs/pm README](https://github.com/ipfs/pm)._

[Calendar](https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com)

Zoom and Stream links will be updated directly before the calls. Links to them will also be dropped in IRC, at the start of each call. If the link below seems to link to this issue, the link has not been updated yet.

### Monday

Endeavour      | Lead            | Time (PST - UTC - CET) | Pad
:------------: | :-------------: | :--------------------: | :----:
All Hands Call | @lgierth   | 9:00 **17:00** 18:00  | [agenda and notes](https://hackmd.io/JwNgzAJgxgDARnAtMFBGRAWAZjAHI3XAQwFZEYoTdUo4Tg5cAmIA)
go-ipfs        | @whyrusleeping  | 10:00 **18:00** 19:00 | [agenda and notes](https://hackmd.io/MwMwRghgbFAsCsBaCBjCAORtgBMCmiYkATIQJxEDsIUAjFMXsUA=)
apps on IPFS   | @haadcode       | 10:30 **18:30** 19:30 | [agenda and notes](https://hackmd.io/AwYwjMCcBMBmCmBaeAjEAORAWSXMoWEXXQGYBWMAdgDZhSUx0g==)
js-ipfs        | @diasdavid      | 11:00 **19:00** 20:00 | [agenda and notes](https://hackmd.io/AwYwRgpgbA7AJgFgLQEYEGYCcSFQKwRJhwwhICG5ATCuSJjBMMHEA===)
libp2p         | @diasdavid      | 11:30 **19:30** 20:30 | [agenda and notes](https://hackmd.io/IYMwxgbADAnALCAtADgIwGZWLpZiBG6U+2w6AJsGMISMnEA=)

### Friday

Endeavour      | Lead            | Time (PST - UTC - CET) | Pad
:------------: | :-------------: | :--------------------: | :----:
IPLD           | @nicola         | 9:00 **17:00** 18:00 | [agenda and notes](https://hackmd.io/JwBgzAjMDsBsAcBaARnCiAsAmAJgY0WAEMcBWTCAMyxGhGC0uTCA)

Please add any agenda items you have to the pad before the project-specific sprint call starts.

**Comment by hsanjuan** [comment]
@RichardLitt I think the lead for the first is @lgierth ? At least thats what the pad says

**Comment by RichardLitt** [comment]
You're right. Spelling error and tab autocomplete; my bad. :)
