### ISSUE TITLE
Sprint: December 19 - 25th

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#293]
_For information about these calls and how they work, read [the ipfs/pm README](https://github.com/ipfs/pm)._

[Calendar](https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com)

Zoom and Stream links will be updated directly before the calls. Links to them will also be dropped in IRC, at the start of each call. If the link below seems to link to this issue, the link has not been updated yet.

### Monday

Endeavour      | Lead            | Time (PST - UTC - CET) | Pad
:------------: | :-------------: | :--------------------: | :----:
All Hands Call | @dignifiedquire  | 9:00 **17:00** 18:00  | [agenda and notes](https://hackmd.io/GwDgZgRiwMwCwFoAMBOAjAJgXFBWA7AigKbAAmCZS+YK+AhvWRGRkA==)
go-ipfs        | @Kubuxu  | 10:00 **18:00** 19:00 | [agenda and notes](https://hackmd.io/AwTmFMQdhAWBaAbMghvWIUJQY1gDnXAGYUBWfWAIwBMBGRGoA===)
apps on IPFS   | @VictorBjelkholm        | 10:30 **18:30** 19:30 | [agenda and notes](https://hackmd.io/IYMw7ARgHBCsCcBaMBmAJhRAWYNEywDZEJCBjGGWMARiwCYg)
js-ipfs        | @diasdavid      | 11:00 **19:00** 20:00 | [agenda and notes](https://hackmd.io/KwEwRgLApiDMCMBaWFYENEQEwQGyIE40CBjRADgnIAZqSB2eLMNWIA==)
libp2p         | @diasdavid      | 11:30 **19:30** 20:30 | [agenda and notes](https://hackmd.io/MbCmCYCMEZwBgLR2gdgBwICzACYGYFJgBOSQ3AVirwjXHCA=)

### Friday

Endeavour      | Lead            | Time (PST - UTC - CET) | Pad
:------------: | :-------------: | :--------------------: | :----:
IPLD           | @nicola         | 9:00 **17:00** 18:00 | [agenda and notes](https://hackmd.io/CYTgDArGAsBsIFoCMsAcB2B0YQQQwGMBmRAI1iOgOAllOKSA)

Please add any agenda items you have to the pad before the project-specific sprint call starts.

**Comment by RichardLitt** [comment]
@VictorBjelkholm has let me know that Christmas in Sweden is on the 24th. Changed title appropriately.

**Comment by haadcode** [comment]
I won't be able to join the calls tonight. Can someone cover for me in "apps for IPFS"?

**Comment by Kubuxu** [comment]
@whyrusleeping won't be here for the calls either.

**Comment by RichardLitt** [comment]
I would cover you for Apps, but I will only be able to make the All Hands call today, I'm afraid.

**Comment by VictorBjelkholm** [comment]
I can moderate the "apps on IPFS" call, not sure if we have some actual content to discuss though

**Comment by lgierth** [comment]
Updated to schedule to reflect that @Kubuxu will be leading the go-ipfs call, and @VictorBjelkholm the apps call.

**Comment by diasdavid** [comment]
Well, if Apps on IPFS won't have an update today, `js-ipfs` and `libp2p` calls don't mind starting 30 mins earlier :)

**Comment by RichardLitt** [comment]
I may perhaps need to specify the amount of time needed to change a date. I prefer to have the schedule locked down on the previous Friday, because then people know the day of. I think that we should have it anyway, in case someone else - who hasn't posted - wants to talk during that meeting.

**Comment by em-ly** [comment]
The streaming link was never updated for this issue - can someone add that?

**Comment by VictorBjelkholm** [comment]
@em-ly it's been updated now!
