### ISSUE TITLE
Set plan: Documentation (general) endeavor

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#313]
Establish a plan for getting the endeavor out of the stale state and update https://github.com/ipfs/ipfs/pull/224.

**Comment by RichardLitt** [comment]
I believe that this will be done as part of the prep for the Documentation sprint. I wouldn't call this a stale state, either - the awesome API endeavor is still being worked on AFAIK.

**Comment by dignifiedquire** [comment]
As far as I understand stale means it is not being sprinted on, but this will be sprinted on in a couple of weeks as far as I know.
