### ISSUE TITLE
Set plan: multiformats

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#317]
Establish a plan for getting the endeavor out of the stale state and update https://github.com/ipfs/ipfs/pull/224.

**Comment by RichardLitt** [comment]
Is this stale? I'm not sure I am the best to make a plan for this; I mainly run the organization on GitHub, not the overall state of all of the Multiformats.

**Comment by lgierth** [comment]
Yeah multiformats is pretty active and covered by multiple Q1 sprints. It needs a captain's log. :writing_hand:
