### ISSUE TITLE
Set plan: starlog

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#331]
Establish a plan for getting the endeavor out of the stale state and update https://github.com/ipfs/ipfs/pull/224.

**Comment by lgierth** [comment]
I think this one is more dead than on the backburner (last meaningful commit in Sep-2015). It could use a few links to similar, but more up-to-date projects.

**Comment by RichardLitt** [comment]
Plan: 
- [ ] Set up a clear status for projects like this: backburned - closed for now, waiting for feedback
- [ ] Mark the README according to what was decided above
- [ ] Close any open issues or PRs so there are no long-standing threads which make it look open
- [ ] Remove it from any project directory where it is listed as a current endeavor
