### ISSUE TITLE
Set plan: Maps on IPFS

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#334]
Establish a plan for getting the endeavor out of the stale state and update https://github.com/ipfs/ipfs/pull/224.

**Comment by lgierth** [comment]
cc @substack @mikolalysenko @davidar could you give us an idea of what the medium term plans for maps are?

**Comment by substack** [comment]
I'm working on building vector tiles with tilemaker right now on the updated dataset. The files for the new build are still copying to my machine.

**Comment by davidar** [comment]
waiting for OSM2VTv3/OpenMapTiles to be released :)
