### ISSUE TITLE
Sprint: data.gov (aka 300 TB Challenge)

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#342]
See ipfs/archives#87

**Dates**: 16-27 January 2017
**Sprint Milestone**: https://github.com/ipfs/archives/milestone/1
**Team**: 
* @flyingzumwalt (PM)
* @whyrusleeping 
* @Kubuxu 
* @lgierth

**Comment by lgierth** [comment]
Waffle board for this sprint: https://waffle.io/ipfs/archives?milestone=Data.gov%20(aka%20300%20TB%20Challenge)
