### ISSUE TITLE
Sprint: Solidify IPLD

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#343]
## Objectives

- [x] dag API 
  - [x] decision: not mess with types https://github.com/ipfs/interface-ipfs-core/issues/81 @whyrusleeping + @diasdavid 
  - [x] ipfs dag API 
    - [x] spec @diasdavid + @whyrusleeping 
      - [x] cli https://github.com/ipfs/specs/pull/150
      - [x] core https://github.com/ipfs/interface-ipfs-core/tree/master/API/dag#dag-api
    - [x] impl in JS @diasdavid
    - [x] impl in Go @whyrusleeping
  - [x] ipfs.dag API (js-ipfs) @diasdavid
    - [x] basics (get, put)
    - [x] resolve
  - [x] http endpoints for js-ipfs-api @whyrusleeping
  - [x] resolving cases (pick the ones we fully understand)
    - [x] Enumerate all cases we might want to support
      - [x] local resolve
      - [x] resolve through types @whyrusleeping
      - ~~resolve paths within paths @nicola + @whyrusleeping + @diasdavid~~ out of scope
- [ ] IPFS Repo @diasdavid
  - [ ] Update spec
  - [ ] Update js-ipfs implementation
- [ ] IPLD Formats supported
  - [ ] dag-cbor
    - [x] js
      - [x] Update dag-cbor to use tags @diasdavid https://github.com/ipld/js-ipld-dag-cbor/pull/38
    - [x] go
    - [ ] format interop tests  https://github.com/ipld/js-ipld-dag-cbor/pull/40
  - [x] dag-pb
  - [ ] eth formats 
    - [ ] go @whyrusleeping
    - [ ] interop tests  (read nodes generated and serialized by the other)
  - [ ] zcash
    - [ ] js @diasdavid 
    - [ ] interop tests  (read nodes generated and serialized by the other)
  - [ ] git
    - [ ] js @diasdavid
    - [ ] interop tests  (read nodes generated and serialized by the other)
  - [ ] dat
    - [ ] go
    - [ ] js
    - [ ] interop tests  (read nodes generated and serialized by the other)
  - [x] export a bunch of graphs that can use for interop tests @whyrusleeping
- [x] ~~Workbench~~ @whyrusleeping @diasdavid @wanderer while in DAppHackathon - This became https://github.com/ipld/js-ipld-graph-builder
- [x] Agree on converging ipld-node and ipld-format https://github.com/ipld/interface-ipld-format/issues/4
- [ ] IPLD Selector Spec @nicola
  - [ ] Enumerate features needed
- [ ] Examples/Tutorials
  - [ ] Enumerate examples @nicola
  - [ ] Pick top 3 
- [ ] respond to: http://ipfs.trydiscourse.com/t/what-is-inter-planetary-linked-data/73 @nicola 

Out of the scope of this sprint:
- [ ] Ship ipld.io

## Team for this Sprint: 
- @diasdavid (PM)
- @whyrusleeping 

## Dependencies

**Comment by flyingzumwalt** [comment]
@nicola is also on this sprint -- couldn't add him as an assignee because he wasn't a collaborator on this repo yet (waiting for confirmation of invite)

**Comment by nicola** [comment]
Was "IPLD Selector Spec" really part of this sprint?
I happen to be doing work on this in the past few days, I thought we did not consider it

**Comment by diasdavid** [comment]
>  IPLD Selector Spec, get bitswap to use it

I don't know how they appeared in the list.. I didn't have any discussion that it would be a goal of the sprint. Yet, we might do a lot of work or even push ourselves to do it.

**Comment by diasdavid** [comment]
@nicola did you remove yourself from this Sprint?

**Comment by diasdavid** [comment]
# Prep session doodle http://doodle.com/poll/yk6xu87q3xxrqyhk

@whyrusleeping @nicola please add your availabilities.

**Comment by nicola** [comment]
@diasdavid I will be in Palo Alto (sorry for the bad timing)

**Comment by whyrusleeping** [comment]
@diasdavid I don't think i can make any of those times, The most likely is 10am friday morning (the rest of the times are all too early in the morning)  but i don't have more than an hour of availability there.

**Comment by diasdavid** [comment]
@whyrusleeping 9am doesn't work for you? What about right after the all hands? Any proposed solution?

**Comment by diasdavid** [comment]
Added another hour (yours 10pm Thursday) http://beta.doodle.com/poll/yk6xu87q3xxrqyhk @nicola @whyrusleeping

**Comment by diasdavid** [comment]
# Prep session notes: https://hackmd.io/MYFgHMAMBGDsBmBaaATAzAJkSDBTAbIgJySyyICM0ArNAIbDV4h1FA==?edit

**Comment by diasdavid** [comment]
# David's check-in Mon 30

- Clean up last things from last sprint
- Doctor appt
- [ ] Update dag-cbor to use tags
- [ ] Revisit js-ipfs DAG API (finish get + put + delete)

**Comment by nicola** [comment]
# Nicola's check-in Mon 30
- [ ] provide david's examples
- [ ] progress with the tutorial (https://github.com/ipld/website/pull/27)
- [ ] progress with simple spec writing (https://github.com/ipld/specs/pull/12)
- [ ] write down first attempt at IPLD Selectors

**Comment by diasdavid** [comment]
# David's check-in Mon 30

Update from yesterday:
- Didn't have time to go through things as much as I wanted, but did a good catch up with Kumavis on prep for DAppHackathon and expanded the list of tasks here to be more discriptive

Today:
- [x] Upgrade dag-cbor to use tags
- [x] Break the DAG API into 3 different PR (basics, resolve and workbench)
- [ ] DAG API basics
  - [x] interface definition
  - [x] js-ipfs impl
  - [ ] js-ipfs-api impl
- [ ] Update Block API to understand how to put blocks from other types
  - [ ] interface
  - [ ] js-ipfs impl
  - [ ] js-ipfs-api impl

**Comment by diasdavid** [comment]
@whyrusleeping need your input (urgent) on https://github.com/ipfs/interface-ipfs-core/issues/81

**Comment by diasdavid** [comment]
@whyrusleeping, @gozala is trying to resolve base16 encoded values in CIDv1, but without success, I also tried and no go, what are we forgetting here?

From IRC

```
21:58 <gozala> daviddias: Ping!
21:58 <gozala> daviddias: I’ve tried to use cids@4.0.0 but still don’t seem to get it to do what I wanted
21:59 <gozala> daviddias: here is the snippet of code https://runkit.com/gozala/58645fba7240320014993626
21:59 <gozala> daviddias: I’m essentially trying to take this address http://localhost:8080/ipfs/QmPZ9gcCEpqKTo6aq61g2nXGUhM4iCL3ewB6LDXZCtioEB
22:00 <gozala> and transcode it to base 16 to have all lower case
22:00 <gozala> http://localhost:8080/ipfs/f1701220120f6af601d46e10b2d2e11ed71c55d25f3042c22501e41d1246e7a1e9d3d8ec
22:01 <gozala> but when I do so go-ipfs 0.4.4 fails to resolve path with: not a key error
```

**Comment by diasdavid** [comment]
Sprint has happened. Closing this issue.

Make sure to check:

- js-ipfs examples of the dag API https://github.com/ipfs/js-ipfs/tree/master/examples/dag
- docs https://github.com/ipfs/interface-ipfs-core/tree/master/API/dag
- spec format https://github.com/ipld/interface-ipld-format
