### ISSUE TITLE
Sprint: Orbit #1 Release Process

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#345]
*Updated by @haadcode after original posting*

**Objective:**

Make Orbit easily downloadable and accessible.

**Goals:**

- We'll focus on fixing the remaining issues with pubsub and improve orbit's correctness. 
- We'll make the Electron app easily downloadable and document how to make releases.
- We'll make Orbit available at https://orbit.chat and document how to deploy a new release.
- We'll move Orbit and orbit-db repos to orbitdb organization (github.com/orbitdb)

**Stretch Goals:**

- We'll define integration tests for Test Lab.

*We'll try to reach this goal if we have time at the end of the sprint. Given the re-allocation of people for this sprint, we might not have the time. If we don't reach this goal in this sprint, @haadcode will work on this during the next sprint, before the Test Lab sprint.*

**Tasks:**

- Finish js-ipfs-api pubsub and use it in Orbit
  - Tracking issue: https://github.com/haadcode/orbit-db/issues/184
  - Pubsub API PR https://github.com/ipfs/js-ipfs-api/pull/493
  - Update the pubsub component in orbit (orbit-db-pubsub) use to use the current pubsub API
- Make Orbit Electron App available for download from dist.ipfs.io
  - Tracking issue: https://github.com/haadcode/orbit/issues/132
  - Document how to make Orbit Electron App builds
  - Document how to make dist.ipfs.io releases
  - Release new dist.ipfs.io page with Orbit download links
- Make Orbit Web App available for use at https://orbit.chat
  - Tracking issue: https://github.com/haadcode/orbit/issues/225
  - Document orbit-web release process
  - Document the deployment process to orbit.chat
- Immutable ipfs-log
  - Tracking issue: https://github.com/haadcode/ipfs-log/issues/97
  - Merge "Immutable ipfs-log" https://github.com/haadcode/ipfs-log/pull/100
  - Make orbit-db use immutable ipfs-log: https://github.com/haadcode/orbit-db/pull/185
- Move repos to orbitdb organization
  - Tracking issue: https://github.com/orbitdb/orbitdb/issues/1
  - Reorganize haadcode/orbit code base: https://github.com/haadcode/orbit/issues/223
- Add orbit, orbit-db, ipfs-log tests to js-ipfs(-api) release process
  - Tracking in: https://github.com/ipfs/js-ipfs/issues/747

**Additional Tasks:**

- Identify and define integrations tests
  - Tracking issue: https://github.com/haadcode/orbit/issues/224
  - Enumerate a list of tests that Orbit should run in Test Lab
  - We'll work on these tasks if we have complete the main goals

**Comment by haadcode** [comment]
We've had some reshuffling on who's working on this sprint. We'll have to re-scope the content of the sprint as it's going to be just me and @RichardLitt in this sprint. We'll have a planning meeting today and see what we can commit to.

My current thinking is we'll focus on the correctness related task and the release process. We should also work on moving the repos under https://github.com/orbitdb which includes finally splitting the orbit* repos appropriately.

> Add orbit, orbit-db, ipfs-log tests to js-ipfs(-api)
> orbit-db and ipfs-log tests should be run as part of CI tests

@diasdavid and @dignifiedquire I know you're gonna be super busy in your upcoming sprints, but would you be able to fit ^ on your todo list? Or perhaps provide a *detailed* instructions on how to do approach it?

**Comment by diasdavid** [comment]
I don't believe adding to CI to be always run will be good (our poor CI already takes so long) and it will be a cat and mouse game because then we have to be updating as you go (and when to update what)

I do believe though that it should be part of the release process as we did -- https://github.com/ipfs/js-ipfs/issues/712 -- it just needs to be formalized.

**Comment by dignifiedquire** [comment]
Maybe we can work together with @VictorBjelkholm and @Kubuxu to make sure we can run these tests as part of our new CI setup?

**Comment by haadcode** [comment]
> I do believe though that it should be part of the release process as we did -- ipfs/js-ipfs#712 -- it just needs to be formalized.

I'm ok either way. @RichardLitt or me will open an issue in js-ipfs this week to follow up on this.

**Comment by haadcode** [comment]
I've update the original issue to reflect the plan for this sprint, see https://github.com/ipfs/pm/issues/345#issue-200908573.

@RichardLitt see the TODO I left you for opening an issue to track adding orbit tests to the js-ipfs release process as per our discussion yesterday (and the comments above).

**Comment by haadcode** [comment]
I've updated the Orbit's board at https://waffle.io/haadcode/orbit. You'll see the planned goals in the "Backlog" column and the ones "In Progress" are currently being actively worked on. There are additional cards in both that are random bugs etc. to be verified to be fixed as we go.

**Comment by RichardLitt** [comment]
Opened.

**Comment by diasdavid** [comment]
Sprint has happened. Closing this issue.
