### ISSUE TITLE
Sprint: Orbit #2 Stability

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#355]
**Objective:**

Improve Orbit stability by writing integration tests. 

**Goals:**
- Write integration tests in Test Lab
- Fix integration test issues

**Comment by dignifiedquire** [comment]
- [ ] Ship Immutable IPFS Log @haadcode 
- [ ] Find a solution to the "History Problem" 
  - [ ] Prototype in JS for history based pubsub @dignifiedquire
- [ ] Mockup & Prototype a Light Theme @dignifiedquire
  - Investigate usage of https://github.com/styled-components/styled-components
