### ISSUE TITLE
Sprint: Delightful Documentation

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#357]
A major sprint with all core maintainers entirely focusing on Documentation for 2 weeks.

## Objectives

- Remove/delete/burn outdated documentation
- Overview lists and diagrams for the whole IPFS stack
- Code examples for all layers of the IPFS stack, and how they fit together
- Overhauling examples on the website
- Adding usage and API sections to current ipfs and libp2p modules
- Checking all commands for ipfs cli tool
- Working on examples for various modules and the system as a whole
- Building a "take your data and use IPFS X" process doc for large institutions.
- Rethinking organizational structures
- Standardizing all organizations
- Getting approval from all committers for licensing and patents - sign off's from before we had sign offs
- Godoc for all go packages

## Waffle board

https://waffle.io/ipfs/docs

## Team for this Sprint

@Kubuxu, @diasdavid, @hsanjuan, @lgierth, @flyingzumwalt, @nicolagreco, @SidHarder (PM)

## Dependencies

**Comment by flyingzumwalt** [comment]
related: https://github.com/ipfs/community/issues/214, https://github.com/ipfs/community/issues/215

**Comment by flyingzumwalt** [comment]
This sprint needs to also address the install experience. There's no point in having documentation if people can't install your software.

**Comment by flyingzumwalt** [comment]
This work is being tracked in the https://github.com/ipfs/docs/issues repository.

**Comment by lgierth** [comment]
Sprint prep: https://github.com/ipfs/docs/issues/20

**Comment by lgierth** [comment]
Waffle board: https://waffle.io/ipfs/docs

**Comment by lgierth** [comment]
I think I've updated the assigned people accordingly -- @VictorBjelkholm @dignifiedquire @whyrusleeping please fix if neccessary :):)

**Comment by lgierth** [comment]
I've updated the waffle board and assignments a bit, please feel free to reassign and reshuffle how you see fit.

**Comment by lgierth** [comment]
# docs sprint standup 15-Mar-2017

participants:
- daviddias
- hsanjuan
- jaycarpenter
- tomkorrison
- lgierth
- flyingzumwalt

updates:
- daviddias
    - improved interface-ipfs-core spec
        - readme
        - polishing function documentation, at least one example for each
        - went through js-ipfs and js-ipfs-api and added links to function definitions
    - improved js-ipfs-init
        - simplified, removed cruft
        - one-step process, and three-step process
        - involved many code and docs changes
    - now: finishing js-ipfs tutorial
    - next: make adding webrtc/ws addresses easier
- hsanjuan
    - wrote ipfs-update install guide
    - improved fs-repo-migrations docs
    - now: go-libp2p examples
    - now: golint on go-libp2p
    - next: more going through repos/packages
- jaycarpenter
    - intro: involved in telecommunications, and north-american regulatory bodies, naming, addressing
    - reviewing various communication and documentation channels, @flyinzumwalt's write-up
    - working on documentation process proposal
    - participating in ipfs/docs#29
- tomkorrison
    - compiled https://github.com/ipfs/docs/issues/31
- lgierth
    - wrapping up go-ipfs core-api refinements
    - collected information for centralizing go-libp2p interfaces
        - not so convinced anymore
        - gonna let it rest for a few days
    - next: set up temporary trusted host for automatic website builds
- flyingzumwalt
    - now: working on discourse decision, and decision-making process
    - next: making sure we're on the path to doing docs properly
- kubuxu
    - "I can't join, sorry. As an update, I haven't done much with docs, mostly other work."

discussion:
- more tasks for david? :)
    - how to start contributing
    - webrtc-star
    - ...
- ...

**Comment by lgierth** [comment]
Recording: https://ipfs.io/ipfs/QmPK36kZomjSgyiXTfwuwgWwsrRQp8XNynyAJWhGA8Q3Gm

cc @SidHarder @Kubuxu

**Comment by lgierth** [comment]
Standups are Wednesday 4p UTC and Friday 4p UTC (just to prevent confusion)

That's 5p CET, dear other folks in central europe.

**Comment by lgierth** [comment]
Wednesday standup recording https://ipfs.io/ipfs/QmTvjfBCAGnG9gyqeQMGDRgs4VddFwCUYtUwMmxSYbPYRL
