### ISSUE TITLE
Sprint: Browser uses DHT to discover content 

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#358]
## Objectives

- js-datastore
  - [x] interface-datastore
  - [x] js-datastore-level-db
  - [x] js-datastore-fs
  - [x] js-datastore-indexed-db
- [x] libp2p-dht https://github.com/libp2p/js-libp2p-dht/pull/1#issue-198376271
- [x] Get bootstrappers to speak Browser WebSockets https://github.com/ipfs/js-ipfs/pull/740
- [ ] Relay
  - [x] Finish the spec https://github.com/libp2p/specs/pull/15
  - [ ] Finish implementation in JS
  - [ ] Implement in Go

## Dependencies

**Comment by diasdavid** [comment]
Apologies for the late notice, but as @lgierth brought up in IRC, we should have a standup today.

I've just updated this issue to make it a sprintino from a sprint (just one week, a very ambitious one) and added a calendar event to the IPFS Community. Essentially today (wednesday) and Friday at 4pm UTC -- https://www.worldtimebuddy.com/?qm=1&lid=5391959,100,2267057,2950159&h=100&date=2017-3-29&sln=16-17 --

![image](https://cloud.githubusercontent.com/assets/1211152/24460647/d55c7056-1496-11e7-975e-7053571891a5.png)

@lgierth @dignifiedquire @VictorBjelkholm @whyrusleeping @dryajov can you make it?

**Comment by diasdavid** [comment]
Ok, due to lack of response (again understandable given the short notice), let's defer this meeting to be done Friday only. If someone doesn't feel that they know what they should be focused on, let me know so we can sync up fast.

**Comment by lgierth** [comment]
We did meet in the end, recording and notes posted here: https://github.com/ipfs/in-web-browsers/pull/48

**Comment by diasdavid** [comment]
### The last sprintino standup call https://zoom.us/j/3339991818

**Comment by flyingzumwalt** [comment]
@diasdavid @dryajov are the remaining items for this issue resolved? do we have relay? do bootstrappers speak to browser web sockets?

**Comment by diasdavid** [comment]
- Relay needs to be fully reviewed, tested and merged (there are tests that showcase its functionality already, we just need to make sure we are being rigorous enough
- Integrate DHT with the remaining of IPFS modules (it is merged up to libp2p level)
- WebSocket bootstrapers are there, but need some tunning because of normal nginx WebSockets timeouts - https://github.com/ipfs/js-ipfs/pull/740
