### ISSUE TITLE
Handle Stale Endeavors

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#361]
See https://github.com/ipfs/pm/milestone/5

**Captain**: @flyinzumwalt
**Due**: Week 6

The info about the endeavors will be recorded in the ipfs/ipfs Roadmap. See PR: https://github.com/ipfs/ipfs/pull/224

This issue will be "done" when we 
- [ ] have a list of all endeavors, their captain, and their status 
- [ ] have a plan for how each endeavor will be handled in the coming quarter (ie. "[remedies](https://github.com/protocol/lab-week-2017-Q1/blob/master/wall_notes.md#resolutions)" identified in [this session at Q1 lab week](https://github.com/protocol/lab-week-2017-Q1/issues/22)
- [ ] have added any required work for each endeavor to the endeavor's captain's OKRs

## Target Statuses

Some sample target statuses

### Back Burner
If it's going on the back burner, the captain needs to spell out what that means, and what work is necessary to keep it in a healthy "back burner" state.

### Set it Free
Some target statuses if we're going to put it in a box on the church steps: "abandoned ship, “closed indefinitely”, “scuttled”

**Comment by diasdavid** [comment]
Some of the Stale Endeavours (I say some because the list must have grown by now) are tagged with "planning" in this repo https://github.com/ipfs/pm/issues?q=is%3Aissue+is%3Aopen+label%3Aplanning
