### ISSUE TITLE
Monday Calls: January 23rd

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#366]
_For information about these calls and how they work, read [the ipfs/pm README](https://github.com/ipfs/pm)._

[Calendar](https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com)

Zoom and Stream links will be updated directly before the calls. Links to them will also be dropped in IRC, at the start of each call. If the link below seems to link to this issue, the link has not been updated yet.

### Monday

Endeavour      | Lead            | Time (PST - UTC - CET) | Pad
:------------: | :-------------: | :--------------------: | :----:
All Hands Call | @dignifiedquire   | 9:00 **17:00** 18:00  | [agenda and notes](https://hackmd.io/GYQwDAbKDGAmC0AjYp4BZgA4LxAJlhHmgjETAFNgBGTAZjWqA===)
Sync Between Sprints      | @flyingzumwalt    | 10:00 **18:00** 19:00 | [agenda and notes](https://hackmd.io/GwTgRgZsDMwIwFo5wEwQQFgKYnWLWKC0WADAMbBYAcWMFQA=)

### Tuesday-Friday Standup Calls

Endeavour      | Lead            | Time (PST - UTC - CET) | Pad
:------------: | :-------------: | :--------------------: | :----:
Standup Call: data.gov (aka 300 TB Challenge)       | @flyingzumwalt   | 10:00 **18:00** 19:00| [waffle board](https://waffle.io/ipfs/archives)

Please add any agenda items you have to the pad before the project-specific sprint call starts.

**Comment by RichardLitt** [comment]
We will start the Sync Between Sprints meeting five minutes early, at 17:38.

**Comment by jbenet** [comment]
what is the stream link? it's wrong here

**Comment by jbenet** [comment]
https://www.youtube.com/watch?v=jCPpyoNxoJc

**Comment by RichardLitt** [comment]
In the future, I or @dignifiedquire will change the link to reflect the video that the stream was saved too. This should clear that up.
