### ISSUE TITLE
Rename 'Sprint' label

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#369]
@flyingzumwalt recently co-opted the `sprint` label to refer to project management issues that refer to sprints, whereas previously it was used for the issues that had the times for sprint calls in them. This was a hangover from an earlier period where we actually discussed our projects in sprint issues. However, this now makes it hard to find the issue saying where the calls are, as there are multiple types of `sprint` issues.

Let's rename `sprint` for the Calls issue to `calls`, and use `sprint` to mean project sprints. Sound good?

**Comment by flyingzumwalt** [comment]
:+1:

**Comment by RichardLitt** [comment]
Done.
