### ISSUE TITLE
Monday Calls: Jan 30-Feb 05

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#370]
_For information about these calls and how they work, read [the ipfs/pm README](https://github.com/ipfs/pm)._

[Calendar](https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com)

Zoom and Stream links will be updated directly before the calls. Links to them will also be dropped in IRC, at the start of each call. If the link below seems to link to this issue, the link has not been updated yet.

### Monday

Endeavour      | Lead            | Time (PST - UTC - CET) | Pad
:------------: | :-------------: | :--------------------: | :----:
All Hands Call | @RichardLitt   | 9:00 **17:00** 18:00  | [agenda and notes](https://hackmd.io/GwVgzATAhhwOwFoCcAzARhBAWJAOYyAJiAIwIki4gpS6EDGADEgKZA==)
Sync Between Sprints      | @flyingzumwalt    | 10:00 **18:00** 19:00 | _See above_.

Please add any agenda items you have to the pad before the project-specific sprint call starts.

**Comment by flyingzumwalt** [comment]
@richard the data.gov sprint ends on the 27th, so no more standup calls for that sprint.

**Comment by RichardLitt** [comment]
@flyingzumwalt I automatically created this using the template from the last week. Can we edit the template for the next one? Should I just remove that section, or make the title change? 

I've made a bot to make these issues in the future. See [node-github-issue-bot](https://github.com/ipfs/node-github-issue-bot).

**Comment by flyingzumwalt** [comment]
Leave that section out. Allow people to add info like that if they need to. It's up to the sprint teams to decide how they will do their daily check-ins. As the PM for then data.gov Sprint I added that section because we decided to do daily standup calls. I think it's best to allow future teams to do the same.
