### ISSUE TITLE
Choose name for repo to track "browser integrations" endeavor

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#421]

**Comment by dignifiedquire** [comment]
- `are-we-browser-yet`
- `are-we-in-the-browser-yet`

**Comment by Kubuxu** [comment]
+1 for that

It is convention that Mozilla uses benchmarks and different compats: https://arewefastyet.com/

I would put ipfs somewhere there.

**Comment by dignifiedquire** [comment]
Yeah this was inspired by 
- http://www.arewewebyet.org/
- https://areweideyet.com/

both of which are Rust projects

**Comment by flyingzumwalt** [comment]
Additional options
* `native-in-browser`
* `browser-integrations`

**Comment by lgierth** [comment]
- are-we-browser-yet is good
- otherwise: browser-ipfs, as in, ipfs in the browser environment, which has an intersection with js-ipfs, but is *not* the same

**Comment by lgierth** [comment]
Wait, actually are-we-browser-yet requires a sort of checklist of things that we and others need to achieve in order to "be browser yet".

**Comment by flyingzumwalt** [comment]
@lgierth I think one of the deliverables of this sprint will be to create that checklist of things we need in order to "be browser yet". Maybe that's an indication that `are-we-browser-yet` is the right name.

**Comment by jbenet** [comment]
- maybe `ipfs/in-the-browser`
- 👎 on `ipfs/are-we-browser-yet` because it's grammatically incorrect, and this repo may be referenced in a bunch of high touch relationships with professional people. but i like the idea
- maybe `ipfs/are-we-in-browsers-yet`?

**Comment by flyingzumwalt** [comment]
I'm going to go with [ipfs/in-web-browsers](https://github.com/ipfs/in-web-browsers) for now. We can change it later if we come up with a better name.
