### ISSUE TITLE
Monday Calls: Feb 27-Mar 05

### ISSUE THREAD

**Issue by ipfs-helper** [ipfs/pm#427]
_For information about these calls and how they work, read [the ipfs/pm README](https://github.com/ipfs/pm)._

[Calendar](https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com)

Zoom and Stream links will be updated directly before the calls. Links to them will also be dropped in IRC, at the start of each call. If the link below seems to link to this issue, the link has not been updated yet.

### Monday

Endeavour      | Lead            | Notetaker | Time (PST - UTC - CET) | Pad
:------------: | :-------------: | :-------: | :--------------------: | :----:
All Hands Call | @dignifiedquire  | @flyingzumwalt  | 9:00 **17:00** 18:00  | [agenda and notes](https://hackmd.io/OwEwrAxgpiwIwFpgBYDMBDByrqggRgGbqbDrACcYwhqcFUFQA===)
Sync Between Sprints      | TBD    | TBD | 10:00 **18:00** 19:00 | [agenda and notes](https://hackmd.io/CwU2GYEMRATBaUBjADIlBWBkkHYBm8S+SAbBvvgJy66lVA==)

Please add any agenda items you have to the pad before the project-specific sprint call starts.

Note that the agenda notes do not automatically have content added to them (see [tracking issue](https://github.com/ipfs/node-github-issue-bot/issues/8)). Either add [this template](https://raw.githubusercontent.com/ipfs/pm/master/templates/agenda-for-all-hands-call.md) or ping @RichardLitt for now.

The sprints for the week are available to view in the [WaffleBoard](http://waffle.io/ipfs/roadmaps) for [ipfs/roadmaps](https://github.com/ipfs/roadmaps).

**Comment by dignifiedquire** [comment]
@RichardLitt I think it's taking lead and notetaker from the beginning again. I don't think we already went through everyone already

**Comment by RichardLitt** [comment]
It isn't. @diasdavid was supposed to be the notetaker last week, as he is after why. Now, he is the lead. It rotates from the lead, not from the second spot (had to make considerations somewhere).

**Comment by dignifiedquire** [comment]
Hmm still confused but okay. @diasdavid is on holidays for the next 2.5 weeks so he won't be able to take his spots

**Comment by RichardLitt** [comment]
If you look at the list, @whyrusleeping is the last one. The next is @diasdavid. It rotates based on the lead. The notetaker is the next one. I think you were thrown off because we skipped a few notetakers.
