### ISSUE TITLE
Link to Chat log

### ISSUE THREAD

**Issue by SidHarder** [ipfs/pm#429]
@RichardLitt I'm having trouble finding the link to the archived chat logs.  Do you know what the link is.

**Comment by RichardLitt** [comment]
I don't. @whyrusleeping does, I believe.

**Comment by dignifiedquire** [comment]
Which chat log are you talking about? IRC is here: https://botbot.me/freenode/ipfs/

**Comment by SidHarder** [comment]
@dignifiedquire That's what I was looking for, Thanks.
