### ISSUE TITLE
some sprint changes

### ISSUE THREAD

**Issue by jbenet** [ipfs/pm#43]
All the sprints syncs, discussions, and planning are very useful to know where we're headed. But the process has some bugs. let's tighten it up.

### Bugs:
- ambiguity as to who wants to participate fully in the sprints or not. (some contributors want to add an update at the end and talk about their things in the sync, but _don't want to commit_ to things up front).
- ambiguity as to who wants to be reminded about TODOs -- sometimes people forget to drop their TODOs. and it's not clear whether they want to be reminded
- ambiguity as to whether something is a "commit to get done" vs "hopefully get done". to move fast as a team it's important to have the `commits` be very clear, but there should be room for the `hopes` too.
- sprint discussions start or run late. moving to fixed calendar events will help.
- sprint discussions are too short (people have asked to allocate 45 min). I'm ok to try this but suspect some of them will be too long. it may be that we should just be tightening up the conversation, or separating busy hangouts out into two.
- we do not remember to fill out their TODOs every day. (it's friday and there were only 2 listings this week)

### Proposed solutions: 

These are proposed solutions. please comment on them and will pick some to implement for this next monday.

- (1) make a list of people who _want_ to be reminded to drop their TODOs, so there is no ambiguity. you can add or remove yourself with a PR into this repo.
- (2) assume a TODO is a `commit` unless it is tagged (inline) with `hope:`. example:
   > - [ ] hope: merge IPLD into go-ipfs
- (3) make repeating calendar events for the sync + hangouts in the [IPFS community calendar](https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com)
- (4) tighten the sprint hangouts with an agenda -- whoever is leading the hangout should prepare it beforehand. can add it to the notes pad for the hangout.
- (5) **a single person should be responsible for the sprint process every week.** (make new sprint issue,  ask people to drop their updates in the old one, remind people to drop their TODOs in the new one). this does not mean the IRC syncup, but rather the github setup + reminding people. i sadly cannot do this as i have way too much organizational stuff to take care of separately. any volunteer? 

### Notes:
- though we discussed this, @diasdavid on second thought, i really don't know about making these discussions 45min. i think our discussions are often not very focused. also, `45/60 * 5 = 3.75` hrs, instead of `2.5`. Let's try one change at a time: let's do calendar events + agenda this week. if we still think that's too short,

**Comment by diasdavid** [comment]
> Let's try one change at a time: let's do calendar events + agenda this week. if we still think that's too short

ok :) 

> i sadly cannot do this as i have way too much organizational stuff to take care of separately. any volunteer?

I can do it (and/or peer with someone if someone else is also interested)

**Comment by whyrusleeping** [comment]
I think that the hangouts purpose should be to decide on concrete set of TODO's for each person each week. At the end of the hangouts, everyone should have some written down in the issue

**Comment by RichardLitt** [comment]
> (1) make a list of people who want to be reminded to drop their TODOs, so there is no ambiguity. you can add or remove yourself with a PR into this repo.

I am very much for this. I think that editing this list frequently - as in, if someone doesn't want to be reminded in a particular week - isn't a problem at all, as long as it is in this repo. But having a list of people would be immensely helpful. I tried pinging everyone in the previous weeks, and I felt like I was infringing on some people's wishes but I didn't know who. Having a list of people the Sprint master can ping without fearing that they're being annoying would be incredibly helpful. This is the main reason I didn't volunteer to be sprint master last week; I didn't want to step on anyone's toes.

Let's put this list at the bottom of the README. Sound good?

> (2) assume a TODO is a commit unless it is tagged (inline) with hope:. example: > - [ ] hope: merge IPLD into go-ipfs

I think this works well. What about longer issues? It's easy to phrase 'Write docs' to 'Make significant headway on docs', which basically circumvents the "hope" issue. I think we should make sure that we use actionable TODOs, only. I can't find a good blog post outlining what I mean by actionable, but anyone familiar with GTD theory will recognize it - things which can be closed, and aren't open ended. 

> (3) make repeating calendar events for the sync + hangouts in the IPFS community calendar
> (4) tighten the sprint hangouts with an agenda -- whoever is leading the hangout should prepare it beforehand. can add it to the notes pad for the hangout.

Good idea! and agreed. 

> (5) a single person should be responsible for the sprint process every week. (make new sprint issue, ask people to drop their updates in the old one, remind people to drop their TODOs in the new one). this does not mean the IRC syncup, but rather the github setup + reminding people. i sadly cannot do this as i have way too much organizational stuff to take care of separately. any volunteer?

I think splitting this up from the IRC syncup - something I am not good at - to the GitHub setup makes a lot of sense. I am more than happy to be in charge of the GitHub setup, as long as the list of people I can ping is clear as mentioned in point 1. That would make this easy, and something I am more than happy to do.

> I think that the hangouts purpose should be to decide on concrete set of TODO's for each person each week. At the end of the hangouts, everyone should have some written down in the issue

Agreed, but some people don't necessarily go to the hangouts. Those people should have a list made by the end of the day, I guess.

**Comment by jbenet** [comment]
@RichardLitt :+1: to all your points.
