### ISSUE TITLE
Improving multihash

### ISSUE THREAD

**Issue by DonaldTsang** [ipfs/pm#455]
Apparently the codes in the Multihash test cases and the multihash specification do not match.

**Comment by DonaldTsang** [comment]
The problem:
https://github.com/multiformats/go-multihash/blob/master/sum_test.go#L34
The first two bytes of Line 34 should be b240 while the first two bytes of Line 37 should be b260.
Links to adding Skein in the standard:
https://github.com/multiformats/multihash/pull/83
https://github.com/multiformats/js-multihash/pull/34
https://github.com/multiformats/go-multihash/pull/52

**Comment by lgierth** [comment]
Thanks for noticing! Could you file an issue in multiformats/go-multihash instead, and close this one?

**Comment by DonaldTsang** [comment]
@Igierth Issue already filed but no one noticed, so I brought it here.

**Comment by Kubuxu** [comment]
@DonaldTsang you mean the hex string doesn't match?

This is due to varint encoding.

**Comment by diasdavid** [comment]
let's continue this convo on https://github.com/multiformats/multihash/pull/83
