### ISSUE TITLE
Pick a less confusing name for ipfs-labs github org

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#467]
background: https://github.com/ipfs/pm/issues/448

https://github.com/ipfs-labs/

This name is great, and descriptive, but it confuses things because the main company steering IPFS is called Protocol Labs. What's another name we can use for the org that still implies open experiments that are less tightly controlled/maintained?

**Comment by lgierth** [comment]
Yeeah I can see how that might be confusing. I don't have the one great idea, but something like:

- ipfs-universe (ubuntu has this notion of "main" and "universe" package repositories)
- ipfs-extras
- ipfs-incubator
- ipfs-playground

**Comment by VictorBjelkholm** [comment]
`ipfs-community`

**Comment by JayCarpenter** [comment]
IPFS Launch Pad

**Comment by diasdavid** [comment]
What about dropping the `FS` and doing:

- IPI - InterPlanetary Incubator
- IPLP - InterPlantery Launch Pads
- ... etc?

**Comment by flyingzumwalt** [comment]
I almost went with ipfs-incubator then I realized we can call it ipfs-shipyard, riffing on @JayCarpenter's launch pad suggestion.

We're starting to release stuff from that org, like https://github.com/ipfs-labs/shared-editing-demo, so need to settle on a name.

**I propose ipfs-shipyard** Let's allow 24 hours for people to :+1: or :-1: this comment. If it gets any -1 votes we'll check in. Otherwise I will update the organization name to ipfs-shipyard

**Comment by diasdavid** [comment]
![image](https://user-images.githubusercontent.com/1211152/28224483-2f67de30-68c7-11e7-9596-59b8ec02f2b3.png)

**Comment by diasdavid** [comment]
Decision on ipfs-shipyard!
