### ISSUE TITLE
Fix the moderator/notetaker rotation

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#483]
The script that generates issues for each week's all hands call assigns moderator and notetaker based on the list at https://github.com/ipfs/pm#facilitators-and-notetakers

That list has drifted out of date, so people keep getting assigned who aren't on the call. How can we fix this?

Meanwhile, that script doesn't apply the [agenda template](https://github.com/ipfs/pm/blob/master/templates/agenda-for-all-hands-call.md) to the hackpad. We should fix that too.

**Comment by diasdavid** [comment]
ping @RichardLitt. Is the code + deploy script available? 

Is this running in our own infra, @lgierth?

**Comment by RichardLitt** [comment]
It's all here. https://github.com/ipfs/sprint-helper.

**Comment by RichardLitt** [comment]
See https://github.com/ipfs/infrastructure/tree/master/sprintbot

**Comment by flyingzumwalt** [comment]
cc @VictorBjelkholm and @lgierth  -- @pmthomps has offered to help with this on today's all hands.  Looks like it's partially a code fix on sprintbot and partially about redeploying the bot?

**Comment by pmthomps** [comment]
Submitted PR for fix (see Issue #586) .   Bot will need to be redeployed and run.  Let me know if you'd like my help.

**Comment by diasdavid** [comment]
Fixed by @VictorBjelkholm ❤️ QA-Testing-DX WG
