### ISSUE TITLE
🦑 IPLD deep dive calls ⚓️

### ISSUE THREAD

**Issue by Stebalien** [ipfs/pm#484]
There's been some talk about starting a weekly IPLD deep-dive meeting to discuss making applications on-top-of IPLD and everything related to that such as PubSub, CRDTs, and possibly IPRS.

Maybe better to call it a "specs" meeting (or IPLD research?)

The Monday 17:00 time didn't appear popular so let's try to pick one here (and flesh out what we plan to talk about).

**Comment by Stebalien** [comment]
@nicola, @lgierth, @hermanjunge, @Kubuxu, @diasdavid

**Comment by Kubuxu** [comment]
As a note, we decided top use UTC time for most communication. I can understand 10am here from context but otherwise it would be hard.

**Comment by Stebalien** [comment]
Sorry, I'm not quite used to that yet...

**Comment by Stebalien** [comment]
Also, @pgte.

**Comment by diasdavid** [comment]
@wanderer and @kumavis have been working with and creating a lot of stuff with IPLD too.

In order to make these discussions productive, I believe there is a couple of verticals we have to tackle and we probably should focus on a couple at a time. The ones I have in mind are:

- IPLD Transformations
- IPLD Selectors
- IPLD Sharding
- IPRS on top of IPLD
- Use IPLD for PubSub (currently it uses its own protobufs)
- Use IPLD for IPNS

**Comment by wanderer** [comment]
@diasdavid would love to join! Lets set a time.

**Comment by wanderer** [comment]
@diasdavid would this next week work?

**Comment by diasdavid** [comment]
What about right after the all hands, meaning -> 5pm UTC?
https://github.com/ipfs/pm/issues/486

**Comment by hermanjunge** [comment]
Can't do, @diasdavid  I have something at the 1730 spot every week.

**Comment by Stebalien** [comment]
@vyzo will probably be interested as well.

**Comment by diasdavid** [comment]
# Here is a [doodle](https://ineffable.doodle.com/poll/7b7frrx4fu7p66rd)

**Comment by wanderer** [comment]
doodle filled!

**Comment by wanderer** [comment]
tomorrow at 10:00 AM – 11:00 AM west coast time looks promising

**Comment by jon-choi** [comment]
I'd love to join in as well.

**Comment by dryajov** [comment]
filled the doodle, I'd love to join as well.

**Comment by diasdavid** [comment]
# Thursday 3pm UTC

Confirm by 👍 this comment

**Comment by diasdavid** [comment]
![image](https://user-images.githubusercontent.com/1211152/29570979-f097dd0c-874f-11e7-8a93-2f84ad016b22.png)

Sounds like we have a call!

If you added the [IPFS Calendar](https://github.com/ipfs/pm#schedule) to your calendar, you should now have:

![image](https://user-images.githubusercontent.com/1211152/29571078-292b8b78-8750-11e7-802e-fffdb3b13d6a.png)

(note, I'm on Lisbon timezone, it will be a different time for you according to the timezone)

**Comment by diasdavid** [comment]
# IPLD deep dive call August 24

- [Zoom](https://zoom.us/j/779-351-365)
- [Notes](https://cryptpad.fr/pad/#/1/edit/OQ-51UugnXcv1Y+ABC9Hqw/c3dFDxScQNPdni9l-MaH1CVm/)

**we need items for the agenda**

**Comment by hermanjunge** [comment]
Up to now, I've been playing this from ear, because I wanted to get as much as the big picture as I could, diminishing the noisy questions.

### So this is my coordination _wishlist_.

* API and Interfaces (i.e. `Resolve()`, `ResolveLink()`, `Tree)=`, `Links()`, etc).
* Dag API (`--format` ? `--input-enc` ? `--mhtype` ? etc)
* My default output is `JSONMarshal()`, what happens if the user wants the raw contents? My current hack is getting the `cid`, and `ipfs block get <cid>`.
* Roadmap of the overall project.
* Each project to report status, and personal roadmap.

**Comment by diasdavid** [comment]
Thank you for bringing those points up, that reminds me that I should share some reading material for everyone so that we save time.

- (Really important) https://github.com/ipfs/interface-ipfs-core/issues/81 
- https://github.com/ipfs/interface-ipfs-core/issues/125
- https://github.com/ipfs/interface-ipfs-core/issues/121
- https://github.com/ipld/interface-ipld-format
- https://github.com/ipld/interface-ipld-format/issues/4
- https://github.com/ipfs/js-ipfs-api/pull/534

Please thumbs up this comment after you read it.

**Comment by magik6k** [comment]
I'd also want to discuss:
* https://github.com/ipld/interface-ipld-format/issues/9

**Comment by Stebalien** [comment]
I'd like people to peruse https://github.com/ipfs/notes/issues/255 when they get a chance. It still needs lots of work but it's getting there.

**Comment by hermanjunge** [comment]
Please. to the notetaker, these elements to be added in the notes. Couldn't manage to use the notepad properly.

```
  - Implemented some ethereum types in the go-ipld-eth plugin
    - Particularly block, tx and tx-trie.
    - We can traverse the transaction trie, as resolving concerns.
    - Next up is implementing the ethereum state trie nodes.
    - But first want to import the whole ethereum blockchain into a number of IPFS servers (7).
      - Working on that ^, we are talking of 4MM blocks or 250GB data,
      - The goal is to have real light clients operating with all the storage referenced via IPFS. 
  - Want to look at the IPLD roadmap:
      - Help with the interfaces,
      - and implement properly in go-ipld-eth.
      - this work could be useful to import further blockchains into IPLD.
  - Current Challenges:
    - Import the blockchain (mostly database / trie parsing)
    - Implement all ethereum types in go for IPLD.
    - Understanding bitswap, as we need to make this elements available.
    - Optimize resolving: Today to get an ETH address state, you need to perform at least 8 resolve requests.
    - ^^  Too I/O Expensive.
  - Future challenges
    - Figure out a way to have a canonical hash table working.
    - ^^ IPNS to tell us which is the last block number and its hash.```

**Comment by jon-choi** [comment]
Sorry couldn't make it. Thanks for taking [excellent notes](https://cryptpad.fr/code/#/1/edit/jzXPvsTxja1ip2aZ-3Hwlg/WrKiUcdeIim78td5OjL24Nwm/) (new link since one above "redirects")

**Comment by diasdavid** [comment]
Opened a PR for the notes - https://github.com/ipfs/pm/pull/489

**Comment by diasdavid** [comment]
## `interface-ipld-format` spec update

As discussed during the call, there were several proposals to update the spec for IPLD formats. I've coalesced all of them and opened a PR with that update here: https://github.com/ipld/interface-ipld-format/pull/11

This will fix a bug, a perf issue and also add the features you were looking for. I appreciate review before I go and change 10 format implementations. Thanks!

**Comment by diasdavid** [comment]
[**Uploading the call (part I managed to record) here**](https://www.youtube.com/watch?v=103DT-im1_M&feature=youtu.be)

**Comment by diasdavid** [comment]
I went through all `ipfs/notes` issues and tagged all the ones IPLD related, you can now find them easily through this url https://github.com/ipfs/notes/issues?q=is%3Aopen+is%3Aissue+label%3Aipld

There is a lot of cool ideas that have been in the back of our heads for a while, it is super important to revisit and refresh our memories :)

**Comment by jon-choi** [comment]
Can we also have the calendar event be on 'labs-events-meetings'? or is that calendar separate?

**Comment by diasdavid** [comment]
@jon-choi we use the `ipfs-community` calendar for IPFS Community related events -- https://github.com/ipfs/community#calendar

**Comment by diasdavid** [comment]
# IPLD deep dive call August 31

- [Zoom](https://zoom.us/j/779-351-365)
- [Notes](https://cryptpad.fr/code/#/1/edit/ElFC3MpQMAgbBSFNx8zLJA/EH2SkOKuopUcZiMOzHJfTksy/)

Tasks:
- [ ] We need a moderator
- [ ] We need a notetaker
- [ ] We need an agenda

**Comment by jon-choi** [comment]
PR for notes https://github.com/ipfs/pm/pull/497

**Comment by diasdavid** [comment]
> I know this comes late (need to automate it) but hopefully everyone subscribed to the calendar by now.

![image](https://user-images.githubusercontent.com/1211152/30170152-3a4c4cf6-93e6-11e7-820a-cbd6aae98b8f.png)

# IPLD deep dive call September 7 

- [Zoom](https://zoom.us/j/9816662617)
- [Notes](https://cryptpad.fr/code/#/1/edit/izI3ZpFe4LkD9Se6bMkw2g/YanuF-dYiIIXW6LCVTfB--gP/)

**Comment by diasdavid** [comment]
# IPLD deep dive call August 24

- [Zoom](https://zoom.us/j/779-351-365)
- [Notes](https://cryptpad.fr/code/#/1/edit/V7u91kNs8KVvqfs6OnHqvw/YFqCdDVbUsNOP5WZdt6Vay0l/)

**Comment by diasdavid** [comment]
Can I get a thumbs up on https://github.com/ipfs/pm/issues/484#issuecomment-327837047 by the folks planning on coming to the next call? Thank you :)

**Comment by Stebalien** [comment]
So, due to lack of agenda items, we've decided to put this meeting on an as-needed schedule. If you have something you want to discuss, post it here (although please refrain from *discussing* it here, probably best to make an issue and link to it). If all linked issues aren't resolved by the time the meeting time rolls around, we'll hold the meeting to discuss them.

---

To propose a topic, post an agenda item in the form:

[ ] #XXX - title
[ ] Short topic, no issue.

As we finish discussing each item (either during the meeting or offline), we'll check them off.
If there are unchecked items by 4AM UTC on Thursday, we'll hold the meeting at 4PM UTC to discuss them.

---

Does this work for everyone?

**Comment by diasdavid** [comment]
This is currently not happening, reopen if the calls restart.

**Comment by daviddias** [comment]
Hi everyone! The IPLD Team now has a active BiWeekly Sync, check all the info at https://github.com/ipld/team-mgmt#bi-weekly-call
