### ISSUE TITLE
⚗️ Bitswap Strategy Research Weekly Call

### ISSUE THREAD

**Issue by dgrisham** [ipfs/pm#500]
Hi everyone,

This is an echo of information posted in the [Bitswap research repo](https://github.com/ipfs/research-bitswap). There is some work going on regarding Bitswap strategies, in particular:

1. **Mathematical modeling of Bitswap.** The current direction involves game theory, though the particular branch is in flux at the moment. You can see an overview of what's been explored in [this issue](https://github.com/ipfs/research-bitswap/issues/2). Discussion on this is being explored primarily between @miyazono and me at the moment, and past discussions have been between @jbenet and me.
2. **Simulations of Bitswap strategies.** This involves a round-robin queue implementation in Bitswap that's currently [in the works](https://github.com/ipfs/go-ipfs/pull/3982), as well as relevant updates to [kubernetes-ipfs](https://github.com/ipfs/kubernetes-ipfs/) to support features for testing Bitswap and how various strategies perform.

If you're interested in any of this, join our weekly call! It's currently **Tuesdays at 10 pm UTC** -- however, if anyone's interested in this and can't make that time, we can always work out a new time. The call currently between myself and @miyazono. We primarily discuss the mathematical modeling side of Bitswap at the moment -- and note that neither of us are, by any means, experts in game theory, so don't feel discouraged by the topic :)

Reply to this thread if you're interested in attending these calls or otherwise discussing Bitswap strategies!

**Comment by hsanjuan** [comment]
@lgierth could you add these meetings to the ipfs-community calendar? I don't have such power it seems.

**Comment by lgierth** [comment]
Okay added -- would be good to figure out how to fix the permissions there

**Comment by diasdavid** [comment]
subscribing :)

**Comment by dgrisham** [comment]
**Update**: This call will take place immediately after the IPFS all-hands call today.

**Comment by Admin-DataRoads** [comment]
Are these calls still happening? I just tried to join the call listed on the community calendar today (1/15 MLK holiday) right after the all hands call, just as a first time listener, and no one is there. Are they intended to be on Tuesdays and listed on Monday as a mistake?

**Comment by dgrisham** [comment]
Hey @Admin-DataRoads, you have the day/time correct, we've just been slow getting back on these since the holidays due to slim availability of the regular attendees. We'll be on it next week though, so feel free to come by and listen in!

**Comment by dgrisham** [comment]
@Admin-DataRoads new call time has been scheduled, this call will be combined with the general PL research call https://github.com/ipfs/research-bitswap/issues/3#issuecomment-359992205

**Comment by diasdavid** [comment]
This is not happening. Reopen if it starts again.
