### ISSUE TITLE
Cancel call for 25 Sept and do a big roadmapping call on 02 Oct

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#502]
On this week's All-Hands, we discussed **cancelling next week's call (25 Sept)** and then doing a big call the following on 02 Oct, focused on IPFS roadmapping.

If nobody objects by the end of day on Wednesday 20 Sept, we will proceed with that plan.

**Comment by llopv** [comment]
Hey guys,

Are you aware that **Spanish government is blocking gateway.ipfs.io** at a DNS level? There is a lot of new IPFS gateways rising in Catalonia right now, such as https://catalonia.network and https://ipfs.infura.io/ .

**Comment by atfornes** [comment]
thanks @llopv for sharing. Should we create a new issue to find a strategy to denounce this attack to freedom of speech?

**Comment by llopv** [comment]
Just to add some more information, that's all about the Catalonia's Referendum of Independence that is programmed for this 1st October.

https://www.express.co.uk/news/world/854281/wikipedia-julian-assange-catalonia-referendum-censorship-protect-spain
