### ISSUE TITLE
Choose language around "teams" vs. "working groups", etc.

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#513]
Over the remainder of Q4 we want to work on forming explicit teams and/or working groups who deal with the various responsibilities around IPFS, libp2p, etc. 

### What we want to achieve
- Increase clarity about which responsibilities are handled by which groups of people, how to follow their work, when to get involved in those groups, how to contribute, etc.
- Provide guidelines for those groups to declare their objectives and communicate their work plans
- Reduce bottlenecks and mitigate bus factor
- Gradually build even more inclusive patterns around governing IPFS, libp2p, IPLD, multiformats, etc.

### What we know
- There are already groups of people who coordinate to handle certain responsibilities. This is done somewhat informally for many areas of work.
- Some explicit teams have already formed who focus on specific code bases (ie. ipfs-cluster team)
- Some ongoing responsibilities are currently assigned to an individual but need to be shared by multiple people (reduce bottlenecks, mitigate the bus factor, etc.)

### What's not clear yet (undecided)
- How do we allow shared responsibility and inclusive decision making without drowning ourselves in design by committee?
- Should we form Working Groups? Teams? What's the difference between a Working Group and a Team?

# Question: What do we call these groups of people? Working Groups? Teams? What is the difference?

Please comment.

**Comment by hsanjuan** [comment]
Teams sounds good to me

**Comment by flyingzumwalt** [comment]
For me, "Working Group" fits better with situations where people from different organizations might participate. It also fits better when applied to an ongoing topic or area of concerns rather than a specific, discrete project. By contrast, "Team " fits better when you're pointing to the people who are responsible for a particular Project or Product. 

Things that sound more like working groups to me:

- go-ipfs releases 
- js-ipfs releases 
- security 
- infrastructure 
- Education and Documentation
- Steering
- Dynamic Data
- Large Volumes

Things that sound more like projects or products to me (which might have _teams_ associated with them):

- IPFS in Web Browsers
- ipfs-cluster
- Data Together
- Giant Files Initiative

**Comment by flyingzumwalt** [comment]
(I'm not proposing that we use _both_ "team" and "working group" -- I'm just trying to draw out distinctions between the way the two terms work so we can come up with clear language and clear definitions)

**Comment by diasdavid** [comment]
During last week discussions, we found a language that feels descriptive and not too verbose on how to define and describe these working groups.

Let's continue this convo on the PR https://github.com/ipfs/ipfs/pull/285 and update it asap so that is available for the whole community.
