### ISSUE TITLE
Define User Journeys for Offline Editing of content

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#514]
Define User Journeys that describe the overall motivations, user experience, and actions for an application developer who is using IPFS and libp2p to develop offline-first applications and/or applications with native support for collaborative Offline Editing of content.

**Comment by diasdavid** [comment]
The `In Web Browsers` Working Groups is doing work on this front with https://github.com/ipfs-shipyard/pm-ipfs-gui/issues/6

**Comment by meiqimichelle** [comment]
@flyingzumwalt is this still a priority? It isn't reflected in our latest UX planning documents, and so is not reflected in my planning for near-term user research (although I will be connecting with @olizilla later on IPFS-gui-land, not sure what that team is focused on right now).

**Comment by diasdavid** [comment]
@meiqimichelle would the `User Research` repo be a better location for this issue? I believe it is a bit lost here.

**Comment by diasdavid** [comment]
@meiqimichelle closing this one here. Please reopen on the user-research repo if you find it still valid or want to reboot it
