### ISSUE TITLE
Define a User Journey for collective management of large volumes of data

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#515]
Define at least one User Journey that describes the overall motivations, user experience, and actions for a group of people who are using IPFS to collectively manage large volumes of data. Example: EDGI using Data Together, Libraries managing pinsets as collection content, Federal Agencies publishing open datasets, etc.  This also relates to the Giant Files Initiative and ipfs-cluster, which should both get their own sets of user journeys.

**Comment by flyingzumwalt** [comment]
@mishmosh as I head into the [datatogether meeting](https://github.com/datatogether/datatogether/issues/26) later this week, do you have any suggestions of how to approach gathering info for these User Journeys?

**Comment by mishmosh** [comment]
Some key principles:

- Build from the user's point of view, not an IPFS systems point of view.
- 4 major phases in creating a journey map:
   1. Make the rough outline - offer participants a skeleton
   2. Invite contributions - from past research, from current users, etc. Show an example if participants haven't contributed before.
   3. Layer in ways to visualize highs and lows. Examples: "Motivations" and "Barriers" sections,  "Pain/Happiness" scores.
   4. Now, visually design it to show overarching patterns while preserving granular details. Choose the visual styles and information architecture that will be most effective for your audience.

Even if we later identify individuals to lead this work, it will still be valuable to source Steps 1 and 2 as directly from the community and contributors as possible. Depending on how this week's Data Together meeting is run, you could have each location create their own version, and share.

**Comment by patcon** [comment]
Possible user journey candidates

- academic research groups who care about and use specific gov data, and are worried about keeping it accessible (no specific names, but i believe ppl would often drop into edgi slack from this group)
- industry (particularly insurance and finance) who who care about and use specific gov data (cc @mylesb could you rep or connect ppl with folks from this group?)

**Comment by meiqimichelle** [comment]
I believe this is being tracked here (and issues that will fall out of that larger task): https://github.com/ipfs/user-research/blob/master/large-volumes/README.md

@flyingzumwalt if that seems right to you, perhaps close this issue?
