### ISSUE TITLE
Wishlist: Provide checksum files for IPFS distributions.

### ISSUE THREAD

**Issue by icefoxen** [ipfs/pm#518]
Don't know where else to open this issue, sorry.  :-)

I'm writing some infrastructure to deploy IPFS automatically to servers and it would be nice to have checksums for the various tarballs available as files that could be downloaded.

Of course it would be *really* nice to have .deb or .rpm packages, but that's a step beyond...

**Comment by lgierth** [comment]
Yeah this would be good to have! Could you move this to https://github.com/ipfs/distributions

**Comment by icefoxen** [comment]
Done, thank you.  :-)
