### ISSUE TITLE
Change messaging around sprint discussion spectating

### ISSUE THREAD

**Issue by emazurek** [ipfs/pm#530]
Specifically, this paragraph in the readme: "If you are interested in watching, but do not plan on participating, please use the stream link provided by the discussion lead and watch on YouTube. This is because video quality is generally better for everyone with less participants on the hangout."

It's my understanding that there's no YouTube stream link anymore. How can us noobs participate without clogging the Zoom stream?

**Comment by lgierth** [comment]
Thanks for fixing it in #534!
