### ISSUE TITLE
Re-Sync Bot

### ISSUE THREAD

**Issue by dgrisham** [ipfs/pm#542]
The bot that sets the all-hands call issues got confused a bit over a month ago, when @forrestweston was edited in as the lead for the call. He's not listed as one of the rotating facilitators/notetakers on the README, so the bot broke -- see [this comment](https://github.com/ipfs/node-github-issue-bot/issues/12#issuecomment-356055946) for more description on that.

Somehow, the bot has to be re-synced. In order to continue as normal from the last time it worked correctly, I'm pretty sure the state should be set to:

- Lead: @victorbjelkholm
- Notetaker: @whyrusleeping

**Edit**: Also, note that adding @forrestweston to the list will **not fix the issue at this point**, because the bot looks to the previous week's lead to determine the next, and the previous week's lead is now set to @ipfs-helper.

**Comment by VictorBjelkholm** [comment]
@dgrisham ah, so next all-hands issue that gets open, we apply me and @whyrusleeping as lead/notetaker and then the next issue, will have lead/notetaker correctly set?

**Comment by dgrisham** [comment]
@VictorBjelkholm Yep, that should do it -- guess I didn't state the clearly in the OP haha.
