### ISSUE TITLE
Proposal: reduce IPFS All Hands call to 30 minutes

### ISSUE THREAD

**Issue by diasdavid** [ipfs/pm#548]
The IPFS All Hands has evolved organically from its original format as the IPFS Dev Team sync up to an IPFS Community call and status updates. We want to continue to have the call as a venue for the community to meet weekly, however, I believe that we can now **reduce the length of it to 30 minutes.**

The call happens to run short for the majority of the days, but since it is always on the calendar, it blocks other folks from scheduling calls for the second half of it. The call happens on **prime time** (time that is friendly for almost the timezones where the majority of our contributors are present), making it extremely valuable and a waste if not used correctly, especially since it happens right in the beginning of the week. 

Also, with the future crystallization of the [IPFS Working Groups](https://github.com/ipfs/ipfs/pull/285), I expect that more working groups will benefit from having more slots available to sync up Monday.

**Comment by flyingzumwalt** [comment]
As raised by @forrestweston on the all hands -- we should also re-work how we source and present Demos. Rather than letting them happen informally in the all hands (and maybe not having time for them) there should be some way to propose a demo, let everyone know when it's going to happen, and possibly conduct it at a time other than the all-hands.

**Comment by lidel** [comment]
Switching to pre-recorded demos is another way to go about reducing All Hands time and improving "linkability" of demos themselves (right now we point at specific time in a call). 

Here are examples of fantastic, ~3min recordings by @alanshaw about WIP on IPFS Companion: 
(i) [ipfs in brave ftw](https://www.youtube.com/watch?v=2cmbm6iABsI), (ii) [window.ipfs access control in IPFS companion](https://www.youtube.com/watch?v=aXLERp9-Mis)

I am not sure how to do proper All Hands Q&A with that approach tho. 
Were there any prior experiments with pre-recorded demos?

It may not be realistic to assume everybody will have enough time to watch demo if it is added to the agenda just before or during the call. Perhaps  every week we could have Q&A related to last week's Demos, and after that there would be an Action Item to watch new demos for next week's Q&A?

**Comment by dryajov** [comment]
> Switching to pre-recorded demos is another way to go about reducing All Hands time and improving "linkability" of demos themselves (right now we point at specific time in a call).

I like this approach.

>  Perhaps every week we could have Q&A related to last week's Demos, and after that there would be an Action Item to watch new demos for next week's Q&A?

IMHO, this makes the most sense 👍

**Comment by diasdavid** [comment]
> Were there any prior experiments with pre-recorded demos during All Hands?

Yes, multiple even, but it turned out that stopping the call to watch a demo video is not an ideal flow.

> Switching to pre-recorded demos is another way to go about reducing All Hands time and improving "linkability" of demos themselves (right now we point at specific time in a call).

I don't necessarily believe that we should be asking folks to record a video "if they want to share a demo", giving a demo is already challenging and having to record a video is a whole new level. There is something very comforting about getting feedback as you present.

I also do not think that by shorting the call down to 30 minutes that we are going to run out of time for demos. We had many 30 minute calls with more than one demo. 

I've opened a PR with a refresh to the repo docs in preparation for the time change, check it here: https://github.com/ipfs/pm/pull/553

**Comment by flyingzumwalt** [comment]
Observations: 
- need to have the moderator & notetaker auto-assigned in advance of the call, with some confidence that the moderator and notetaker will actually be on the call & prepared to fill that role -- currently we waste 5 minutes twisting arms because sprint-helper is broken
- we won't be able to fit both discussion and demos in 30 minutes. In the past few weeks we've gotten through the discussions but no demos by the 30 minute mark. Possibly plan for that -- 30 minute call followed by optional demos if there are any demos.

**Comment by flyingzumwalt** [comment]
also - to move this forward, I recommend time-boxing it. Give people a window of time to agree/disagree and a clear way for them to express their agreement or disagreement. You could potentially use loomio if you want an extra layer of explicit "there's a decision being made and people have all agreed"

**Comment by Admin-DataRoads** [comment]
Some more suggestions I would also characterize as "Weekly Call Evolution" came up in the last call 2/12, so I'll quickly comment on those call action-items here.

https://hackmd.io/MYTgLGBsDMDsCMBaKAmAJsgDAI1o78YwisImArGvCgIZQ3lA?view

* Monday "morning" All-Hands calls have definite value to project cohesion, with disparate teams starting the week seeing each other -- especially now that projects are being spread out between LibP2P, IPLD, and IPFS repositories and their various sub-projects. I would argue for retaining this call, and perhaps moving Demos and new-interest questions to another new "New Items of Interest" style conference later in the week.

* We've all experienced demonstration-death by executing it live, and fixes or recovery take precious call time, so I want to reiterate sticking exclusively to pre-recorded Demos for all these calls, if only to avoid further complications from conferencing video system issues.

**Comment by diasdavid** [comment]
This got stale and yet we still have calls that do not make the best use of our time. I'm changing the call to 45 minutes and see how everyone feels about that :)

**Comment by diasdavid** [comment]
Now that we are at 45 mins, how do people feel? Shall we take the next step and go 30 minutes?

**Comment by flyingzumwalt** [comment]
Here's my proposal for re-formatting the calls as a 30-minute call that will also spend the time more effectively. https://github.com/ipfs/pm/issues/636

**Comment by diasdavid** [comment]
Thank you for your proposal on #636, @flyingzumwalt. I went ahead and made the call only 30 minutes which was already a wish. Now we just have to try the new format.

<img width="302" alt="image" src="https://user-images.githubusercontent.com/1211152/42126136-9d5dd36e-7c7a-11e8-9c50-679dca6f3e28.png">
