### ISSUE TITLE
Can working group captains use the protocol zoom account?

### ISSUE THREAD

**Issue by olizilla** [ipfs/pm#554]
In conversation with @flyingzumwalt and @lidel today, we realised it would be useful for working group captains to be able to set up zoom calls on a pro account. plz can has?

**Comment by olizilla** [comment]
cc @diasdavid

**Comment by diasdavid** [comment]
Added @lidel. Will be adding @olizilla and @alanshaw too as soon as we get more Zoom accounts on our subscription :) Will add the other WG Captains as well.

**Comment by diasdavid** [comment]
Ok, everyone has an account now :)

**Comment by diasdavid** [comment]
![image](https://user-images.githubusercontent.com/1211152/35537871-aa09b822-0500-11e8-9182-bdaa0ed37877.png)
