### ISSUE TITLE
Give working group captains edit powers on the ipfs community calendar

### ISSUE THREAD

**Issue by olizilla** [ipfs/pm#555]
A working group captain is may reasonably want to schedule a call with their fellow working groupers. Can it be calendar'd?

cc: @flyingzumwalt @diasdavid

**Comment by diasdavid** [comment]
💯 

You will need an @ipfs.io email addr first. @lgierth can you get that set up?

**Comment by lgierth** [comment]
Working on getting super-admin for non-juans

**Comment by flyingzumwalt** [comment]
FYI -- I still don't have edit permissions on that calendar, despite having an ipfs.io address for over a year. I think I've submitted a few GH issues requesting access over the year but it was never clear who has the power to grant those edit permissions.

**Comment by lgierth** [comment]
> I still don't have edit permissions on that calendar, despite having an ipfs.io address for over a year

Fixed

**Comment by diasdavid** [comment]
@lgierth is this all done?

**Comment by lgierth** [comment]
No - still no super-admin. Juan needs to clear out his old emails there

**Comment by lidel** [comment]
Hey, any update on this?
We really don't want to bother David/Matt every time WG needs to move weekly sync to a different hour :upside_down_face:

**Comment by mikeal** [comment]
+1, I'll need to add a meeting for the Community WG soon :)

**Comment by lgierth** [comment]
Same situation -- if someone (maybe close to Rivendell) would like to work on this with Juan, please go for it :)

**Comment by diasdavid** [comment]
Seems that we might have a solution for this issue now, see:

<img width="611" alt="image" src="https://user-images.githubusercontent.com/1211152/46171534-7ac82a00-c2a9-11e8-9574-ac5adc6983a3.png">

@olizilla @lidel, gave you new permissions to make changes to the calendar, try to give it a spin and report back, please :) Thank you!

**Comment by lidel** [comment]
@diasdavid I was able to move GUI/WB Sync as noted in https://github.com/ipfs/in-web-browsers/issues/106, I also added @olizilla  to it, looks like it works as expected, thanks! :)

**Comment by diasdavid** [comment]
Woot! IT WORKS \o/
