### ISSUE TITLE
Enter Mid-Quarter OKR Scores

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#566]
If you are the owner of any KRs, enter your mid-quarter scores in the [IPFS+libp2p OKRs sheet](https://docs.google.com/spreadsheets/d/1clB-W489rJpbOEs2Q7Q2Jf1WMXHQxXgccBcUJS9QTiI/edit#gid=534051604) by Wednesday 14 February.  If you have questions, ask @flyingzumwalt or @diasdavid for help.

Some of the People who need to enter scores:

- [ ] @jbenet 
- [x] @diasdavid 
- [x] @flyingzumwalt
- [ ] @whyrusleeping 
- [x] @lidel 
- [x] @olizilla 
- [ ] @VictorBjelkholm 
- [ ] @lgierth 
- [x] @hsanjuan 
- [x] @ZenGround0 
- [ ] @Stebalien 
- [ ] @vyzo 
- [ ] @kyledrake 
- [ ] @hacdias

**Comment by flyingzumwalt** [comment]
I've made all of the working group captains assignees on this issue. You're each responsible for making sure your WG's OKR scores are entered on time.

**Comment by vyzo** [comment]
i am not sure what i need to do here -- i don't seem to own any of these KRs.

**Comment by flyingzumwalt** [comment]
@vyzo you are listed as the owner of 2 KRs in the go-ipfs sheet. Maybe @whyrusleeping forgot to tell you.

**Comment by vyzo** [comment]
ooh there are multiple sheets! ok, i see it now.

**Comment by vyzo** [comment]
need permissions to edit the spreadsheet...

**Comment by vyzo** [comment]
@flyingzumwalt ping -- i don't have permissions to edit the spreadsheet.

**Comment by diasdavid** [comment]
Closing as this was done :)
