### ISSUE TITLE
Remove video links from the readme 

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#57]
They die, and we don't use them. We should link people instead to IRC where the new videos will be dropped. 

Should specify that project leads should update it in the agenda before hand? Or is that too much effort?

**Comment by Dignifiedquire** [comment]
I used it for apps hangout today and it worked fine

**Comment by RichardLitt** [comment]
Cool. There's still an issue, though: @lgierth didn't for Infrastructure, as it goes down sometimes and it's easier to just post in IRC. We should be consistent.

**Comment by lgierth** [comment]
Yeah other hangouts keep disappearing too. They just aren't permanent.

**Comment by Dignifiedquire** [comment]
Then probably drop the links and a note about how to create a hangout and that the links will be posted in IRC

**Comment by jbenet** [comment]
:+1: agreed

**Comment by jbenet** [comment]
- when making hangouts pls use https://hangouts.google.com/start
