### ISSUE TITLE
Feb 21 4pm UTC - Test the Zoom Webinar for IPFS Calls

### ISSUE THREAD

**Issue by diasdavid** [ipfs/pm#571]
Following up https://github.com/ipfs/pm/issues/564, here is the issue to track the testing of the Webinar option for Zoom.

I'm proposing Feb 21 4pm UTC to test this. Let me know if you really want to be part of the test session and if this time doesn't work for you.

We want to test:

- Experience with enabling people to participate (adding/removing panelists)
- Check if people that are not the hosts can open the Webinar (from docs seems like they won't be, let's see)
- Youtube livestreaming

I'll set up the Webinar. For everyone else, please read the documentation on Zoom https://zoom.us/webinar 

//cc @jaycarpenter @lgierth @flyingzumwalt @dryajov

**Comment by dryajov** [comment]
I'll be there.

**Comment by lgierth** [comment]
Great I'll be there.

**Comment by JayCarpenter** [comment]
I'll be there as well.

**Comment by diasdavid** [comment]
I've shared a doc with you @dryajov @lgierth and @JayCarpenter, let me know if you have questions.

**Comment by diasdavid** [comment]
I might have found the holy grail, will report soon:

<img width="993" alt="image" src="https://user-images.githubusercontent.com/1211152/37722505-6bd152de-2ce9-11e8-9d6f-21c22a9076d7.png">

**Comment by diasdavid** [comment]
YEEEASSS

<img width="493" alt="image" src="https://user-images.githubusercontent.com/1211152/37723043-9f998090-2cea-11e8-9d4d-d5b7d5aebbc1.png">

Now anyone with Ops-Zoom Account can video stream the call if they also are an owner of the IPFS Channel on Youtube!

**Comment by diasdavid** [comment]
One more thing! I was able to set up a key for all the calls, so now live stream should be possible with just one click!

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/1211152/38469109-8820f5b6-3b8a-11e8-8e1d-c57f3df6b6ff.png">

**Comment by diasdavid** [comment]
IT WORKS! \o/

**Comment by diasdavid** [comment]
Today it was the first call where we did a Zoom Meeting Live Stream and it worked really nicely 

Future Stream URL - https://www.youtube.com/c/IPFS-dweb/live
