### ISSUE TITLE
Monday Call: March 12

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#584]
(@ipfs-helper failed to add it, so I added it manually)

_For information about these calls and how they work, read [the ipfs/pm README](https://github.com/ipfs/pm)._

[Calendar](https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com)

Zoom and Stream links will be updated directly before the calls. Links to them will also be dropped in IRC, at the start of each call. If the link below seems to link to this issue, the link has not been updated yet.

### Monday

Endeavour      | Lead            | Notetaker | Time (PST - UTC - CET) | Pad
:------------: | :-------------: | :-------: | :--------------------: | :----:
All Hands Call | @ipfs-helper   | TBD | 9:00 **16:00** 18:00  | [agenda and notes](https://hackmd.io/-x80pn3FRjq3P7JJWoRhdQ#)

Please add any agenda items you have to the pad before the project-specific sprint call starts.

**Comment by diasdavid** [comment]
Seems that @ipfs-helper is not generating from the right template. The calls have been 5pm UTC for a while (which gives us a bit more sanity), see:

![image](https://user-images.githubusercontent.com/1211152/37296456-f4b36fac-2612-11e8-82a5-96c6fb17de6e.png)

https://github.com/ipfs/pm/#weekly-all-hands

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/1211152/37296468-f9f9e7e8-2612-11e8-8103-37b7987fff62.png">

**Comment by flyingzumwalt** [comment]
It's not the helper that's broken. Daylight savings ended this weekend in the US, so all the americans showed up an hour early. In the past we have updated the calendar to reflect US daylight savings rather than waiting for european daylight savings to kick in.

**Comment by flyingzumwalt** [comment]
...or I guess both are broken. Either way, we'll sort it out on the call.
