### ISSUE TITLE
Monday Call: March 19

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#591]
(@ipfs-helper failed to add it, so I added it manually)

_For information about these calls and how they work, read [the ipfs/pm README](https://github.com/ipfs/pm)._

[Calendar](https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com)

Zoom and Stream links will be updated directly before the calls. Links to them will also be dropped in IRC, at the start of each call. If the link below seems to link to this issue, the link has not been updated yet.

### Monday

Endeavour      | Lead            | Notetaker | Time (PST - UTC - CET) | Pad
:------------: | :-------------: | :-------: | :--------------------: | :----:
All Hands Call | @ipfs-helper   | TBD | 10:00 **17:00** 19:00  | [agenda and notes](https://hackmd.io/hxiGRVupRD-cmuvMPQDZxA#)

Please add any agenda items you have to the pad before the project-specific sprint call starts.

**Comment by Admin-DataRoads** [comment]
I was one of a few who saw this calendar item still at 16:00 UTC this morning, just to see it update to 17:00 UTC after jumping on. I just want to note here that while the calendar link above is defaulting to UTC timezone correctly now, all the call times in later weeks are still appear to be at 16:00 UTC.

**Comment by Admin-DataRoads** [comment]
Nevermind the last comment. It just seems to have taken an hour or so to propagate changes to calendar subscriptions.
