### ISSUE TITLE
Convene a call to align work/plans around Decentralized Data Stewardship

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#594]
_(forked from #592)_

Zoom link: https://protocol.zoom.us/j/721929659
Notes: https://docs.google.com/document/d/1r6lHGGPjdRPkxQ6RU_8rhLqVtX3qwaVECmni6wS-08I/edit?usp=sharing

Goal: 
- share information and align understanding across teams & stakeholders who deal with this topic
- identify how this information can/should inform OKRs for teams

How:
Convene an open call about using IPFS for Decentralized Data Stewardship. Use that time to 
- Share information and align understanding across teams & stakeholders
- Gather reference information that reflects use cases in this area
- Identify who is allocating time and resources to relevant work in the coming months
- Discuss draft OKRs and consider ways to tweak them, tighten them or otherwise improve them.

When:
Ideally by 23 March, definitely by 29 March

Participants: 
_This is an open call. Anyone who is working to use IPFS for Decentralized Data Stewardship is welcome to join._ Some likely participants:
- @flyingzumwalt
- @hsanjuan 
- @ZenGround0 
- @b5 
- maybe @jonnycrunch ?

**Comment by hsanjuan** [comment]
I have more availability next week.

We'll bring the draft OKRs for cluster.

**Comment by flyingzumwalt** [comment]
I'm fine with doing it next week. I'll be at a conference Monday through Wednesday, but I could slip away if we want to do this meeting earlier in the week. @b5 which dates work best for you?

**Comment by b5** [comment]
Thanks for arranging! 

I'm out of commission Monday, Could do afternoon of Tuesday, Anytime Wednesday, 9-12pm & 5pm onward (EST) on Thursday. Friday is a dumpster fire.

**Comment by dcwalk** [comment]
Could you advertise the time/date in Data Together and EDGI slack when this is picked @b5?

**Comment by b5** [comment]
@dcwalk absolutely! 😃

**Comment by ZenGround0** [comment]
Wednesday 9am-12pm works best for me and I'm guessing @hsanjuan too as its the earliest time posted.  Thursday after 5pm also works for me.

**Comment by flyingzumwalt** [comment]
@hsanjuan could you do 5pm EST on Thursday? That's 21:00 UTC.

**Comment by flyingzumwalt** [comment]
Otherwise I could do 11am EST on Wednesday (17:00 UTC)

**Comment by hsanjuan** [comment]
both Thursday and Wednesday options are good for me

**Comment by b5** [comment]
any update on this? I could still do Thursday!

**Comment by flyingzumwalt** [comment]
Zoom link: https://protocol.zoom.us/j/721929659

**Comment by hsanjuan** [comment]
yeah

**Comment by jonnycrunch** [comment]
@flyingzumwalt @b5 yes please include me.  I am very deep into identity now, data governance and video streaming.   When?

**Comment by Mr0grog** [comment]
Ah, this actually did happen 25 days ago, @jonnycrunch. @flyingzumwalt did we get a recording of it saved somewhere?

**Comment by Mr0grog** [comment]
Maybe we should close this issue since the meeting happened?
