### ISSUE TITLE
Sprint E

### ISSUE THREAD

**Issue by jbenet** [ipfs/pm#6]
**Sprint Goals** 

1. Wire protocol + interop with node
2. Make gateways faster / better
3. Perf + Bugfixes

**Sprint Participants** - @jbenet @dylanPowers @whyrusleeping @travisperson @wking @cryptix

**Sprint Deliverables**

- make it easy to work with gateways 
    - [ ] remove docker, init script, auto-rebooting (@jbenet)
    - [ ] cpu + mem profiling on gateways (@whyrusleeping)
    - [ ] change nginx to do fallback (not round robin) (@jbenet)

- perf/bugs:
  - [x] change the memory profiling (@whyrusleeping)
  - [ ] save memory profile + binary to ipfs (@whyrusleeping)
  - [ ] scope out how testing will be done on both webui and api (@travisperson, @jbenet)
  - [ ] https://github.com/ipfs/webui/issues/20 (@travisperson)

- [ ] Specs / scoping out
  - [ ] DHT spec (@jbenet)
  - [ ] Keystore spec (@jbenet)
  - [ ] scoping out how signed binaries + autoupdate will work (@jbenet)

- interop with node
  - [ ] Protocol wire spec (@jbenet)
  - [ ] swapping out the stream muxer (or having multiplex in go) (@jbenet)
  - [x] protocol-stream (@jbenet)
  - [ ] option (or build) to disable encryption for interop with node (@whyrusleeping)

- Community
  - [x] Waffle documentation (@dylanPowers) ipfs/infrastructure#8
  - [x]  Explain the label scheme (@dylanPowers) ipfs/community#10

- [ ] make all adds add to an object representing local state
- [ ] scope out init + daemon sprint (@jbenet)
- [ ] reimplement goprocess without mem leak (@whyrusleeping)
- [ ] Address memory leak (likely culprit is goprocess)
- [ ] json encoding for add (@travisperson)

**Comment by jbenet** [comment]
@wking + @krl -- still need to add things for you this week-- chat briefly on irc?

**Comment by wking** [comment]
On Mon, Apr 27, 2015 at 01:25:46PM -0700, Juan Batiz-Benet wrote:
> @wking + @krl -- still need to add things for you this week…

[ ] organize filesystem node creation and extraction in shell/fsnode
    and core/fsnode, deprecating the existing importer and
    core/coreunix interfaces and migrating the internal use to the new
    interfaces.  I may only get through the addition commands this
    week (WIP in ipfs/go-ipfs#1151.  This is part of a larger push to
    clean up the existing file handling before working on access modes
    (more discussion in ipfs/go-ipfs#846).

I'd like to open an issue to figure out our migration strategy.  Do we
need ‘gofix’ style translators?  Should we be logging runtime
deprecation warnings?  Some folks do some sed-like things with ‘go
fmt’.  Maybe we're just explaining migrations in our release notes?
Anyhow, it would be good to have a plan written up somewhere, but I'm
not sure where that place is.  Ideas?

**Comment by whyrusleeping** [comment]
@wking deprecating importer? in favor of what?

In my perfect awesome world where I wrote all the code and spent lots of time making the interfaces perfect, We would have the importer, with all its knobs and switches on the low end (probably), and `coreunix.Add` being all nice and user friendly on top, and then the `commands.Add` would just call into `coreunix.Add`. 

I guess the further refinement of that idea is that *all* commands are just UX wrappers over the `core*` methods, and the `core*` methods handle a bunch of logic in order to make calls to the low level `importer` style, raw methods.

\<musings ignore=true random=true>
maybe we should rename core -> mantle, and call the lowest level type API commands the core...
\</musings>

Maybe i'm crazy, @jbenet @wking thoughts on this?

**Comment by jbenet** [comment]
@travisperson  for "scope out how testing will be done on both webui and api" if you can propose a system or two i can review it and suggest changes. maybe in: https://github.com/ipfs/webui/issues/38

**Comment by whyrusleeping** [comment]
potential issues to address next sprint:
https://github.com/ipfs/go-ipfs/issues/1082
https://github.com/ipfs/go-ipfs/issues/1050
https://github.com/ipfs/go-ipfs/issues/964
https://github.com/ipfs/go-ipfs/issues/1179
https://github.com/ipfs/go-ipfs/issues/1150

In general, try to do something with ipfs, record difficulties, try and fix them

**Comment by whyrusleeping** [comment]
also, if anyone is looking to poke the webui:
https://github.com/ipfs/webui/issues/41
https://github.com/ipfs/webui/issues/42
https://github.com/ipfs/webui/issues/43
https://github.com/ipfs/webui/issues/38

**Comment by whyrusleeping** [comment]
I would also like to get more testing around ipns and path resolution written, testing various commands with different path syntax (/ipfs/<hash> vs <hash> vs /ipns/<peerid>)

**Comment by whyrusleeping** [comment]
and this https://github.com/jbenet/go-peerstream/issues/5 also needs to get done
