### ISSUE TITLE
Module Lead Maintainers - Sharing the Responsibility over the IPFS module base

### ISSUE THREAD

**Issue by diasdavid** [ipfs/pm#600]
The IPFS project has grown significantly since 2 years ago and the task of maintaining its module base a very large and time consuming task for few individuals. Me and others have voiced concerns about the bottleneck which leads me to feel really strongly that we need a proper structure to share the responsibility, ownership of the multiple modules we currently maintain.

The current situation is:

- Two Tech Leads, @diasdavid and @whyrusleeping, who have full responsibility, right to merge and release over all modules/packages on the js-ipfs and go-ipfs projects, respectively.
- Few maintainers/contributors that cover parts of the module codebase (e.g @pgte for js-ipfs-unixfs, @vmx for all things IPLD, @VictorBjelkholm for aegir and other dev tools, etc).
- There is no clear way to tell explicitly who is the maintainer of what, other than that the Tech Leads are.

**What we would like to be at is:**

- Recognize extraordinary contributions and empower contributors to take even more important role in the project
- Reduce PR review time and Time To Release
- Increase the overall quality of the project
- Help users know who to reach out for help
- Have a clear way to pass on the baton 

**A Lead Maintainer must:**

- Have complete understanding of that piece of the stack (known the code by heart, read all the specs related to it)
- Have contributed to the module before
- Show a great level of rigor and polish in the code that they ship
- Help others in understanding the module
- Proactively improve documentation, tests and examples of the module
- Apply the established Contributing Guidelines to the project and help others do too

**In a tl;dr;, what I'm proposing is:**

- Have a Maintainers Guide to make sure we every lead is on the same page.
- Add a section to the top of each module that identifies the maintainer
- Give merge and release access to maintainers
- Update the packages table on each project (i.e https://github.com/ipfs/js-ipfs#packages and https://github.com/libp2p/js-libp2p#packages) to include a column for maintainer as well.

In addition to this, I also feel it would fit well to list the Working Group in which the module and/or project falls into. So far, we have pretty much labeled every project with [![](https://img.shields.io/badge/project-IPFS-blue.svg?style=flat-square)](http://ipfs.io/), It would be good to have a badge for the working group as well.

**How do other projects do it?**

We should look into other projects do it as well. [Hapi](https://github.com/hapijs) has a good structure and success for running a similar process for the last few years. @sericaia, @geek Hi o/! can I ask you to share with us some of your leanings here?

**Other things to look at**

- http://openopensource.org/

**Comment by sericaia** [comment]
In Hapi we have guidelines that help a lot for starters:
https://github.com/hapijs/contrib/blob/master/Guidelines.md

A code of conduct its also important (and you can also find it in the /contrib folder)

Everything else is similar to what you just mentioned ;)

**Comment by diasdavid** [comment]
The [protocol has been created](https://github.com/ipfs/community/pull/301) and we are in the process of updating every repo.

**Here is the current Status**

| Module | README.md | package.json | Github perms | npm publish perms |
|---------|--------------|--------------|---------------|--------------------|
| **Multiformats** |  |  |  |  |
| https://github.com/multiformats/js-multihash/pull/51  | ✅ | ✅ | ✅ | ✅ |
| https://github.com/multiformats/js-multiaddr/pull/66  | ✅ | ✅ | ✅ | ✅ |
| https://github.com/multiformats/js-multibase/pull/27  | ✅ | ✅ | ✅ | ✅ |
| https://github.com/multiformats/js-multicodec/pull/24 | ✅ | ✅ | ✅ | ✅ |
| https://github.com/multiformats/js-multihashing |  |  |  |  |
| https://github.com/multiformats/js-multihashing-async |  |  |  |  |
| https://github.com/multiformats/js-mafmt |  |  |  |  |
| https://github.com/multiformats/js-multistream-select |  |  |  |  |
| **IPLD** |  |  |  |  |
|  |  |  |  |  |
| https://github.com/ipld/js-ipld/pull/127 | ✅ | ✅ | ✅ | ✅ |
| **libp2p** |  |  |  |  |
| https://github.com/libp2p/js-peer-id |  |  |  |  |
| https://github.com/libp2p/js-peer-info |  |  |  |  |
| https://github.com/libp2p/js-peer-book |  |  |  |  |
| https://github.com/libp2p/js-libp2p-webrtc-star |  |  |  |  |
| https://github.com/libp2p/js-libp2p-websockets |  |  |  |  |
| https://github.com/libp2p/js-libp2p-tcp |  |  |  |  |
| https://github.com/libp2p/js-libp2p-utp |  |  |  |  |
| https://github.com/libp2p/js-libp2p-webrtc-direct |  |  |  |  |
| https://github.com/libp2p/js-libp2p-websocket-star |  |  |  |  |
| https://github.com/libp2p/js-libp2p-websocket-star-rendezvous |  |  |  |  |
| https://github.com/libp2p/js-libp2p-udt |  |  |  |  |
| https://github.com/libp2p/js-libp2p-udp |  |  |  |  |
| https://github.com/libp2p/js-libp2p-identify |  |  |  |  |
| https://github.com/libp2p/js-libp2p-floodsub |  |  |  |  |
| https://github.com/libp2p/js-libp2p-spdy  |  |  |  |  |
| https://github.com/libp2p/js-libp2p-mplex |  |  |  |  |
| https://github.com/libp2p/js-libp2p-mdns |  |  |  |  |
| https://github.com/libp2p/js-libp2p-railing |  |  |  |  |
| https://github.com/libp2p/js-libp2p-ping |  |  |  |  |
| https://github.com/libp2p/js-libp2p-kad-dht |  |  |  |  |
| https://github.com/libp2p/js-libp2p-record |  |  |  |  |
| https://github.com/libp2p/js-libp2p-delegated-content-routing |  |  |  |  |
| https://github.com/libp2p/js-libp2p-delegated-peer-routing |  |  |  |  |
| https://github.com/libp2p/js-iprs-record |  |  |  |  |
| https://github.com/libp2p/js-libp2p-kad-routing |  |  |  |  |
| https://github.com/libp2p/js-libp2p-distributed-record-store |  |  |  |  |
| https://github.com/libp2p/js-libp2p-kad-record-store |  |  |  |  |
| https://github.com/libp2p/js-libp2p-random-walk |  |  |  |  |
| https://github.com/libp2p/js-libp2p-keychain |  |  |  |  |
| https://github.com/libp2p/js-libp2p-circuit |  |  |  |  |
| https://github.com/libp2p/js-libp2p-rendezvous |  |  |  |  |
| https://github.com/libp2p/js-libp2p-half-closed-connection-upgrade |  |  |  |  |
| https://github.com/libp2p/js-libp2p-connection-manager |  |  |  |  |
| https://github.com/libp2p/js-libp2p-crypto-secp256k1/pull/6 | ✅ | ✅ | ✅ | ✅ |
| https://github.com/libp2p/js-libp2p-crypto/pull/119 | ✅ | ✅ | ✅ | ✅ |
| https://github.com/libp2p/js-libp2p-secio/pull/102 | ✅ | ✅ | ✅ | ✅ |
| https://github.com/libp2p/js-libp2p-switch |  |  |  |  |
| https://github.com/libp2p/js-libp2p/pull/190 | ✅ | ✅ | ✅ | ✅ |
| **IPFS** |  |  |  |  |
| https://github.com/ipfs/interface-datastore |  |  |  |  |
| https://github.com/ipfs/js-datastore-core |  |  |  |  |
| https://github.com/ipfs/js-datastore-fs |  |  |  |  |
| https://github.com/ipfs/js-datastore-s3 |  |  |  |  |
| https://github.com/ipfs/js-datastore-level |  |  |  |  |
|https://github.com/ipfs/interface-pull-blob-store  |  |  |  |  |
| https://github.com/ipfs/js-fs-pull-blob-store |  |  |  |  |
| https://github.com/ipfs/js-idb-pull-blob-store |  |  |  |  |
| https://github.com/ipfs/js-level-pull-blob-store |  |  |  |  |
| https://github.com/ipfs/js-ipfs-unixfs-engine |  |  |  |  |
| https://github.com/ipfs/js-ipfs-unixfs  |  |  |  |  |
| https://github.com/ipfs/js-ipfs-mfs |  |  |  |  |
| https://github.com/ipfs/js-ipfs-repo |  |  |  |  |
| https://github.com/ipfs/js-ipfs-block-service |  |  |  |  |
| https://github.com/ipfs/js-ipfs-block |  |  |  |  |
| https://github.com/ipfs/js-ipfs-bitswap |  |  |  |  |
| https://github.com/ipfs/aegir/pull/220 | ✅ | ✅ | ✅ | ✅ |
| https://github.com/ipfs/js-ipfsd-ctl |  |  |  |  |
| https://github.com/ipfs/interface-ipfs-core |  |  |  |  |
| https://github.com/ipfs/js-ipfs-api |  |  |  |  |
| https://github.com/ipfs/js-ipfs |  |  |  |  |

**Comment by vmx** [comment]
In case you follow the Standard Readme, these scripts might help for adding the Lead Maintainer: https://gist.github.com/vmx/6ff564e93cf7c0a77866a4bcda19fdf5

**Comment by vmx** [comment]
@diasdavid Should the Tech Lead also have permissions to publish a module on npm? It's not explicitly mentioned in the guidelines.

**Comment by diasdavid** [comment]
@vmx yes, good catch. Mind adding that in through a PR? 

@VictorBjelkholm just got what I fear when we shut out maintainers and tech leads from being able to push to master

```
 ⠋ Push to GitHub
   Generate GitHub Release
   Publish documentation
   Publish to npm
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "continuous-integration/jenkins/pr-merge" is expected. At least 1 approving review is required by reviewers with write access.
To github.com:ipfs/js-ipfs-repo.git
 * [new tag]         v0.20.1 -> v0.20.1
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:ipfs/js-ipfs-repo.git'

Cannot create property 'context' on string 'remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "continuous-integration/jenkins/pr-merge" is expected. At least 1 approving review is required by reviewers with write access.
To github.com:ipfs/js-ipfs-repo.git
 * [new tag]         v0.20.1 -> v0.20.1
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:ipfs/js-ipfs-repo.git'
```

``

**Comment by VictorBjelkholm** [comment]
Hm, that's sad, as we cannot guarantee that master is always green then... Is there a way around this? What is it trying to push here, it's the changelog right?

**Comment by diasdavid** [comment]
@VictorBjelkholm changelog, version bump and tag.

We could hypothetically have aegir create a branch for the release that has to be merged after the publish

**Comment by wanderer** [comment]
@diasdavid  done! on the npm publish perms, does anyone else need perms for ipld-graph-builder?

**Comment by diasdavid** [comment]
@wanderer me (daviddias on npm) and @vmx (vmx on npm also), please. Thank you!

**Comment by vasco-santos** [comment]
@diasdavid I created the PR for the [js-ipfsd-ctl](https://github.com/ipfs/js-ipfsd-ctl/pull/240) repo.

**Comment by diasdavid** [comment]
This happened, every module has a new Lead Maintainer now. Thank you everyone! ❤️
