### ISSUE TITLE
Define a PR merge policy

### ISSUE THREAD

**Issue by vmx** [ipfs/pm#606]
There was a PR in AEgir that looked good to me and was ready to be merged. Though I didn't know if I should go ahead or wait for the Captain (resp. probably responsible person) to review and merge it.

After a quick discussion on IRC with @lgierth we thought about having some policy for merging things. Individual repos should of course have the power to have their own policy, but there should be a default one and perhaps some well defined ones one can link to.

Some ideas for policies:

 - Only Captain merges
 - Anyone with merge permissions can merge
 - Original author merges if he has permission: I prefer this one as there might be inter-dependencies/obstacles only the author is aware of (he/she might be on holidays the next weeks and doesn't want to risk breakage before that). That one would of course need a fall-back policy if it's a PR from someone without permission.

**Comment by lgierth** [comment]
Yeah I think this has never been written down explicitly. In most repos, we've merged after at least one positive review. In a few individual repos, the captain merges (e.g. go-ipfs).

I'd go with "merge after at least one review" by default, and leave room for individual repos to note otherwise.

**Comment by Stebalien** [comment]
This also really depends on the PR. For, e.g., "fix a broken link in the readme" fixes, I often just merge it myself (although still go through a PR). For mass gx release/updates, I occasionally push to master because merging 50+ PRs is just a waste of time.

**Comment by dryajov** [comment]
I think 2 & 3 both make sense. I can see most PRs being ready after a few rounds of review and its usually obvious when they can be merged, however, in specific cases the owner thinks its shouldn't be merged (or someone else for that matter), it should be made clear in the PR, preferably with a note in the top comment.  

Something like **WARNING, DO NOT MERGE YET!!!!**

Or even better, maybe we can have a label that marks a pr as not to be merged?

Great to have this issue, thanks for bringing it up @vmx!

**Comment by djdv** [comment]
@dryajov 
>a label that marks a pr as not to be merged

I like the idea of PR's either being marked with WIP in the title or tagged with WIP. Very easy for both parties to manage. When you create a PR, tag it, when you're done, untag it.
When reviewing PRs just make sure to skip ones tagged WIP.

**Comment by dryajov** [comment]
@djdv yeah, that works as well 👍

**Comment by diasdavid** [comment]
Duplicated of https://github.com/ipfs/pm/issues/238, let's continue the conversation there.
