### ISSUE TITLE
Hangouts on Air

### ISSUE THREAD

**Issue by Dignifiedquire** [ipfs/pm#61]
We talked about it last week that we want to provide a way to record the Monday Hangouts, so I've gone and setup things for this: 

* Youtube Channel: [IPFS](https://www.youtube.com/channel/UCdjsUXJ3QawK4O5L1kqqsew)
* Linked Google Plus [account](https://plus.google.com/108638684245894749879)
* First hangout on air scheduled for the apps hangout: https://www.youtube.com/watch?v=m2dDOtp1PK4

**Comment by diasdavid** [comment]
oh nice! :D Was this created with an @ipfs.io account? it would be cool if you can have one like youtube@ipfs.io and schedule things from there, because then we can have 15 people instead of 10 in a Google Hangout (Google Apps accounts get 5 more)

@lgierth can you set up this account?

**Comment by Dignifiedquire** [comment]
@diasdavid no it was not, if you can get me access to one, I should be able to transfer it though.

**Comment by Dignifiedquire** [comment]
@lgierth @jbenet I also need access to the google analytics briefly to verify that https://ipfs.io is the connected site for the accounts.

**Comment by RichardLitt** [comment]
:+1: This is awesome!

**Comment by Dignifiedquire** [comment]
Schedule for tonight is up: https://plus.google.com/u/2/b/108638684245894749879/events

**Comment by lgierth** [comment]
> @lgierth can you set up this account?

Yeah probably add google apps and analytics to meldium (don't have access either) -- i'll open a meta-issue for that

**Comment by lgierth** [comment]
> record the Monday Hangouts

This kinda discourages me from using the webcam -- but I didn't get to getting one yet anyhow ;)

**Comment by Dignifiedquire** [comment]
Closing as we have found a solution for now in #63
