### ISSUE TITLE
All Hands May 03

### ISSUE THREAD

**Issue by ipfs-helper** [ipfs/pm#619]
# Agenda and Notes

Please add your agenda items before the call.

Endeavour      | Lead            | Notetaker | Time (PST - UTC - CET) | Pad
:------------: | :-------------: | :-------: | :--------------------: | :----:
All Hands Call | @dgrisham    | @diasdavid	  | 9:00 **16:00** 18:00  | [agenda and notes](https://cryptpad.fr/code/#/1/edit/SJiMDRuILbNrnD7PPNqWlA/HcX0hkCqzZW3iRVK7r8b08Xb/)

Zoom link for joining the call: https://zoom.us/j/779351365

**Comment by VictorBjelkholm** [comment]
Hm, wrong date so clearly not working yet...
