### ISSUE TITLE
All Hands May 7

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/pm#627]
# Agenda and Notes

Please add your agenda items before the call.

Endeavour      | Moderator            | Notetaker | Time (PST - UTC - CET) | Pad
:------------: | :-------------: | :-------: | :--------------------: | :----:
All Hands Call | @flyingzumwalt     | @hsanjuan  | 9:00 **16:00** 18:00  | [agenda and notes](https://hackmd.io/4SORVxfSTCitfARbn8GFXQ#)

Zoom link for joining the call: https://zoom.us/j/779351365

**Comment by diasdavid** [comment]
What happened to the bot? @VictorBjelkholm ?

**Comment by VictorBjelkholm** [comment]
@diasdavid hm, we're using dokku on the server where it's deployed (cloud.ipfs.team). Somehow, the connection to api.github.com could not be made, so it couldn't create the issue.

This is not the first time we have issues with the cloud.ipfs.team instance, so I'm gonna redeploy the sprint-helper on it's own host instead.
