### ISSUE TITLE
Recording Sync Hangouts ?

### ISSUE THREAD

**Issue by jbenet** [ipfs/pm#63]
Thanks to @Dignifiedquire for taking the initiative to start recording the sync hangouts.

---

However, before we actually keep these and institute a new policy of doing this recording, we need to think through whether we actually do want to do this. These will become part of the **public and permanent record of everyone involved. Everything said will be archived + searchable forever.**

I for one do not want hangouts around which could be used against any member of the ipfs community in the future (suppose we discuss censorship resistance and someone from china participates and says something not very acceptable to the censors there...).

---

There is also the question of presentation to the viewers-- archival for our own purposes is different from broadcast + archival for interested viewers. i would think that _if_ we're going to have the downsides of a public broadcast/archive then we should have the upsides too, namely, a good source of information for viewers who would like to explore and join our community. If so, then we should:

- be much more efficient with our use of time. (today's infra hangout was >7min of banter as people waited)
- be much more precise + professional
- come up with a policy of what is "not ok" to discuss on air. i want to still be able to accept _anybody_ who wants to come in + discuss things, but if so then we also need a way of handling trolls or undesirable situations. these will come up (have already happened to me in live recording)
- make sure every participant is aware of this policy before they join the hangout
- announce at the beginning of every hangout that these are being recorded.
- so far we've been using the hangouts as a way to "hang out" as well, as a regular face-to-face time. If we're going to record + archive these though, i think we'll have to separate this out.

**Comment by whyrusleeping** [comment]
I'm fine with deleting them after the fact, but keep the 'on air' stuff so that we can have more people watching live

**Comment by lgierth** [comment]
I'm not very enthusiastic about recording the hangouts -- apart from the mentioned concerns, it may discourage people form using their webcam, and it's nice to actually see you folks at hangouts :)

Although it could be useful to have recorded "general" hangout, something like a virtual meetup?

> keep the 'on air' stuff so that we can have more people watching live

agreed

**Comment by jbenet** [comment]
+1 on a general hangout-- we could have an "end of the week" TGIF type thing for the whole community to hang out + talk about things. i've been wanting to do it over a minecraft server or something similar.

**Comment by nicola** [comment]
That is a great idea, it would be the ipfs weekly for people to do announcements & co

**Comment by Dignifiedquire** [comment]
I will write more thoughts on this later today, but for now I have made all the recordings from yesterday private, so nobody has to worry and we can have this discussion stress free.

**Comment by RichardLitt** [comment]
> +1 on a general hangout-- we could have an "end of the week" TGIF type thing for the whole community to hang out + talk about things. i've been wanting to do it over a minecraft server or something similar.

This would be fun. 

I'm for not recording the videos, given the concerns above. I'm also way for better notetaking.

**Comment by diasdavid** [comment]
Community Hangout anyone? https://github.com/ipfs/community/issues/28 :D Let's do it :)

**Comment by Dignifiedquire** [comment]
Given the concerns over publishing recorded versions of the sync, I think it's probably better to not do so. However I change the settings in a way that all recordings are private so we can still record and have them for our own record (at least until we decide to delete them) and could rewatch them to update the notes if something is missed for example. So I suggest that for today we 

* use hangouts on air for live streaming
* store the videos privately in our youtube account 
* delete them after x days when we are sure we have captured all important info into notes

---

On another note, things like the infrastructure hangout last week were effectively not needed as @lgierth and @jbenet were not around and I think some of the later hangouts did not happen at all, so I suggest updating the list to include only those that are sure to happen, if the hangout lead is not around and has not appointed someone to take over for him to drop the hangout for that day. In addition it might make sense to have one general sync for small things that don't fit into the other categories, or are simply not constant enough to have their own sync every week.

--- 

On the other note I'm very much for establishing a community hangout, as there are often things one wants to talk about and they are forced into the sync at the moment. The results of that are that both are mixed and we do not have enough time for neither.

**Comment by jbenet** [comment]
:+1: on the thoughts re recordings

> On another note, things like the infrastructure hangout last week were effectively not needed as @lgierth and @jbenet were not around and I think some of the later hangouts did not happen at all, so I suggest updating the list to include only those that are sure to happen, if the hangout lead is not around and has not appointed someone to take over for him to drop the hangout for that day.

Agreed!

> In addition it might make sense to have one general sync for small things that don't fit into the other categories, or are simply not constant enough to have their own sync every week.

Sounds good to me. We could actually start with this? (next week, too late for this one)

> On the other note I'm very much for establishing a community hangout, as there are often things one wants to talk about and they are forced into the sync at the moment. The results of that are that both are mixed and we do not have enough time for neither.

:+1: sounds good.

**Comment by Dignifiedquire** [comment]
As this is all setup now, @RichardLitt can you close this please?

**Comment by RichardLitt** [comment]
:)
