### ISSUE TITLE
 All Hands May 14

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/pm#630]
# Agenda and Notes

Please add your agenda items before the call.

Endeavour      | Moderator            | Notetaker | Time (PST - UTC - CET) | Pad
:------------: | :-------------: | :-------: | :--------------------: | :----:
All Hands Call | TBD     | TBD  | 9:00 **16:00** 18:00  | [agenda and notes](https://hackmd.io/ywvNV2ujRvqu0w2D_d1pnA#)

Zoom link for joining the call: https://zoom.us/j/779351365

**Comment by djdv** [comment]
Agenda needs to be updated to use: https://docs.google.com/document/d/1WHyIZhBo2eEgYXlZ5HLHg6a6ZWTH3tV848sWkYBJjJA/edit?usp=sharing
