### ISSUE TITLE
All Hands June 11, 2018

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/pm#641]
# Agenda and Notes

Please add your agenda items before the call!

Endeavour      | Moderator            | Notetaker | Time (PST - UTC - CET) | Pad
:------------: | :-------------: | :-------: | :--------------------: | :----:
All Hands Call | [TBD]    | [TBD]  | 9:00 - **16:00** - 18:00  | [agenda and notes](https://docs.google.com/document/d/1WHyIZhBo2eEgYXlZ5HLHg6a6ZWTH3tV848sWkYBJjJA/edit#heading=h.hz5t61tdc5r6/)

Zoom link for joining the call: https://zoom.us/j/779351365

**Comment by lanzafame** [comment]
@Mr0grog @lidel the `NOBODY HAS PERMISSIONS HERE` comment re: start recording, does that mean that there was no recording of the All Hands or just no live streaming of it to YouTube?

**Comment by Mr0grog** [comment]
No recording or streaming at all. There has to be someone with a PL account present to do (or delegate permission to do) either.

**Comment by lanzafame** [comment]
😢 ah well, thanks for the great notes 👍
