### ISSUE TITLE
Moving from editing top comment to commenting individual sprints

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#65]
We used to edit the top comment of a sprint to include our todos. I don't think we should keep doing this. 

### Why

- Not everyone does it
- It discourages people who do not have write access to the top editors comment
- Throwing in a comment is easier
- Throwing a comment in provides better time stamping and provenance
- Editing leads to errors sometimes
- It's confusing to use both. 

### Suggestion

- [ ] Change the documentation to make it clear that you just need to add a comment with your sprint to dos each sprint. 
- [ ] Remove the `### [@Githubusername](dsdfs)` link, as it isn't useful for anyone and takes time.

**Comment by whyrusleeping** [comment]
:+1:

**Comment by Dignifiedquire** [comment]
:+1:

**Comment by harlantwood** [comment]
+1

**Comment by jbenet** [comment]
:+1:

**Comment by jbenet** [comment]
(this was a holdover from adding our todos in an etherpad. am totally fine moving to just messages on the sprint)

**Comment by diasdavid** [comment]
I'm good both ways :)
