### ISSUE TITLE
Upgrade Golang Core Dev Comms, help everyone get a better shared understanding and take Golang Core Dev Velocity to the stars 🚀🌌

### ISSUE THREAD

**Issue by diasdavid** [ipfs/pm#673]
Hi Golang Core Dev Team (i.e. go-ipfs, go-libp2p and go-ipld devs)!

Me, @whyrusleeping, @Stebalien and @jbenet have been discussing in length what are current needs of the Golang Devs of the IPFS, libp2p and IPLD projects and how we can help everyone be productive and therefore successful. Our thinking is that we can improve communication a lot, helping everyone get a better shared understanding of the project priorities and capacity available, so that we know better how to allocate work and enable everyone to have laser focus on a set of tasks.

There is no perfect recipe that works for every team and it requires one to clearly understand everyone's needs and design something for it (which includes both adding and removing things :)). I'll be leading the effort as a cross pollination agent, focused on improving what exists right now and I'll be reaching out to everyone to learn from you directly (check for email!).

Meanwhile, there are a set of healthy habits that other teams/working groups have adopted and that we want to try for Golang Core Dev as well. I believe that these will be a obvious for everyone.

- Host a **Weekly Core Dev Sync**, similar to #650, but for Golang, in which each team members gets to update everyone on progress, things that got blocked and what people will be working next. 
  - We have a perfect slot for it right after the JS Core Dev Weekly Sync and before the libp2p biweekly, [10am Pacific, 7pm CET](https://www.worldtimebuddy.com/?qm=1&lid=5391959,2267057,2950159,264371&h=5391959&date=2018-8-13&sln=10-10.5). 
  - **Let's start it next week, August 13**. Let me know if timing doesn't work for you.
  - I've added it to the [Community Calendar](https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com&ctz=UTC)
- Develop the habit of grooming the Waffle Boards for go-ipfs, go-libp2p and go-ipld and transform it into a useful resource to track work and focus + to invite others in the community to contribute.
  - Adopt the Grooming described in https://github.com/ipfs/pm/blob/master/JS_CORE_DEV_MGMT.md (half page read)
  - I went ahead and:
    - Created http://waffle.io/ipld/go-ipld
    - Updated https://waffle.io/ipfs/go-ipfs with the latest go-ipfs repos
    - Updated https://waffle.io/libp2p/go-libp2p with the latest go-libp2p repos
    - Created a "whole view" waffle board, find it at http://waffle.io/ipfs/go-waffle
- Upgrade the [Go Contributing Guidelines](https://github.com/ipfs/community/blob/master/go-code-guidelines.md) so that it is a good resource for contributors to use as a reference point, saving time from the Core Maintainers from "education by PR" on what you expect a PR to look like. See the [JS Contributing Guidelines](https://github.com/ipfs/community/blob/master/js-code-guidelines.md) for compassion.

Another thing I want us to consider is adopting a Lead Maintainer Protocol such as https://github.com/ipfs/community/blob/master/js-code-guidelines.md#tech-leads-and-lead-maintainers. Please go through that section (less than 1 page) and comment here your thoughts.

Pinging here the people that I know that work on any of the Go pieces of the IPFS, libp2p and IPLD projects. If I miss anyone, please ping them too :)

@whyrusleeping @Stebalien @kevina @keks @Kubuxu @magik6k @schomatis @djdv @warpfork @marten-seemann @bigs @lgierth

**Comment by kevina** [comment]
> Let's start it next week, August 13. Let me know if timing doesn't work for you.

I have a conflict at this time next week.  Other weeks at this time should be okay.

**Comment by whyrusleeping** [comment]
I also have a conflict at that time. Can probably move it though. Rest sounds like a good way to start moving forward. Will comment on the 'lead maintainer protocol' soon.

**Comment by Stebalien** [comment]
Sounds like a good plan and the time works for me. However, it would be *nice* if we could get @hsanjuan there and that time conflicts with the cluster standup. @hsanjuan any interest in attending?

**Comment by diasdavid** [comment]
Thank you for following up. I've created the tracking issue for the Weekly Syncs -- https://github.com/ipfs/pm/issues/674 (To be automated soon https://github.com/ipfs/testing/issues/31)

@kevina, understood. Can you post your update for this time via text (add it to the cryptpad listed on https://github.com/ipfs/pm/issues/674). @marten-seemann is going to do the same.

@whyrusleeping hoping that you can make your schedule work. Thank you 🙏🏽

@Stebalien I didn't find the Cluster Standup on the IPFS Community Calendar nor listed here https://github.com/ipfs/ipfs-cluster. @hsanjuan could you confirm if it still happens?

**Comment by whyrusleeping** [comment]
@diasdavid I actually can't make anything on monday. I've got a full day event going on.

**Comment by bigs** [comment]
think it’s a great idea. would wanna make sure the weekly was purely to report in and less to discuss issues at length. perhaps that could happen over irc afterwards?

**Comment by bigs** [comment]
yep, sounds great :) just mean it shouldn’t get too technical or i think people will burn out!

**Comment by schomatis** [comment]
@diasdavid Thanks for all this info and organizational tools!!

(can't edit in this repo: the new link for the management doc is https://github.com/ipfs/pm/blob/master/JS_CORE_DEV_MGMT.md)

**Comment by lgierth** [comment]
Infra Weekly Sync is at 5p UTC / 7p CET too -- I'll look into a different time there, but when in doubt I'll rather skip the Go meeting (for now!) since my Go contributions are currently minuscule anyway.

Also one way or the other I'll have to skip this Monday :)

**Comment by whyrusleeping** [comment]
I would prefer to not have these recorded.

**Comment by marten-seemann** [comment]
A recording would be super helpful for people in non-EU/US timezones. But maybe we can make them accessible only for team members?

**Comment by hsanjuan** [comment]
hey, cluster standup still happens right after ipfs call. It should be over before this one starts.

I would recommend that everyone writes down whatever update they want to share in advance and that any feedback is noted too if person is not present. I have the feeling that a 2 minutes read is always better than watching a 30 minutes video. As a matter of fact, I also would prefer to not have these recorded, but properly logged instead (limiting access is good though).

> Constrained to 30 minutes, no more, no less. (IRC would lead to things ballooning.)

I think sync meetings should not have a minimum length limit. If one day we can be done in 10 mins, we probably should.

**Comment by diasdavid** [comment]
> cluster standup still happens right after ipfs call. It should be over before this one starts.

Perfect, no conflicts then. Still, better make sure to add the Cluster Sync up to the IPFS Community Calendar, otherwise someone might try to add something for to that slot in the future. 

> I would recommend that everyone writes down whatever update they want to share in advance

👍 

> If one day we can be done in 10 mins, we probably should.

You are right. I really meant only `no more`.

**Comment by hsanjuan** [comment]
> Perfect, no conflicts then. Still, better make sure to add the Cluster Sync up to the IPFS Community Calendar, otherwise someone might try to add something for to that slot in the future.

I never got access to that calendar.

**Comment by diasdavid** [comment]
@hsanjuan I can add it for you :) Just give me an ok and I'll create an event there.
