### ISSUE TITLE
Need moderator for all hands August 27, 2018

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/pm#684]
@Mr0grog will be traveling next week and unable to moderate the IPFS all hands call on Monday, August 27th. We need a volunteer for that day. Your job is:

- Post a notice about the meeting when it's about to happen on #ipfs and #ipfs-dev in IRC
- Be on the call on time
- Make sure there's a notetaker
- Make sure someone starts recording
- Move the meeting along and make sure everything is covered in a timely fashion :)

Please post here or, if you are on the Protocol Labs Slack, DM @Mr0grog there if you’d like to volunteer.

**Comment by diasdavid** [comment]
Seems that this slipped through the cracks. I took the lead today.
