### ISSUE TITLE
2018 Q4 OKR Planning - It's that time of the quarter again ✨

### ISSUE THREAD

**Issue by diasdavid** [ipfs/pm#698]
With two weeks left in this quarter, it is time to report the progress made, retrospect on it and plan the work we want to for next Quarter.

Planning the next Quarter comes with no new surprises, our goal is to have the [**2018 Q4 OKR Spreadsheet**](https://docs.google.com/spreadsheets/d/139lROP7-Ee4M4S7A_IO4iIgSgugYm7dct620LYnalII/edit#gid=1681757723) filled by the time the next quarter starts, that is October 1st.

Before planning the next quarter, it is important to **score the KRs you owned during this quarter**. Do it ASAP on the [2018 Q3 OKR Spreadsheet](https://docs.google.com/spreadsheets/d/19vjigg4locq4fO6JXyobS2yTx-k-fSzlFM5ngZDPDbQ/edit#gid=274358435). I know that in 2 weeks a lot can happen, but you should have a good grasp on what will be finished by now and it is ok to adjust any individual KR 2 weeks from now too.

To prepare this next quarter, I want to invite all the Working Groups to adopt or at least experiment with two of the most healthy habits that have emerged from other IPFS Working Groups, these are run a Async Retrospective of the Quarter__ and __Planning OKRs in the Open__.

### Async Retrospective of the Quarter

Running an Async Retrospective will give everyone in the team to clearly communicate what was achieved and not achieved in the quarter. It will also give the opportunity to signal things that can be improved and these can go from communication, structure, launch of features or anything that a team member finds important for the team to know.

These retrospectives enable us to check in with ourselves and prepare the following quarter better taking into consideration everything happened in the past. It also gives our future selves a way to check in with the past and see how far we have progressed.

You can see a great example of one of these with the [JS Core Dev Q2 Retrospective](https://docs.google.com/document/d/1N4xAIHFfbr3ZpUSaPC0wJaruNQNM8nxTt3nai9TtvSI/edit#heading=h.y8lua98atzlj). The whole team got to voice and learn from everyone else perspective.

We have reached a format for the retrospective that is quite simple and easy to complete. With the [Template](https://docs.google.com/document/d/1cpMAsP6giMvGR_jaBS4nzdqx2GCOvwOjTbOhLAEPkGI/edit#), all you need to do is to create a copy of [this doc](https://docs.google.com/document/d/1cpMAsP6giMvGR_jaBS4nzdqx2GCOvwOjTbOhLAEPkGI/edit#) and share it with your Working Group members.

### Planning OKRs in the Open

This is one of my favorite practices that has emerged in the IPFS Community by the IPFS Working Groups, planning OKRs in the Open.

The typical way to do this is simply by opening a PR on the entry point repo of the Working Group. In this PR, everyone gets to share their own view of the world and describe which Objectives and Key Results should be tackled for next quarter, community and users included!

Once everyone has shared theirs, the Captain takes the role of crafting a version of the final possible list of KRs based on everyone's proposal and needs of the project. Only then, people volunteer to take on certain Key Results and assign Priorities Collectively.

A suggestion is that each individual should not take anymore than two P0 items (unless they are quite small tasks). There are no recommended limits for P1, P2, P3 and P4s.

Also, if you know if you have Holidays, Conference Attendance or some other event planned, do the _timing exercise_ to make sure you are not trying to allocate too much work for the time you will have available. Another golden rule is to take the number of days in the Quarter (Q4 is 12 Weeks, that is 60 days) and take out the days you will be out and then plan for only 60% of that time. We propose to save 40% of time for putting out fires or surprise endeavors that always appear during the quarter.

Just for an example, given that the quarter is 60 days, imagine that I plan to take on 8 days of time off and spent 10 days attending/speaking at conferences, I realistically only have 42 days total. If we assume a work day of 8 hours a day, that is 336 hours. Cutting that to just 60% means that I have roughly only 201.6 hours of work I should plan for, otherwise I risk of not being able to achieve my KRs which might be dependencies of other projects.

Find great examples of this being done in the past at:

- https://github.com/ipfs/js-ipfs/pull/1281
- https://github.com/ipfs/js-ipfs/pull/1409
- https://github.com/libp2p/js-libp2p/pull/207
- https://github.com/ipfs/in-web-browsers/pull/73

These PRs become records of the reasoning behind deciding on each KR.

I'll post in this issue the urls to the news PRs for the OKR planning for the Working Groups that adopt this strategy. So far we have:

- IPFS WGs
  - [js-ipfs OKR Planning](https://github.com/ipfs/js-ipfs/pull/1566)
  - [Web Browsers OKR Planning](https://github.com/ipfs/in-web-browsers/issues/110)
  - [go-ipfs OKR Planning](https://github.com/ipfs/go-ipfs/pull/5474)
- libp2p
  - [js-libp2p OKR Planning](https://github.com/libp2p/js-libp2p/pull/247)
  - [go-libp2p OKR Planning](https://github.com/libp2p/go-libp2p/pull/425)
- IPLD
  - [js-ipld OKR Planning](https://github.com/ipld/js-ipld/pull/148)

WG Captains, when your WG has finished planning the OKRs, make sure to update the [**2018 Q4 OKR Spreadsheet**](https://docs.google.com/spreadsheets/d/139lROP7-Ee4M4S7A_IO4iIgSgugYm7dct620LYnalII/edit#gid=1681757723)

I can't wait to see the retrospectives and the OKR scoring and be able to comprehend everything that has been achieved in 2018 Q3 (I know it is a lot of exciting stuff!) and I look forward to a stellar 2018 Q4!

PS: I'm assigning the WG Captains to this issue to get it on your radar. However, remember that it is a whole WG effort. Github just doesn't me assign everyone in one single issue :)

**Comment by jamiew** [comment]
I am interested in following along but all the linked Google Docs are private. Was that on purpose? Also a huge fan of y'all planning things in the open

**Comment by diasdavid** [comment]
Thanks for catching that @jamiew! My mistake (ETOOMANYPERMISSIONS), I went through the docs and added view/comment permissions through link share. If you happen to see one I missed, let me know or just ask for access through the Google Docs interface and then I'll know right away which one :)

**Comment by momack2** [comment]
Recording of todays all hands with discussion of how to do OKRs in the open and next steps for grading Q3 OKRs, retrospecting, and planning for Q4: https://youtu.be/5VgjykmLYIE?t=2m27s

**Comment by jamiew** [comment]
@diasdavid cool, I just requested access to two that were still private, including "2018 Q3 OKR spreadsheet"

And a big thank you to you & the whole team for trying out a format like this. Really great for all of us following along.

**Comment by diasdavid** [comment]
Status Update. Some teams have already landed their OKRs and are ready for review, these teams are:

- IPFS
  - [**ipfs-cluster**](https://docs.google.com/spreadsheets/d/139lROP7-Ee4M4S7A_IO4iIgSgugYm7dct620LYnalII/edit#gid=2055463539)
  - [**ipfs-infrastructure**](https://docs.google.com/spreadsheets/d/139lROP7-Ee4M4S7A_IO4iIgSgugYm7dct620LYnalII/edit#gid=729478084)
  - [**community**](https://docs.google.com/spreadsheets/d/139lROP7-Ee4M4S7A_IO4iIgSgugYm7dct620LYnalII/edit#gid=1876434856)

**Comment by momack2** [comment]
Awesome work! Reminder for everyone to *also* grade their Q3 OKRs based on
how far they actually got this quarter so we can estimate better next time:
https://docs.google.com/spreadsheets/d/19vjigg4locq4fO6JXyobS2yTx-k-fSzlFM5ngZDPDbQ

**Comment by olizilla** [comment]
First draft of the **[ipfs-gui](https://docs.google.com/spreadsheets/d/139lROP7-Ee4M4S7A_IO4iIgSgugYm7dct620LYnalII/edit#gid=1841105909)** OKRs are up for feedback. 

...and over here for the folks following along on github https://github.com/ipfs/ipfs-gui/issues/67

**Comment by lidel** [comment]
Draft of the **[in-web-browsers](https://docs.google.com/spreadsheets/d/139lROP7-Ee4M4S7A_IO4iIgSgugYm7dct620LYnalII/#gid=755202447)** OKRs – also up for feedback

**Comment by momack2** [comment]
Congrats to [js-ipfs](https://docs.google.com/spreadsheets/d/19vjigg4locq4fO6JXyobS2yTx-k-fSzlFM5ngZDPDbQ/edit#gid=274358435), [dynamic data](https://docs.google.com/spreadsheets/d/19vjigg4locq4fO6JXyobS2yTx-k-fSzlFM5ngZDPDbQ/edit#gid=412099511), [ipfs-gui](https://docs.google.com/spreadsheets/d/19vjigg4locq4fO6JXyobS2yTx-k-fSzlFM5ngZDPDbQ/edit#gid=1841105909), [web browsers](https://docs.google.com/spreadsheets/d/19vjigg4locq4fO6JXyobS2yTx-k-fSzlFM5ngZDPDbQ/edit#gid=755202447), [cluster](https://docs.google.com/spreadsheets/d/19vjigg4locq4fO6JXyobS2yTx-k-fSzlFM5ngZDPDbQ/edit#gid=2055463539), and [infra](https://docs.google.com/spreadsheets/d/1RktUwzZNambdZBokC0UNdSJEF5WCZmX9nZCTOSn9EdI/edit#gid=0) on finishing grading their Q3 OKRs!  Just go-ipfs and dx left to go! =]

When thinking about how to share/report on these scores - try to focus on the high-priority (~P0) items and call out any that got dropped/blocked (score of <=0.5) in addition to highlighting top wins. Any meta points about the planning process and lessons learned are also useful to document/aggregate so we can learn from each other. <3

**Comment by pgte** [comment]
The [first draft of the Q4 Dynamic Data and Capabilities WG](https://docs.google.com/spreadsheets/d/139lROP7-Ee4M4S7A_IO4iIgSgugYm7dct620LYnalII/edit?ts=5b9fcc7c#gid=412099511) is ready for feedback.

**Comment by diasdavid** [comment]
Now the OKRs planning in the open all lives in this repo at -- https://github.com/ipfs/pm/tree/master/OKR -- with -- https://github.com/ipfs/pm/pull/719

**Comment by diasdavid** [comment]
Closing this issue for now, see you all again for another round at the end of the quarter :)
