### ISSUE TITLE
"needs review" label for items that are currently blocked waiting for a review

### ISSUE THREAD

**Issue by diasdavid** [ipfs/pm#78]
Following Sprint Jan 5 discussion on IRC and to avoid having someone blocked waiting for review from someone else, let's start adding a label "needs review" to the issues or pull requests that need attention.

To make this a collaborative effort and to unblock devs as soon as we can, let's make sure to spend at least 30 mins a day, opening this link https://github.com/issues?utf8=✓&q=is%3Aopen+org%3Aipfs+label%3A"needs+review" and reviewing as much as we can that is currently open.

Note: Once you review and give the necessary input, make sure to remove the label so that others don't have to parse the entire thread in order to understand that the request was already fulfilled.

### [Items that currently need review](https://github.com/issues?utf8=✓&q=is%3Aopen+org%3Aipfs+label%3A"needs+review")

**Comment by diasdavid** [comment]
I've been opening the `needs review` label every day (assigned a reminder to myself so that I make sure I don't miss any) and so far, I haven't seen any there. 

If anyone has things they need review (code+specs+docks+impl), add the label and we will be review it ASAP :)

**Comment by RichardLitt** [comment]
Reopen this issue if no one uses this label.

**Comment by dignifiedquire** [comment]
Please leave it open, that way I always find the link

**Comment by RichardLitt** [comment]
@dignifiedquire No; if you need it, there should be a better place to reach it. Will PR somewhere else.

**Comment by diasdavid** [comment]
## Update

We might not need the `needs review` label anymore, as Github now provides a feature to explicitly request reviews for a PR and a way to communicate that such review was performed.

Shall we drop the `needs review` label?

**Comment by RichardLitt** [comment]
You can't search by those requests at the moment, that I can tell. So, I don't think so.
