### ISSUE TITLE
Do we want to move our sprint day to Tuesday because of president's day?

### ISSUE THREAD

**Issue by jbenet** [ipfs/pm#90]
this monday is a national holiday in the US. maybe we should move sprint to tuesday. cc @RichardLitt thoughts?

(Personally, am just fine having it monday. I will be catching a plane Tue though so may not be able to be in the later conversations.)

**Comment by noffle** [comment]
My preference is moving to Tuesday. (my SO has Monday off)

**Comment by lgierth** [comment]
I'll have to skip sync but I'll be there for the hangouts

**Comment by whyrusleeping** [comment]
Preference of tuesday here.

**Comment by RichardLitt** [comment]
Also a preference for Tuesday. I say we should move it. @lgierth do you mean you'll have to skip the sync on Tuesday, or on Monday?

**Comment by lgierth** [comment]
on tuesday - have something to do at 5pm UTC that I can't cancel, but I'll be back right in time for the infrastructure hangout.

**Comment by lgierth** [comment]
so i'm fine with tuesday

**Comment by diasdavid** [comment]
I can swing it too :)

**Comment by RichardLitt** [comment]
Let's move it to Tuesday.

**Comment by RichardLitt** [comment]
Moved. https://github.com/ipfs/pm/issues/91
