### ISSUE TITLE
Sprint change to once every two weeks

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#96]
So, the current sprint and sync is really hard on our system. Every Monday, the productivity for the core developers is cut way down by having to be around for five or six hours. Sometimes, not that much has been done, but we still need to fill up half an hour of one person chatting during the endeavors, for each endeavor. 

Let's move to once every other week. On the Monday in between -- for starters, next Monday the 29th -- let's have a short community call, where we simply talk about where we are and any immediate blockers. This will be like the normal sync, but over Google Hangouts, and not long. 

What do you say?

cc @whyrusleeping @lgierth @diasdavid @jbenet @dignifiedquire @harlantwood @haadcode @noffle @voxelot @Kubuxu

**Comment by whyrusleeping** [comment]
:+1: No argument from me.

**Comment by dignifiedquire** [comment]
sounds good, but I think in addition everyone should try to be around for an hour afterwards in IRC so we have a fixed point to ask questions/for help.

**Comment by whyrusleeping** [comment]
agreed, a while ago we tried to get everyone to be around and available during a certain common overlapping time period, something like 1800UTC to 2100UTC, or something

**Comment by haadcode** [comment]
sounds like a good idea!

**Comment by noffle** [comment]
Yeah! Let's give it a try and iterate/refine as we go!

**Comment by diasdavid** [comment]
I agree with all of the above :)

**Comment by jbenet** [comment]
lets do it!

**Comment by Kubuxu** [comment]
Trying new things is important, if it works out, awesome, if not, there is next iteration.

**Comment by lgierth** [comment]
sounds great to me :+1: :+1:

**Comment by diasdavid** [comment]
This has been ongoing for some sprints now, I believe that everyone is really happy with the reduced overhead in communication and with the ability to focus in larger pieces per sprint. 

Closing this issue, open if need be.
